### ISSUE TITLE
bash/zsh auto-completion

### ISSUE THREAD

**Issue by na--** [grafana/k6#1065]
Since we're using `cobra` anyway, it seems like there might be an easy way to generate auto-completion definitions: https://github.com/spf13/cobra/blob/master/bash_completions.md

Ideally, we should then distribute those with the deb/rpm/homebrew/etc. packages.

**Comment by MStoykov** [comment]
The [v1.2.0](https://github.com/spf13/cobra/releases/tag/v1.2.0) of cobra made the `completion` command automatic. 

Additionally, I found that for the current user and bash you can do:
```
mkdir -p ~/.local/share/bash-completion/completions/
./k6 completion bash > ~/.local/share/bash-completion/completions/k6
```
which might be useful even if we decide to put them in the deb/rpm/homebrew.

**Comment by na--** [comment]
Turns out the [k6 AUR package](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=k6) already has bash/zsh/fish auto-completion files :sweat_smile: https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=k6

**Comment by codebien** [comment]
Closing as this is already available via `k6 completion` command automatically generated by Cobra that we had updated a long time ago.
