### ISSUE TITLE
Investigate and improve IP blacklisting performance

### ISSUE THREAD

**Issue by na--** [grafana/k6#1256]
The current IP blacklisting code is very naive and unoptimized: https://github.com/loadimpact/k6/blob/a2e1c6f4e6207d69461a1b0f24c3aa2c72233101/lib/netext/dialer.go#L84-L88

We need to investigate whether that's an issue when we have hundreds of IP ranges blacklisted... If it is, we probably should use something like https://github.com/yl2chen/cidranger

**Comment by olegbespalov** [comment]
After an internal conversation, we decided to close the issue since the original case wasn't an issue. If our users found out any performance issue we could re-open the issue again.
