### ISSUE TITLE
http.batch() should not accept more than one argument

### ISSUE THREAD

**Issue by na--** [grafana/k6#1289]
It took me a while to understand why this code didn't work :face_with_head_bandage: :
```js
// ...
let responses = http.batch(
    ["GET", "https://test.loadimpact.com/"],
    ["GET", "https://test.loadimpact.com/", null, { responseType: "text" }],
);
// ...
```

The only warning I saw was
```
WARN[0000] Request Failed                                error="Get GET: unsupported protocol scheme \"\""
```

Since `http.batch()` doesn't accept more than one argument, we should probably emit a warning with a more sensible message (or maybe even throw an error) when users pass us more...

**Comment by vanshaj** [comment]
Hello @na-- 

I have started working on this issue and was able to find the fix. If no one else is working on it , can you please assign this issue to me. I will resolve it. 

Regards
Vanshaj Dhar

**Comment by vanshaj** [comment]
Hello @na-- 

I would also wanted to add one point that there are some unit tests that contains the same scenario as yours but contains invalid urls, need to update those test scenarios also.
kindly update me on the same

Regards
Vanshaj

**Comment by na--** [comment]
> there are some unit tests that contains the same scenario as yours but contains invalid urls

can you share a link to that code?

**Comment by vanshaj** [comment]
Hello @na-- 
Sorry I didn't look at the tests properly, the tests doesnot contain the same scenarios . All the tests have only one array of items not multiple arrays. 

Can you allow me to work on the fix and I will add the unit test for the same. Along with validation for previous tests also.

Regards
Vanshaj
