### ISSUE TITLE
Add TLS keylogger support

### ISSUE THREAD

**Issue by MStoykov** [grafana/k6#1385]
## Feature Description
Currently if you are using https you have only `--http-debug=full` to see what the request/response are ... this is not terrible, but given that it has issues and that with big or binary response/request it is nearly unusable, I would argue that it is better if users can use wireshark(or other tools with similar capabilities).

Luckily for some time now (go1.8) golang has support to dump the tls keys it uses in a [format](https://developer.mozilla.org/en-US/docs/Mozilla/Projects/NSS/Key_Log_Format) that wireshark [understands](https://jimshaver.net/2015/02/11/decrypting-tls-browser-traffic-with-wireshark-the-easy-way/).

So I propose we add a flag to enable logging those keys to a file using the [tls.KeyLogger](https://golang.org/pkg/crypto/tls/#example_Config_keyLogWriter)

A [repo with a basic implementation and explanation](https://github.com/joneskoo/http2-keylog)

**Comment by jayjayswal** [comment]
is this still open? Can i work on this?

**Comment by MStoykov** [comment]
The whole k6 team is working on getting a very big pr by number 1007 (not linking it as it already is linked from thousands of places) to be merged - so we aren't working on anything else up until then.

You can do it, it is somewhat likely though that we won't merge it very fast :( and we might not be able to give you much feedback in the next month or two, but other than that, this shouldn't be that hard (famous last words :D). 

So go for it if you want or need it ;).

You will need to do something like we do for [InsecureSkipTLSVerify](https://github.com/loadimpact/k6/blob/8d1a038d79c06237158fff2dcdc7cf6a3715ccf3/js/runner.go#L163) but make certain that it isn't settable from inside the script `options`, as that will be a requirement for us to merge it :D

**Comment by jayjayswal** [comment]
```
Environment variable: K6_LOG_TLS_KEY
CLI Flag: --log-tls-key 
```
Is this naming convention okay?
Also what I understood from the last two-line, the "LogTLSKey" option won't be available in exported script options(.js file). Correct? If yes, will it be settable from the config.json file?

**Comment by MStoykov** [comment]
Well, we would certainly prefer it not to be, as it will need to be disabled in the cloud either way. 

I personally think this falls under the "this is only for debugging and will be terrible for normal use" category. This definitely will be faster than `--http-debug` but still probably far from cheap and IMO will generate A LOT of data in a normal run - so it being configurable through the script or config file(which is the same) seems like a bad idea either way.

**Comment by jayjayswal** [comment]
I found two approaches to this problem.
**Approach 1:**
We can just add `json:"-"` tag to `LogTLSKey`. As Script and Config file are using `json.Unmarshal`, Field will be ignored while building object.
```
LogTLSKey null.Bool `json:"-" envconfig:"K6_LOG_TLS_KEY"`
```

**Approach 2:**
We create functions to validate this manually.
- js/bundle.go (for parsing JS file)
```
//Function will be called inside NewBundle function before returning Bundle.
func ValidateJsScriptOptions(options *lib.Options) error{
	if options.LogTLSKey.Valid {
		return errors.New("Use command line argument or environment variable to set LogTLSKey.")
	}
	return nil
}
```
- cmd/config.go (for parsing Config file)
```
//Function will be called inside readDiskConfig function before returning Config.
func ValidateDiskConfig(config *Config) error{
	if config.Options.LogTLSKey.Valid {
		return errors.New("Use command line argument or environment variable to set LogTLSKey.")
	}
	if config.NoThresholds.Valid {
		return errors.New("Use command line argument or environment variable to set NoThresholds.")
	}
	return nil
}
```

IMO `Approach 2` is giving us more freedom for future development. e.g. if we want to use `json.Unmarshal` in the future and we don't want `LogTLSKey` to be ignored.
Also, it came to my attention that currently `NoThresholds` is settable by Config file but it should not as per current documentation. With `Approach 2` we can have more power over this kind of configuration. 
Let me know what do you think.

**Comment by jayjayswal** [comment]
Hey,
I have created a pull-request. golangci-lint check has been failed, I will look into it in a day or two.  As you guys must be busy with PR 1007, Review it whenever you get time.

**Comment by MStoykov** [comment]
Closing this in favor of a *previous* [issue](https://github.com/grafana/k6/issues/1043) I wrote that seems to have better description
