### ISSUE TITLE
Can K6 control the http terminator?

### ISSUE THREAD

**Issue by hgkiller** [grafana/k6#1393]
I want to very slowly feed the http request body to the server, and control the http request body,
 How I implemented it with K6?

**Comment by imiric** [comment]
This feature won't be implemented in the current HTTP API, but is planned as part of the [new API](https://github.com/grafana/k6/pull/2971). See the Sockets section.

This is also currently possible with the [xk6-tcp extension](https://github.com/NAlexandrov/xk6-tcp).
