### ISSUE TITLE
Run gofumports on the whole codebase

### ISSUE THREAD

**Issue by na--** [grafana/k6#1447]
When we don't have a ton of open PRs that will conflict, we can make a simple (though big) PR that will clean up minor code issues with gofumpt / gofumports (https://github.com/mvdan/gofumpt)

**Comment by codebien** [comment]
Closing as we already run `gofumpt` and lint using it https://github.com/grafana/k6/blob/6e2c8e80b35eec0a06197490f7962e4d309d0abb/.golangci.yml#L90
