### ISSUE TITLE
k6 path resolution doesn't work from CWD when running from stdin

### ISSUE THREAD

**Issue by na--** [grafana/k6#1462]
## Environment
- k6 version: 0.26.2
- OS and version: Linux (though this probably happens on other OSes as well)

## Expected Behavior
If I have the following as `test.js`:
```js
export var test = 123;
```

and if I have this as `script.js`:
```js
import { test } from "./test.js"

export default function (data) {
    console.log(test);
}
```
And both of these files are in the same folder, I should be able to execute them both by running `k6 run ./script.js` and `k6 run - <./script.js`, and get `123` printed either way.

## Actual Behavior

Instead, only the first command works. The second gives the following error:
```
GoError: The moduleSpecifier "file:///test.js" couldn't be found on local disk. Make sure that you've specified the right path to the file. If you're running k6 using the Docker image make sure you have mounted the local directory (-v /local/path/:/inside/docker/path) containing your script and modules so that they're accessible by k6 from inside of the container, see https://docs.k6.io/v1.0/docs/modules#section-using-local-modules-with-docker. 
```

For some reason, it's looking at the import file in the root folder.

**Comment by trathborne** [comment]
Neither work for me! Had to specify full paths in my test script.

**Comment by ecmyilmz** [comment]
I had the same issue but a little bit different, I had forgotten  lastfix ".js", I mean I imported 
import { test } from "./test", Maybe you can try to delete ".js"

**Comment by MStoykov** [comment]
@ecmyilmz this seems like #475 and as written there it's very unlikely that k6 will start adding `.js` to the end of module identifiers just in case that works. It seems that even node (finally) decided to [drop this for ESM modules](https://nodejs.org/api/esm.html#resolution-algorithm)

**Comment by IttiS46** [comment]
> Neither work for me! Had to specify full paths in my test script.

I have the same issue on mac os Big Sur 11.5.2

**Comment by JapuDCret** [comment]
> I had the same issue but a little bit different, I had forgotten lastfix ".js", I mean I imported import { test } from "./test", Maybe you can try to delete ".js"

Thank you! I had to change
```js
import { config } from '../environment';
```
to
```js
import { config } from '../environment.js';
```
