### ISSUE TITLE
Fix json benchmarks in http package

### ISSUE THREAD

**Issue by mstoykov** [grafana/k6#1505]
see 4e4d5d8 for reference. We just need to set context (with runtime set) for those responses.

**Comment by mstoykov** [comment]
This benchmark was removed in 3bcdabbf so if we want we should readd it

**Comment by codebien** [comment]
At this point, I'm for closing it. If we find a specific issue then I expect we will add directly there. Otherwise, I think the realistic way is that we will add one when the new API will be available.
