### ISSUE TITLE
Progress rendering artifacts in terminal on Mac

### ISSUE THREAD

**Issue by robingustafsson** [grafana/k6#1557]
On Mac there're some progress rendering artifacts when resizing the terminal window:

![k6-mac-progress-rendering-issue](https://user-images.githubusercontent.com/1792533/87529487-5ceed380-c68f-11ea-9f8a-4aaa8518a88c.gif)

## Environment
- k6 version: v0.27.0 (built from `master` on release day)
- OS and version: macOS Catalina (10.15.2) using [iTerm2](https://www.iterm2.com/)

**Comment by MStoykov** [comment]
Can this be retested given that there have been some fixes around the posgresbars?

**Comment by olegbespalov** [comment]
After an internal discussion, the k6-core team decided to close the issue as it is unlikely to be a common case.
