### ISSUE TITLE
Results output to Azure Monitor and LogAnalytics workspace

### ISSUE THREAD

**Issue by rupeshtech** [grafana/k6#1621]
We are using k6 for load testing our Apis and looking for a PaaS solution to send the output.

## Feature Description

Azure Monitor and(or) Log Analytics Workspace are prefered logging solutions for all kinds of metrics in Azure.
It would be great if we can send the metrics output to Azure Monitor and(or) Log Analytics Workspace

**Comment by MrBasset** [comment]
I'd love to see this feature too, for now though we are using this project to push a k6 JSON log into LAWs. https://github.com/yangl900/log2oms.

The problem we have is that it lags behind the actual tests in pushing the data, so we have to be careful to not kill our test harness before ingestion has completed.

**Comment by olegbespalov** [comment]
After an internal discussion, the k6-core team decided to close this issue. The output of the Azure Monitor could be implemented via xk6-extension; any contributions are welcome.
