### ISSUE TITLE
Huge VU numbers in ramping-vus result in a panic

### ISSUE THREAD

**Issue by na--** [grafana/k6#1693]
The following example:
```js
export let options = {
  stages: [
    {
      target: 40000000000000,
      duration: "1m",
    },
  ],
};

export default function () {
}
```
And some smaller numbers than that will result in a `fatal error: runtime: out of memory`. We should add some validation in here: https://github.com/loadimpact/k6/blob/bf826ba614ded605c93302d04464ab0252c63a6b/lib/executor/ramping_vus.go#L99-L106

That checks if the total number of VU up and down shifts exceeds some ridiculous number, say 100 million or something like that, and treat it as a config error.

**Comment by codebien** [comment]
This is not fully completed, we just did a minor UX improvement. https://github.com/grafana/k6/issues/1499 is a better approach to fix the issue here.
