### ISSUE TITLE
Rotate PRs assignment

### ISSUE THREAD

**Issue by MStoykov** [grafana/k6#1729]
It will be better to automate PRs reviewing.
Mostly there being someone assigned automatically as with:
- https://github.com/kentaro-m/auto-assign
- https://www.pullapprove.com/

**Comment by imiric** [comment]
We might want to consider using an OWNERS file for this, similar to [Kubernetes](https://github.com/kubernetes/community/blob/master/contributors/guide/owners.md) and apparently [GitHub's CODEOWNERS file](https://help.github.com/articles/about-codeowners/) too, which appears to be supported by that auto-assign project.

It's a bit smarter than just rotating assignments, but maybe we don't need the complexity.

**Comment by na--** [comment]
Probably a bit too early, but good to know for the future. I imagine that it would be especially useful when we have a lot more JS modules though, especially after we adopt several xk6 modules.

**Comment by na--** [comment]
We already implemented this in https://github.com/grafana/k6/pull/2175 :sweat_smile: 
https://github.com/grafana/k6/blob/703fd5723f51f5fb7e24e87361f920870d2e3564/.github/workflows/pr-auto-assign.yml#L11
