### ISSUE TITLE
Display any extensions bundled by xk6 in the pre-execution output

### ISSUE THREAD

**Issue by simskij** [grafana/k6#1741]
## Feature Description
With the introduction of xk6, it is likely that we'll start to get support questions or bug reports where users are running bespoke versions of k6. From a "k6 core" point of view, the course of action would/should likely be to ask the user to try again with an official build.

That aside, if we ever want to support any extension, or make life easier for extension developers, we need some way to tell by execution logs how to replicate their builds.

## Suggested Solution
Add a new row in the pre-execution output of k6 cli. This would only be visible when k6 detects something in the 'k6/x' namespace, and should then list extensions and their versions. Mockup below:

```
          /\      |‾‾| /‾‾/   /‾‾/   
     /\  /  \     |  |/  /   /  /    
    /  \/    \    |     (   /   ‾‾\  
   /          \   |  |\  \ |  (‾)  | 
  / __________ \  |__| \__\ \_____/ .io
  execution: local
     script: test.js
 extensions: github.com/dgzlopes/k6-extension-notifications
             github.com/dgzlopes/k6-extension-zmq
     output: -
```

With versions displayed:
```
          /\      |‾‾| /‾‾/   /‾‾/   
     /\  /  \     |  |/  /   /  /    
    /  \/    \    |     (   /   ‾‾\  
   /          \   |  |\  \ |  (‾)  | 
  / __________ \  |__| \__\ \_____/ .io
  execution: local
     script: test.js
 extensions: github.com/dgzlopes/k6-extension-notifications@v0.2.0
             github.com/dgzlopes/k6-extension-zmq@v0.0.0-20180725130230-947c36da315
     output: -
```

Given that we've been discussing other kinds of extensions than js extensions in the future, we might also need some way to detect those. One way of doing this would be to add a tripwire to `modules.Register` instead. Personally, I'd argue that we can leave that as a future improvement and focus on the js case for now.

**Comment by na--** [comment]
We might also investigate a way to display the included extensions and their version in the output of `k6 version`, so we have a one-stop command we can ask users to perform, which will give us all the information we want (k6 version, Go version, OS, extensions).

**Comment by imiric** [comment]
Hey, can we prioritize this for an upcoming cycle?

Support for outputting the included extensions and their version in `k6 version` specifically would be helpful when working on extension issues reported by users, since currently it outputs something like `k6 v0.34.1 ((devel), go1.17.2, darwin/amd64)`. See https://github.com/grafana/xk6-browser/issues/111#issue-1052714990.

We should probably define a new `Version()` method extensions must implement.

**Comment by na--** [comment]
Yeah, it's probably high time we do this... The `Version()` method should be optional though, if it's not implemented, we can just display the extension import path or output identifier :man_shrugging: Though I wonder if we even need `Version()`, maybe this is enough? https://pkg.go.dev/runtime/debug#BuildInfo
