### ISSUE TITLE
When iterations per second is less than 1, it floors to 0 in the progress output

### ISSUE THREAD

**Issue by simskij** [grafana/k6#1753]
If you set up a scenario where the executors runs less than one iteration per second, the value is floored to zero while in progress. However, it reports the correct amount in the end-of-test summary.

## Environment
- MacOS Big Sur
- k6 v0.29.0

## Expected Behavior

```
checkEveryFiveSeconds   [=========>----------------------------] 0/1 VUs  0m17.1s/1m0s  0.20 iters/s
```

or

```
checkEveryFiveSeconds   [=========>----------------------------] 0/1 VUs  0m17.1s/1m0s  >0 iters/s
```

Given end-of-test summary

```
  data_received........: 0 B 0 B/s
  data_sent............: 0 B 0 B/s
  iteration_duration...: avg=154.19µs min=83.97µs med=151.48µs max=282.84µs p(90)=205.18µs p(95)=244.01µs
  iterations...........: 8   0.205413/s
  vus..................: 1   min=1 max=1
  vus_max..............: 1   min=1 max=1
```

## Actual Behavior

```
checkEveryFiveSeconds   [=========>----------------------------] 0/1 VUs  0m17.1s/1m0s  0 iters/s
```

## Steps to Reproduce the Problem
Minimal repro:

```js
export let options = {
  scenarios: {
    checkEveryFiveSeconds: {
      executor: 'constant-arrival-rate',
      rate: 1,
      timeUnit: '5s',
      duration: '1m',
      preAllocatedVUs: 1,
    },
  },
};

export default function () {
  console.log(new Date());
}
```

**Comment by DarkAEther** [comment]
Greetings @simskij! If this issue is open to be worked on, I'd like to have a go at it.

**Comment by asettouf** [comment]
@DarkAEther Are you handling it? Otherwise I will take a shot at it

**Comment by DarkAEther** [comment]
> @DarkAEther Are you handling it? Otherwise I will take a shot at it 

Hey there! I'd love to handle it. I was just waiting for the maintainers to give me a thumbs up to proceed.

**Comment by na--** [comment]
Ah, sorry, both of you have the official :+1: to work on it, but I guess because @DarkAEther staked it first, @asettouf can you do the PR review? :sweat_smile:  And sorry, I guess I didn't respond to @DarkAEther initially because he addressed @simskij, and then later I completely forgot to follow up... :disappointed:

**Comment by DarkAEther** [comment]
> Ah, sorry, both of you have the official  to work on it, but I guess because @DarkAEther staked it first, @asettouf can you do the PR review?  And sorry, I guess I didn't respond to @DarkAEther initially because he addressed @simskij, and then later I completely forgot to follow up...

No worries! Thank you! I'll start working on it.

**Comment by asettouf** [comment]
@na-- Yeah no problem I can review the PR.

**Comment by simskij** [comment]
> > Ah, sorry, both of you have the official  to work on it, but I guess because @DarkAEther staked it first, @asettouf can you do the PR review?  And sorry, I guess I didn't respond to @DarkAEther initially because he addressed @simskij, and then later I completely forgot to follow up...
> 
> 
> 
> No worries! Thank you! I'll start working on it.

Sorry for the late reply! I'm not on the maintainer team of this project, @DarkAEther. 😅

You'll get better and faster replies by pinging @na--, @MStoykov or @imiric.

In the extremely unlikely case you don't get a reply though, feel free to ping me and I'll remind them! 😇

**Comment by na--** [comment]
@chtnnh, sorry for the late response :disappointed: sure, feel free to make a PR

**Comment by m3hm3t** [comment]
I have created a PR for the issue.

https://github.com/grafana/k6/pull/2282

**Comment by na--** [comment]
This was closed by https://github.com/grafana/k6/pull/2282, right?
