### ISSUE TITLE
DNS TTL not Expiring

### ISSUE THREAD

**Issue by Salamandastron1** [grafana/k6#1850]
When running the k6 tool with 
```js
export let options = {
    dns: {
      ttl: '0',
      select: 'roundRobin',
      policy: 'any'
    },
 ```

The TTL value of '0' is not honored until after the first transaction expires at 30 seconds.

<img width="1092" alt="Screen Shot 2021-02-09 at 12 13 32 PM" src="https://user-images.githubusercontent.com/40044553/107402696-477d4300-6ad2-11eb-8c4f-5c4dcb5cf4f6.png">

## Environment

- k6 version:
     - v0.30.0
- OS and version:
     - linux 5.0.0

## Expected Behavior

The expected behavior is that the DNS TTL session should be reset on every call.

## Actual Behavior

The initial TTL call caches the first IP returned and didn't expire until after 30 seconds. Then k6 starts behaving normally.

## Steps to Reproduce the Problem

1. Create a k6 script with the options object set to the below value
2.
```js
  export let options = {
    dns: {
      ttl: '0',
      select: 'roundRobin',
      policy: 'any'
    },
    vus: 10,
    duration: '30s',
  }
```
3. Be sure to run this against this an Active-Active setup. This will properly show in metrics where only one site will receive the initial run of traffic.

**Comment by imiric** [comment]
Hi, thanks for reporting this.

Are you using HTTP keep-alive? [As mentioned in the documentation](https://k6.io/docs/using-k6/options#dns) k6 will keep a connection open if keep-alive is in use, so the only way to force any DNS resolver strategy is to disable it with the [`noConnectionReuse` option](https://k6.io/docs/using-k6/options#no-connection-reuse).

Can you give that a try and let us know if the issue persists?

**Comment by MStoykov** [comment]
This has been awaiting response from @Salamandastron1 for over a year. I would like to close it unless the user confirms that this isn't due to `keep-alive` connections
