### ISSUE TITLE
Improve UX of native Go errors

### ISSUE THREAD

**Issue by na--** [grafana/k6#2049]
This error: https://github.com/k6io/k6/blob/da5eebc638d9917cedfe98e232a7eed4cb69a157/js/modules/k6/k6.go#L40-L41
https://github.com/k6io/k6/blob/da5eebc638d9917cedfe98e232a7eed4cb69a157/js/modules/k6/k6.go#L70-L74

And others like it, when returned, produce a stacktrace that might be very confusing to users. Before https://github.com/k6io/k6/pull/1971 and https://github.com/k6io/k6/pull/2046, it used to be something like this:

```
ERRO[0000] engine error                                  hint="error while initializing VU #5: 'GoError: Using group() in the init context is not supported\n\tat go.k6.io/k6/js/common.Bind.func1 (native)\n\tat file:///path/to/script.js:28:19(59)\n'"
```

After them, it will be something like this:
```
ERRO[0000] GoError: Using group() in the init context is not supported
	at go.k6.io/k6/js/common.Bind.func1 (native)
	at file:///path/to/script.js:28:19(59)  hint="error while initializing VU #2 (script exception)"
```

But in both cases, `GoError` and `at go.k6.io/k6/js/common.Bind.func1 (native)` are probably quite confusing to a lot of k6 users. They feature implementation details (like the fact that k6 is written in Go :sweat_smile:) that don't help in the issue diagnosis at all.

https://github.com/k6io/k6/issues/1802 might get rid of the extra stacktrace line, but we might have to do some text trimming in `js.scriptException` if we want to get rid of `GoError`, since I think that's something that goja attaches?

**Comment by na--** [comment]
@MStoykov reminded me that @imiric had actually opened a PR that partially solved this issue, https://github.com/k6io/k6/pull/1775 :sweat_smile: We should probably dust up that PR and merge it (or something similar) in the next k6 release...

**Comment by na--** [comment]
Moved the milestone of the PR to v0.33.0, since it's easy to rebase and port and seems to completely solve the `GoError` part of the issue! :tada: I'd still leave this issue open for the `at go.k6.io/k6/js/common.Bind.func1 (native)` part.

**Comment by olegbespalov** [comment]
Closing since it's no longer relevant:

```
ERRO[0000] GoError: Using group() in the init context is not supported
        at go.k6.io/k6/js/modules/k6.(*K6).Group-fm (native)
        at file:///path/to/script.js:4:6(36)  hint="script exception"
```
