### ISSUE TITLE
Use Semgrep for static analysis in CI

### ISSUE THREAD

**Issue by imiric** [grafana/k6#2065]
Recently we added a CodeQL workflow (#1961), which is great, but the included checks don't seem very useful. More rules can surely be added, but from a quick glance they don't seem very easy to write: https://github.com/github/codeql-go/blob/main/ql/src/InconsistentCode/LengthComparisonOffByOne.ql

In comparison, [Semgrep](https://semgrep.dev/) is a similar tool which doesn't have many built-in Go rules, but it does have a lot of [user-contributed rules](https://github.com/dgryski/semgrep-go) which on the surface seem easier to write: https://github.com/dgryski/semgrep-go/blob/master/wrongerrcall.yml It is YAML though, so hopefully not too frustrating... :sweat_smile:

We could use both for a while, and CodeQL seems to have better GitHub integration, but ultimately we should settle on one.

**Comment by na--** [comment]
I doubt I'll forget, but I particularly want to add a check for error handling like this:
```go
if suberr := something(); err != nil {
    return suberr
}
```

**Comment by joanlopez** [comment]
After an internal discussion with the team, we've decided to close this as it's too open ended and nothing has been worked on so far. If at some point we find this might deserve the effort, we may re-open it.

Thanks! 🙇🏻
