### ISSUE TITLE
Document limitation on Go JS bridge when returning only a single error type

### ISSUE THREAD

**Issue by cretz** [grafana/k6#2080]
## Feature Description

Today at https://github.com/k6io/k6/blob/cc0361ca4a5443e5b90d22b4c0e62a9f15c9757d/js/common/bridge.go#L151 you must have more than one return value to propagate Go errors. This surprised my developing a side-effect-only function that just returned a single error. I now return `(struct{}, error)` to have my Go error seen as a real error and not just a single value return.

## Suggested Solution

Assuming this is by intention, should document this somewhere. Currently `k6 Extensions` in the docs links to https://k6.io/blog/extending-k6-with-xk6/ which states:

> If err is not nil, it will be thrown with the appropriate message in the JS script.

Though it's understandable that a high-level blog post won't have this detail. Unsure where to document it, just thought I'd point out the surprise. I suppose a single-error-only-return func test has value at https://github.com/k6io/k6/blob/master/js/common/bridge_test.go to affirm behavior.

**Comment by MStoykov** [comment]
Given that common.Bind is probably going to be replaced as it has other issues described in #1802 and that goja by default *does* work with just a single returned value of `error`, I don't think documenting this is a good idea.

You can and I would encourage you to read #1802 and the proposed solutions, all the WIP PRs are very much a WIP and are mostly to illustrate the ideas and are neither final nor full. Likely the final version will be something in between all of them.

**Comment by mstoykov** [comment]
I am closing this as https://github.com/dop251/goja/commit/ea66e911853df63de1b259bfbbe090fccdb9ece9 basically fixes this particular issue and will be released with v0.41.0 (already updated on master)
