### ISSUE TITLE
K6_STATSD_ENABLE_TAGS set to true only works when --out is set to datadog instead of statsd 

### ISSUE THREAD

**Issue by filfreire** [grafana/k6#2096]
## Environment

- k6 version: `k6 v0.32.0 (2021-05-12T15:30:06+0000/5e42319, go1.16.4, linux/amd64)` and `k6 v0.32.0 ((devel), go1.16.3, darwin/amd64)`
- OS and version: macOS Catalina (and Docker 20.10.7)
- Docker version and image, if applicable: Docker 20.10.7, image used is `[v0.32.0](https://hub.docker.com/layers/loadimpact/k6/0.32.0/images/sha256-9aa4e5c11b198780d027e74bac5833d33f60ab7afd62ef7a087ccee0e6af9570?context=explore)`

## Expected Behavior
If I run multiple runs of k6, for each defining `--out statsd --tag test_run_id=<some_id>` and setting the variable `K6_STATSD_ENABLE_TAGS=true` I expect to be able to filter by multiple `test_run_id` on the [datadog default k6 integration dashboard](https://docs.datadoghq.com/integrations/k6/).

## Actual Behavior
I only see metrics pushed with the assigned `test_run_id` if I change the `--out` flag value from `statsd` to `datadog` (which supposedly will become deprecated by version `v0.34.0`) and keep `K6_STATSD_ENABLE_TAGS=true`.

Screenshot with `--out statsd` and `K6_STATSD_ENABLE_TAGS=true`:
<img width="617" alt="out_statsd" src="https://user-images.githubusercontent.com/11976836/125613280-78258ca3-14a4-4f9d-b6bf-3d0a46917678.png">
Screenshot with `--out datadog` and `K6_STATSD_ENABLE_TAGS=true`:
<img width="693" alt="out_datadog" src="https://user-images.githubusercontent.com/11976836/125613283-6a2258e7-82b5-4774-8fd6-1f4b35705ece.png">

## Steps to Reproduce the Problem

1. Spin up a [Datadog Agent](https://k6.io/docs/results-visualization/datadog/#run-the-datadog-agent)
2. Run a dummy k6 (v0.32.0) scenario with `datadog` flag: 
```
K6_STATSD_ENABLE_TAGS=true k6 run --out datadog --tag test_run_id=1 example.js
```
3. Run a dummy k6 (v0.32.0) scenario with `statsd` flag: 
```
K6_STATSD_ENABLE_TAGS=true k6 run --out statsd --tag test_run_id=2 example.js
```
4. Check on your datadog account the [default k6 integration dashboard](https://docs.datadoghq.com/integrations/k6/), you should only be able to filter `test_run_id` by `*` or by `1`, and the data from `test_run_id=2` will be obscured/not filterable by `2`.

**Comment by filfreire** [comment]
For version `v0.33.0` neither `--out statsd` or `--out datadog` seem to be working when it comes to push `test_run_id`, following same steps above.

**Comment by MStoykov** [comment]
Hi @filfreire,

I just tested this and it works perfectly fine for me including :
1. both v0.32.0 and v0.33.0 show tags if you just dump the packages in the same format (not that k6 supports another format to begin with) ([code of the server](https://gist.github.com/MStoykov/284b0637c2d8e994d7580fad798ca509))
2. it does send it to datadog and I can filter based on the `test_run_id` more or less following the linked documentation.

https://user-images.githubusercontent.com/312246/125617162-b7338ce0-3c7d-41e1-b906-653a0c5d8330.mp4

The video clearly shows that some metrics appear with the `test_run_id` ... I did notice that datadog sometimes need a refresh to notice new tags or at least I was having trouble while recording :shrug: but it definitely did show and did work as long as I wasn't moving around the UI all that much, which seems like a datadog issue not a k6 one.

I do expect it's something with the way you are running it. Can you paste the specific commands you are running and how it's setup if you want us to help you further.

**Comment by filfreire** [comment]
This is the command that I trigger `k6` inside a k6-based docker image (`from loadimpact/k6:0.33.0`) (never mind the names of the env variables):

With `--out datadog`:
```
k6 run src/example.js --vus 2 --iterations 2 \
-e "foo1=bar" \
-e "foo2=bar" \
-e "foo3=bar" \
-e "foo4=bar" \
-e "foo5=" \
-e "K6_STATSD_ENABLE_TAGS=true" \
-e "foo6=" \
-e "foo7=" \
-e "foo8=bar" \
--out json=reports/temp.json --summary-export=reports/summary_temp.json --out datadog --tag test_run_id=10568a53-5a15-4021-a70f-4004dfbbc4ac
```


With `--out statsd`
```
k6 run src/example.js --vus 2 --iterations 2 \
-e "foo1=bar" \
-e "foo2=bar" \
-e "foo3=bar" \
-e "foo4=bar" \
-e "foo5=" \
-e "K6_STATSD_ENABLE_TAGS=true" \
-e "foo6=" \
-e "foo7=" \
-e "foo8=bar" \
--out json=reports/temp.json --summary-export=reports/summary_temp.json --out statsd --tag test_run_id=6c020c58-0bee-45d3-b701-6664902e5a7a
```

This is what I see on datadog if I filter by `test_run_id`:

![Screenshot 2021-07-14 at 17 03 20](https://user-images.githubusercontent.com/11976836/125646256-51bbf5ff-850c-493a-b279-384e29560cbf.png)

**Comment by MStoykov** [comment]
`-e "K6_STATSD_ENABLE_TAGS=true" ` 

tells k6 to provide the script with an env var with the provided name and value but does not actually "think" of it as one. So you can't do it with this flag you need to actually set an env variable in order to k6 to take it into account

**Comment by filfreire** [comment]
Indeed this was the case, thank you @MStoykov! 

Changing the direct k6 run call to `K6_STATSD_ENABLE_TAGS=true k6 run ...` indeed did the trick for direct k6 call.

For docker way of running, this also seemed to solve the issue:
```
docker run \
      --network=host \
      -e "K6_STATSD_ENABLE_TAGS=true" \
      --rm -i loadimpact/k6:0.33.0 \
      run - <src/example.js --vus $VUS --iterations $ITERATIONS \
      -e "foo1=bar" \
      -e "foo2=bar" \
      # ... some other args
      --out statsd --tag test_run_id=123
```

From my side we can close the issue. Again, thank you @MStoykov 🙇
