### ISSUE TITLE
What do the K6 default output metrics mean?

### ISSUE THREAD

**Issue by wmsken** [grafana/k6#2098]
Hi, Sir, 
Hope you are doing well.

I am a little confused about the K6 default output metrics, which is like below:
iteration_duration.........: avg=9.27s    min=1.55s med=4.94s    max=1m6s   p(90)=17.53s   p(95)=32.78s

What exactly does metric "med", "p(90)" and "p(95)" mean?
Whether the "med" means "p(50)" or not?

Could you please help me about this?

Thanks
Ken

**Comment by imiric** [comment]
Hi Ken, I'm doing very well, hope you are too. :smiley:

Your question is better suited for the [community forum](https://community.k6.io/), but I'll answer you here.

What you're seeing there is part of the [end-of-test summary](https://k6.io/docs/results-visualization/end-of-test-summary/). Specifically, `iteration_duration` is a [Trend metric](https://k6.io/docs/javascript-api/k6-metrics/trend) that tracks the time it took to execute the `default` function in your script. Using it we can calculate some statistics for the entire test such as the [percentile](https://en.wikipedia.org/wiki/Percentile) values like "med" (median), which is the equivalent to `p(50)`. So in your case 50% of iterations took 4.94s or less.

You can read more about this in the [Metrics guide](https://k6.io/docs/using-k6/metrics/).

Have fun!

**Comment by wmsken** [comment]
Thank you so much imiric, it really helps me a lot!
