### ISSUE TITLE
http.expectedStatuses doesn't work with POST requests

### ISSUE THREAD

**Issue by koynoyno** [grafana/k6#2120]
```
import http from 'k6/http';

export default function () {
  http.post("http://test.k6.io/login.php", { responseCallback: http.expectedStatuses(403) })
}
```
![image](https://user-images.githubusercontent.com/46102189/130406076-5aa4ba2c-c899-4b48-8b7c-83978ea4853a.png)

## Environment
- k6 version: k6 v0.32.0 (2021-05-12T15:30:26+0000/5e42319, go1.16.3, linux/amd64)
- OS and version: Manjaro Linux

## Expected Behavior
`http_req_failed` 0%

## Actual Behavior
`http_req_failed` 100%

**Comment by MStoykov** [comment]
The second argument to `http.post` is the body not the [params](https://k6.io/docs/javascript-api/k6-http/params/) it works with 
```
http.post("http://test.k6.io/login.php", null, { responseCallback: http.expectedStatuses(403) })
```
