### ISSUE TITLE
K6_STATSD_TAG_BLOCKLIST not functional

### ISSUE THREAD

**Issue by guongle-ssense** [grafana/k6#2129]
## Environment

- k6 version: 0.33.0
- OS and version: EKS 1.24
- Docker version and image, if applicable: loadimpact/k6:0.33.0

## Expected Behavior

in command line should exclude comma separated tags listed in `K6_STATSD_TAG_BLOCKLIST` from appearing in custom metrics of Datadog (or StatsD)

## Actual Behavior

Command line with fully loaded comma list of tags STILL appears as part of metrics summary within Datadog

## Steps to Reproduce the Problem

1. load job in EKS with benchmark script executing 
```bash
K6_STATSD_ENABLE_TAGS=true K6_STATSD_TAG_BLOCKLIST="name,url,tls,tls_version,proto,method,image,instance-type,k8s.io/role/node,k8s.io/cluster-autoscaler/enabled,k8s.io/cluster-autoscaler/node-template/label/node-role.kubernetes.io,k8s.io/cluster-autoscaler/node-template/taint/dedicated:benchmark,k8s.io/cluster-autoscaler/qa.k8s.ssense.com,kernel,aws" k6 run --compatibility-mode=base -e RPS=5 -e PRE_ALLOCATED_VUS=4 -e VUS=10 -e DURATION=60 --summary-trend-stats "min,avg,med,max,p(25),p(75),p(95),p(99)" --out statsd scripts/test.bundle.js
```
2. wait for execution (no errors)
3. check metrics summary - `k6.vus` tag key still present despite `K6_STATSD_TAG_BLOCKLIST` used

**Comment by MStoykov** [comment]
Just checked again locally by just dumping what is being sent and with the provided BLOCKLIST at least for me `k6.vus` does not have any tags, while http_reqs still keeps stuff such as `status`

```
k6.vus:1.000000|g
k6.vus_max:1.000000|g
k6.http_reqs:1|c|#expected_response:false,scenario:default,error_code:1504,status:504
k6.http_req_duration:10116.042227|ms|#error_code:1504,expected_response:false,scenario:default,status:504
k6.http_req_blocked:413.500953|ms|#error_code:1504,scenario:default,status:504,expected_response:false
k6.http_req_connecting:113.835326|ms|#error_code:1504,expected_response:false,status:504,scenario:default
k6.http_req_tls_handshaking:263.297315|ms|#scenario:default,status:504,expected_response:false,error_code:1504
k6.http_req_sending:0.352701|ms|#scenario:default,expected_response:false,status:504,error_code:1504
k6.http_req_waiting:10115.537411|ms|#error_code:1504,expected_response:false,scenario:default,status:504
k6.http_req_receiving:0.152115|ms|#error_code:1504,expected_response:false,scenario:default,status:504
k6.http_req_failed:1|c|#expected_response:false,status:504,error_code:1504,scenario:default
k6.check.status is 200.fail:1|c|#scenario:default,check:status is 200
k6.check.protocol is HTTP/2.pass:1|c|#scenario:default,check:protocol is HTTP/2
k6.data_sent:658|c|#scenario:default
k6.data_received:5762|c|#scenario:default
k6.iteration_duration:10529.794403|ms|#scenario:default
k6.iterations:1|c|#scenario:default
```

are you certain you are not looking at older data or that just the interface shows you tags for older samples of the same metric even if the period doesn't actually has it ? Can you try with a clean server to confirm it?

**Comment by guongle-ssense** [comment]
hi @MStoykov 
the dogstatsd agent lives as a daemon set, each run of the pod that has K6 as a pod runs fresh. Im also certain it is not stale data as when i run the pod i leave it as least for several hours and i use the 1hr portion to check for data from Datadog's metric summary. 

please see screenshot

![Screen Shot 2021-09-09 at 8 51 33 AM](https://user-images.githubusercontent.com/48691526/132689127-8daf1b51-1eea-4065-8ef1-1ada8bbd2539.png)

**Comment by MStoykov** [comment]
@guongle-ssense are those tags configured in k6 or in datadog? as it seems to me that those get added by the datadog agent

**Comment by guongle-ssense** [comment]
> @guongle-ssense are those tags configured in k6 or in datadog? as it seems to me that those get added by the datadog agent

i am checking if they are not configured by DD for cluster. If it is, then it wouldn't be a bug and DD addson those tags per metrics sent from the pod despite within the pod it self blocking those tags - right?

**Comment by MStoykov** [comment]
k6 just sends metrics to the datadog-agent and then it does aggregation and it can send additional tags. For me locally the only tag that it sends is `host` but ... looking at all the tags you have and the command line you are showing, none of those are actually things k6 will send on its own, so unless it tells it to do it, I will expect they come from the agent. But the agent is the one who is adding them so, you will need to removed them there (or not add them I guess)

**Comment by guongle-ssense** [comment]
As a daemon set - it adds much metadata on top of the forwarded data, with a small relay dogstatsd as a service deployed and let the k6 container talk to it.
It went from 70 distinct metrics with 54 tag values (and 32 tag keys) down to 32 distinct with 41 values (28 tag keys)
It IS smaller in value but i still see tag keys that are not supposed to be sent. the Dogstatsd deployed only has the DD_API_KEY set and nothing else.

don't suppose there is a way to also block on the statsd service also.

**Comment by MStoykov** [comment]
From what I can gather all of this get added by datadog agent after k6 sent stats. This likely is also included on any and all other metrics for these pods such as memory and cpu usage and is totally not connected to k6, so I am closing this. 

You probably want to go talk to datadog's support on how to lower the number of tags the agent attaches.  Here are some [docs](https://docs.datadoghq.com/agent/kubernetes/tag/?tab=containerizedagent#out-of-the-box-tags) showing big parts of the tags you have listed.

**Comment by guongle-ssense** [comment]
will do @MStoykov thanks for the assist
