### ISSUE TITLE
Fix snake_case to camelCase in argline for csv and influxdb outputs

### ISSUE THREAD

**Issue by MStoykov** [grafana/k6#2137]
Throughout k6 we use camelCase for JSON options and CAPS_SNAKE_CASE for env variables. The few places where there are argline options such as `k6 run -o csv=file_name=something.csv` we sometimes use snake_case as in the CSV output and one option in the influxdb one, but sometimes we use camelCase as in the loki logs and the rest of the influxdb options :(. 

Given that there really isn't a good case for one of the options to be camelCase and the other snake_case we should make them the same. For backwards compatible reasons we should still parse the snake_case variant and warn the user through a log message, at least for ... some versions.

So I propose that @codebien fixes the influxdb one in #2110  and there to be a separate PR for the CSV output.

**Comment by Sampriti-Mitra** [comment]
@MStoykov can I take this

**Comment by MStoykov** [comment]
Go for it @Sampriti-Mitra ! Just FYI if you want to do it as part of hacktoberfest, you might need to wait another 3 days or so, although maybe it's fine, I haven't really read the fine print :man_shrugging:

**Comment by JosephWoodward** [comment]
Hi @Sampriti-Mitra, are you working on this? If not I have a pull request [here](https://github.com/grafana/k6/pull/2150) that I'd like to propose.

**Comment by Sampriti-Mitra** [comment]
@MStoykov sure, will be working on this!

**Comment by Sampriti-Mitra** [comment]
@JosephWoodward think your PR looks good, @MStoykov  can you assign this to @JosephWoodward instead
