### ISSUE TITLE
Error - InfluxDB: Couldn't write stats

### ISSUE THREAD

**Issue by perrinj3** [grafana/k6#2145]
When is run a K6 test which outputs to the Opentelemetry InfluxDb receiver I get continuous errors 
InfluxDB: Couldn't write stats error = "failed to append to the batch"
However the data appears to be flowing through the OpenTelemetry Collector ok as I can see all the output from the test in Splunk ( the Otel Collector is exporting to Splunk HEC)
I don't get this error if I point K6 to an instance of InfluxDB. 
What does this error mean please?

**Comment by MStoykov** [comment]
Hi @perrinj3, can you provide the exact log output of k6 and the exact tools you are using and setup. 

From the looks of it, this is an error something else returns that k6 just logs so likely you will need to report it to the other tool, but let's first see what the setup is.

**Comment by perrinj3** [comment]
Hi @MStoykov 
As I mentioned I don't get any errors if I output to an Influxdb instance. However I do get the errors when outputting to an OpenTelemetry collector configured with an InfluxDB receiver. I suspect the error is coming from Optel but not sure as the data is flowing through the collector ok and successfully exporting to Splunk. 

My K6 command line is
~~~
k6 run --out influxdb=http://0.0.0.0:8087  --config config.json script3.js
~~
 
0.0.0.0:8087 is an Opentelemetry receiver 
~~~
receivers:
  influxdb:
    endpoint: "0.0.0.0:8087"
~~~
script.js 
~~~
import http from 'k6/http';
import { sleep } from 'k6';
import { Rate } from 'k6/metrics';



export default function () {
  
  let res1 = http.get('http://appau401mel5058:8080', {
    tags: { type: 'API Call' ,group: 'Login', name: 'Login to Jenkins',scenario: 'Smoke Test1'},
  });
  let res2 = http.get('http://appau401mel5058:8888/sources/2/chronograf/data-explorer', {
    tags: { type: 'API Call' ,group: 'Chronograf', name: 'Login to Chronograf',scenario: 'Smoke Test1'},
  });

  let responses = http.batch([
    [
      'GET',
      'http://appau401mel5058:8080',
      null,
      { tags: { type: 'staticContent',group: 'Home Page' ,scenario: 'Smoke Test1'} },
    ],
    [
      'GET',
      'http://appau401mel5058:8080',
      null,
      { tags: { type: 'staticContent',group: 'Home Page',scenario: 'Smoke Test1' } },
    ],
  ]);

  sleep(10);
}
~~~

config.json is
~~~
{
    "stages": [
		{
		"duration": "10s",
		"target": 5
		},
		{
		"duration": "3600s",
		"target": 10
		},
		{
		"duration": "10s",
		"target": 0
		}
			],
  "thresholds": {
    "http_req_duration": ["avg<1", "p(95)<1"],
	"http_req_duration{type:Jenkins}": ["p(95)<1"],
	"http_req_duration{type:Chronograf}": ["p(95)<1"], 
    "http_req_duration{type:staticContent}": ["p(95)<1"],
	"http_reqs": ["count>100880"]
  },
  "tags": {
  "TribeName":"CAT","BuildNumber":"160","SquadName":"Join","Environment":"LOCAL","TestName":"Smoke Test1","Application":"APP1"},
  
  "noConnectionReuse": true,
  "userAgent": "MyK6UserAgentString/1.0"
} 
~~~

log output is as follows
~~~
          /\      |‾‾| /‾‾/   /‾‾/   
     /\  /  \     |  |/  /   /  /    
    /  \/    \    |     (   /   ‾‾\  
   /          \   |  |\  \ |  (‾)  | 
  / __________ \  |__| \__\ \_____/ .io

  execution: local
     script: script3.js
     output: influxdb=http://0.0.0.0:8087 (http://0.0.0.0:8087)

  scenarios: (100.00%) 1 scenario, 10 max VUs, 1h0m50s max duration (incl. graceful stop):
           * default: Up to 10 looping VUs for 1h0m20s over 3 stages (gracefulRampDown: 30s, gracefulStop: 30s)


running (0h00m01.0s), 01/10 VUs, 0 complete and 0 interrupted iterations
default   [   0% ] 01/10 VUs  0h00m00.9s/1h00m20.0s
{"error":"","level":"error","msg":"InfluxDB: Couldn't write stats","time":"2021-09-30T11:56:26+10:00"}

running (0h00m02.0s), 01/10 VUs, 0 complete and 0 interrupted iterations
default   [   0% ] 01/10 VUs  0h00m01.9s/1h00m20.0s
{"error":"","level":"error","msg":"InfluxDB: Couldn't write stats","time":"2021-09-30T11:56:27+10:00"}

running (0h00m03.0s), 02/10 VUs, 0 complete and 0 interrupted iterations
default   [   0% ] 02/10 VUs  0h00m02.9s/1h00m20.0s
{"error":"","level":"error","msg":"InfluxDB: Couldn't write stats","time":"2021-09-30T11:56:28+10:00"}

running (0h00m04.0s), 02/10 VUs, 0 complete and 0 interrupted iterations
default   [   0% ] 02/10 VUs  0h00m03.9s/1h00m20.0s
{"error":"","level":"error","msg":"InfluxDB: Couldn't write stats","time":"2021-09-30T11:56:29+10:00"}

running (0h00m05.0s), 02/10 VUs, 0 complete and 0 interrupted iterations
default   [   0% ] 02/10 VUs  0h00m04.9s/1h00m20.0s
{"error":"","level":"error","msg":"InfluxDB: Couldn't write stats","time":"2021-09-30T11:56:30+10:00"}

running (0h00m06.0s), 03/10 VUs, 0 complete and 0 interrupted iterations
default   [   0% ] 03/10 VUs  0h00m05.9s/1h00m20.0s
{"error":"","level":"error","msg":"InfluxDB: Couldn't write stats","time":"2021-09-30T11:56:31+10:00"}

running (0h00m07.0s), 03/10 VUs, 0 complete and 0 interrupted iterations
default   [   0% ] 03/10 VUs  0h00m06.9s/1h00m20.0s
{"error":"","level":"error","msg":"InfluxDB: Couldn't write stats","time":"2021-09-30T11:56:32+10:00"}

running (0h00m08.0s), 04/10 VUs, 0 complete and 0 interrupted iterations
default   [   0% ] 04/10 VUs  0h00m07.9s/1h00m20.0s
{"error":"","level":"error","msg":"InfluxDB: Couldn't write stats","time":"2021-09-30T11:56:33+10:00"}

running (0h00m09.0s), 04/10 VUs, 0 complete and 0 interrupted iterations
default   [   0% ] 04/10 VUs  0h00m08.9s/1h00m20.0s
{"error":"","level":"error","msg":"InfluxDB: Couldn't write stats","time":"2021-09-30T11:56:34+10:00"}

running (0h00m10.0s), 04/10 VUs, 0 complete and 0 interrupted iterations
default   [   0% ] 04/10 VUs  0h00m09.9s/1h00m20.0s
{"error":"","level":"error","msg":"InfluxDB: Couldn't write stats","time":"2021-09-30T11:56:35+10:00"}

running (0h00m11.0s), 05/10 VUs, 1 complete and 0 interrupted iterations
default   [   0% ] 05/10 VUs  0h00m10.9s/1h00m20.0s
{"error":"","level":"error","msg":"InfluxDB: Couldn't write stats","time":"2021-09-30T11:56:36+10:00"}

running (0h00m12.0s), 05/10 VUs, 1 complete and 0 interrupted iterations
default   [   0% ] 05/10 VUs  0h00m11.9s/1h00m20.0s
{"error":"","level":"error","msg":"InfluxDB: Couldn't write stats","time":"2021-09-30T11:56:37+10:00"}

running (0h00m13.0s), 05/10 VUs, 2 complete and 0 interrupted iterations
default   [   0% ] 05/10 VUs  0h00m12.9s/1h00m20.0s
{"error":"","level":"error","msg":"InfluxDB: Couldn't write stats","time":"2021-09-30T11:56:38+10:00"}

running (0h00m14.0s), 05/10 VUs, 2 complete and 0 interrupted iterations
default   [   0% ] 05/10 VUs  0h00m13.9s/1h00m20.0s
{"error":"","level":"error","msg":"InfluxDB: Couldn't write stats","time":"2021-09-30T11:56:39+10:00"}

running (0h00m15.0s), 05/10 VUs, 2 complete and 0 interrupted iterations
default   [   0% ] 05/10 VUs  0h00m14.9s/1h00m20.0s
{"error":"","level":"error","msg":"InfluxDB: Couldn't write stats","time":"2021-09-30T11:56:40+10:00"}

running (0h00m16.0s), 05/10 VUs, 3 complete and 0 interrupted iterations
default   [   0% ] 05/10 VUs  0h00m15.9s/1h00m20.0s
{"error":"","level":"error","msg":"InfluxDB: Couldn't write stats","time":"2021-09-30T11:56:41+10:00"}

running (0h00m17.0s), 05/10 VUs, 3 complete and 0 interrupted iterations
default   [   0% ] 05/10 VUs  0h00m16.9s/1h00m20.0s
{"error":"","level":"error","msg":"InfluxDB: Couldn't write stats","time":"2021-09-30T11:56:42+10:00"}

running (0h00m18.0s), 05/10 VUs, 4 complete and 0 interrupted iterations
default   [   0% ] 05/10 VUs  0h00m17.9s/1h00m20.0s
{"error":"","level":"error","msg":"InfluxDB: Couldn't write stats","time":"2021-09-30T11:56:43+10:00"}

running (0h00m19.0s), 05/10 VUs, 4 complete and 0 interrupted iterations
default   [   1% ] 05/10 VUs  0h00m18.9s/1h00m20.0s
{"error":"","level":"error","msg":"InfluxDB: Couldn't write stats","time":"2021-09-30T11:56:44+10:00"}

running (0h00m20.0s), 05/10 VUs, 4 complete and 0 interrupted iterations
default   [   1% ] 05/10 VUs  0h00m19.9s/1h00m20.0s
{"error":"","level":"error","msg":"InfluxDB: Couldn't write stats","time":"2021-09-30T11:56:45+10:00"}
~~~

**Comment by MStoykov** [comment]
Hm ... maybe @codebien will know more :man_shrugging:

**Comment by codebien** [comment]
The `influxdbreceiver` is returning `202 Accepted` as a successful status code. Instead, the Go client library [is following](https://github.com/grafana/k6/blob/e0d8d9336f77fd8b4dc50c840ac7aedfac43574b/vendor/github.com/influxdata/influxdb1-client/v2/client.go#L413) the API reference [defined](https://docs.influxdata.com/influxdb/v1.8/tools/api/#summary-table-1) from InfluxDB, expecting a `204 No Content` (or eventually a `200 OK`). I opened an issue https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/5582.

This should be the reason why you're getting the error only on the k6 side and the data are flowing correctly through the collector and Splunk.
