### ISSUE TITLE
prometheus

### ISSUE THREAD

**Issue by sysmat** [grafana/k6#2146]
## Environment
- k6 version: v0.33.0
- OS and version: Win 10
- Docker version and image, if applicable:

## Expected Behavior
- is Prometheus Remote Write only possible to work on cload
- in config k6 with fake prometheus end point should return some error message that can not publish metrics 
- reference doc: https://k6.io/docs/cloud/integrations/prometheus-remote-write/

## Actual Behavior
- some error message can't publish or this option is not supported

## Steps to Reproduce the Problem
```js
export let options = {
  stages: [
    { duration: '30s', target: 20 },
    { duration: '1m30s', target: 10 },
    { duration: '20s', target: 0 }
  ],
  thresholds: {
    http_req_duration: ['p(99)<1500'], // 99% of requests must complete below 1.5s
    'status is 200': ['p(99)<1500'], // 99% of requests must complete below 1.5s
  },
  ext: {
    loadimpact: {
      apm: [
        {
          provider: "prometheus",
          remoteWriteURL: "http://monitoring.example.com:9090/api/v1/write", // this is fake endpoint
          // optional parameters
          credentials: {
            token: "aaaaabbbb"
          },
          includeDefaultMetrics: true,
          metrics: ["http_req_sending", "my_rate", "my_gauge"],
          includeTestRunId: false,
          resampleRate: 3
        },
      ]
    },
  }
};

```

**Comment by yorugac** [comment]
Hi @sysmat 

Yes, that documentation you linked describes k6 Cloud-only solution. With a fake endpoint, the test should run as usual but with an error about metrics export. Is that what happens with your test?

FYI, we have k6 OSS solutions for remote write here:

- [xk6-output-prometheus-remote](https://github.com/grafana/xk6-output-prometheus-remote) is an output extension for remote write interface
- [xk6-client-prometheus-remote](https://github.com/grafana/xk6-client-prometheus-remote) is a client extension for Prometheus remote write

But they are WIP and are not as stable at the moment.

**Comment by na--** [comment]
I'll close this, since we already have other issues that track prometheus support by k6: https://github.com/grafana/k6/issues/1761, https://github.com/grafana/k6/issues/343, https://github.com/grafana/k6/issues/858
