### ISSUE TITLE
Replace packaging tools that use Glide

### ISSUE THREAD

**Issue by inancgumus** [grafana/k6#2154]
There are some packages that we depend like: [go-bin-deb](https://github.com/mh-cbon/go-bin-deb) and [go-bin-rpm](https://github.com/mh-cbon/go-bin-rpm).

These packages have been stale for the last five years or so, and they use [Glide](https://github.com/bumptech/glide). We want to keep them as they are (_with the same dependencies in their Glide files_) but with proper Go modules.

This issue is an open discussion to see what we will plan to do next.

This issue (#2153) is also related to this one, and this [comment](https://github.com/grafana/k6/pull/2153#issuecomment-933243979).

----

*Some ideas:*

* We want to keep the same dependencies of these packages.
* But, technically glide is needed for the rpm/deb things and they use glide.
* We can drop them while replacing them.
* We can fork them and move to go modules (with the same version that are in glide) and vendor everything at which point go install will hopefully build us the same binary or at least with the same dependencies as it does currently with glide.
* `go mod` respects `glide.yaml` files, so we can easily `go.mod` them. So, fork these packages, run `glide install`, commit the vendored files (or run `go mod init`) and push the result - we can then use `go install` on our own fork, safely knowing we're going to get the exact same versions we are currently getting (and which we know work)

**Comment by na--** [comment]
An alternative that @MStoykov mentioned is that we might want to use the vanilla `rpmbuild` and `dpkg` tools, instead of some Go project :man_shrugging: 

Also, this might affect what we choose: https://github.com/grafana/k6/issues/2136

**Comment by na--** [comment]
@codebien suggested we can use https://goreleaser.com/ (https://github.com/goreleaser/goreleaser)

At a cursory glance, we can at least use this sub-component of goreleaser to build our deb and rpm packages instead of the dead `go-bin-deb` and `go-bin-rpm` we currently use: https://github.com/goreleaser/nfpm
