### ISSUE TITLE
Terminal prompt ends up mid-output on auth error

### ISSUE THREAD

**Issue by sniku** [grafana/k6#2157]
When the k6-cloud token is invalid, k6 exits with the terminal prompt being mid-output.

![image (32)](https://user-images.githubusercontent.com/442646/135989723-72910abc-56a8-41e6-b3df-0a8f18edef54.png)

## Environment
- k6 version: `k6 v0.34.1 ((devel), go1.16.5, linux/amd64)`
- OS and version: `Linux work 5.10.0-8-amd64 #1 SMP Debian 5.10.46-4 (2021-08-03) x86_64 GNU/Linux`
- Shell: `bash`
- Term: `rxvt-unicode-256color`

## Expected Behavior
I expect the prompt to show after the k6 output. 

## Steps to Reproduce the Problem
1. Set a wrong cloud token
2. Run a cloud test

**Comment by olegbespalov** [comment]
I've checked in my term and mentioned `rxvt-unicode-256color`.

![Image](https://github.com/user-attachments/assets/65a530eb-be9f-4b15-b956-9bf7cf94d5fc)

It works as expected, so it probably was fixed by one of the refactorings.
