### ISSUE TITLE
New Github forms for issues

### ISSUE THREAD

**Issue by divshacker** [grafana/k6#2171]
## Feature Description

New Github forms for issues. 
https://github.blog/changelog/2021-06-23-issues-forms-beta-for-public-repositories/

## Suggested Solution (optional)

If one can provide what things are necessary for new issue forms then I can make one.

**Comment by divshacker** [comment]
Hey I would like to work on this for hacktober fest.

**Comment by na--** [comment]
Sure, @divshacker, this seems like a nice idea.
