### ISSUE TITLE
exec.vu.tags: Tags not overwritten consistently by System Tags

### ISSUE THREAD

**Issue by MStoykov** [grafana/k6#2221]
### Feature Description

after https://github.com/grafana/k6/pull/2172 there will be a way for script code to add tags to be emitted for *all* metrics emitted by the vu, this, unfortunately, has some tags that it just won't work with such as :
- `url` for [HTTP requests](https://github.com/grafana/k6/blob/98152ba6480f8e3d820554040b94b1347466d270/lib/netext/httpext/transport.go#L116-L118) 
- `check` for [checks](https://github.com/grafana/k6/blob/98152ba6480f8e3d820554040b94b1347466d270/js/modules/k6/k6.go#L156-L158) 

Both of those as can be seen just overwrite the tag as long as it's enabled in system tags. 

This isn't true for all tags, for example `name` actually [gets checked](https://github.com/grafana/k6/blob/98152ba6480f8e3d820554040b94b1347466d270/lib/netext/httpext/request.go#L189-L200)  ([twice](https://github.com/grafana/k6/blob/master/lib/netext/httpext/transport.go#L111-L113)) and won't be overwritten. 

I haven't checked anything else but I would expect there will be more of this :). 

### Suggested Solution (optional)

This is in practice the current behaviour for `tags` set in the [Params](https://k6.io/docs/javascript-api/k6-http/params/) AFAIK, so I guess it isn't really all that big of a problem.

Still, it might be good to it be known and to think about whether we want to change that.

**Comment by codebien** [comment]
I checked all the system tags that we currently have and all of them are relying only on the `Has` method. The unique exception is `name` as reported in the description. I don't think we plan to change that logic around `name` so I'm closing this.
