### ISSUE TITLE
Add support for local files to `--log-output`

### ISSUE THREAD

**Issue by na--** [grafana/k6#2249]
### Feature Description

[`--log-output`](https://k6.io/docs/using-k6/options/#log-output) currently supports only `none` (disabled), `stdout`, `stderr` and [`loki`](https://grafana.com/oss/loki/). 

Supporting local files should be simple and will be beneficial for debugging, or in CI environments, and it can also be used by log-forwarding tools to ship the logs pretty much anywhere. Combined with the [`logformat` ](https://k6.io/docs/using-k6/options/#logformat) option, this feature should be pretty versatile.

Somewhat connected issue: https://github.com/grafana/k6/issues/1939

**Comment by naoyukis** [comment]
Can I try this issue?

**Comment by na--** [comment]
Sure!

**Comment by codebien** [comment]
@na-- Do we expect to get some sort of rotation or is it something we would encourage to delegate to other tools?

**Comment by na--** [comment]
We should probably start without that, we can always add it later if there's demand for it.

**Comment by oleiade** [comment]
Some context is probably missing on my side, but what's the delta between redirecting stdout/stderr to a file from the command-line, and having k6 do it for us instead?  As in, something along the lines of `k6 run --log-output stderr samples/http_batch.js &> output.log`.
