### ISSUE TITLE
What about VUs = 0 ?

### ISSUE THREAD

**Issue by msaf1980** [grafana/k6#2276]
I need to testing several scenarios: for example short and long duration queries

Number of VU's configured via env vars.

I need to disable of some scenario execution. But if set to vus to 0, get error `the number of VUs should be more than 0`

What about to allow of vus = 0 with simple disable scenario execution ?

```
let USERS_1H = getenv.getInt(`${__ENV.USERS_1H}`, 10);
let USERS_1D = getenv.getInt(`${__ENV.USERS_1D}`, 0);

export const options = {
    scenarios: {
        render_1h_offset_0: {
            executor: 'constant-vus',
            exec: 'api_render',
            vus: USERS_1H,
            duration: DURATION,
            gracefulStop: '10s',
            env: { GROUP: 'render_1h' },
        },
        render_1h_offset_7d: {
            executor: 'constant-vus',
            exec: 'api_render',
            vus: USERS_1D,
            duration: DURATION,
            gracefulStop: '10s',
            env: { GROUP: 'render_1d' },
        },
}
```

**Comment by MStoykov** [comment]
@msaf1980, thanks for the issue and PR 

Unfortunately, IMO the check here is correct - the idea behind it is that it's unlikely that what you wanted is to make a configuration for a `constant-vus` and have it have *no* vus (negative ones are even a bigger red flag). Disabling a scenario in this way seems like an interesting approach but I would argue that ultimately it will be more confusing for anybody reading the script. I would propose that you just add or remove parts of the scenario depending on the configuration you provide:

```javascript
let USERS_1H = getenv.getInt(`${__ENV.USERS_1H}`, 10);
let USERS_1D = getenv.getInt(`${__ENV.USERS_1D}`, 0);
let scenarios = {};
if (USERS_1H > 0) {
    scenarios["render_1h_offset_0"] = {
            executor: 'constant-vus',
            exec: 'api_render',
            vus: USERS_1H,
            duration: DURATION,
            gracefulStop: '10s',
            env: { GROUP: 'render_1h' },
      }
}
if (USERS_1D > 0) {
     scenarios["render_1h_offset_7d"] = {
            executor: 'constant-vus',
            exec: 'api_render',
            vus: USERS_1D,
            duration: DURATION,
            gracefulStop: '10s',
            env: { GROUP: 'render_1d' },
        }
}
export const options = {
    scenarios: scenarios
}
``` 
(the code was written right here, so expect a type somewhere - it's for illustrative purposes ;) ).

Reading this code now at least I can clearly see that if USERS_1D is set to 0 I will *not*  get the second scenario for example. 

Hope this helps.

I am going to close this, but a another team member with a different opinion is welcome to come and reopen it if they have differing opinion.
