### ISSUE TITLE
Regeneration of grpc sample is not documented

### ISSUE THREAD

**Issue by MStoykov** [grafana/k6#2297]
Currently, if someone changes ./samples/grpc_server and needs to regenerate the protobuf files, they need to figure out the command they need to use and how to get all of it's parts. 

I suggest we at least add a `//go:generate` comment and some additional info on top of it so that `go generate .` in that directory will work.

The command AFAIK is:
> protoc --go_out=./ route_guide.proto
from inside the folder and I got protoc from https://github.com/protocolbuffers/protobuf/releases and ran `go install google.golang.org/protobuf/cmd/protoc-gen-go@latest`. 

It probably also be good if the CI checks that this was done ... although given the above requirements(two external tools) it might be a bit much :shrug:

**Comment by codebien** [comment]
This was covered by #2295 so I'm closing it
