### ISSUE TITLE
Unclear error message when using the `-o` option, while not logged in

### ISSUE THREAD

**Issue by oleiade** [grafana/k6#2394]
### Feature Description

I was setting up a new machine to interact with the k6 cloud today. I hadn't logged in yet. When I ran the command `k6 run simple.js -o cloud`, the command ran, and failed, with a somewhat unhelpful error message: `An unexpected error occured`. My immediate assumption is, as I haven't logged in yet via the `k6 login cloud --token <YOUR_K6_CLOUD_API_TOKEN>`, the commands fails as the cloud's can't identify my request?

```bash
❯ k6 run simple.js -o cloud

          /\      |‾‾| /‾‾/   /‾‾/
     /\  /  \     |  |/  /   /  /
    /  \/    \    |     (   /   ‾‾\
   /          \   |  |\  \ |  (‾)  |
  / __________ \  |__| \__\ \_____/ .io

ERRO[0002] (500) An unexpected error occurred

Init      [--------------------------------------] Starting outputs
default   [--------------------------------------]

Init      [--------------------------------------] Starting outputs
default   [--------------------------------------]
```

### Suggested Solution (optional)

As a user, I would expect the error message to guide me towards resolution. My immediate idea to help with that would be to make the error message more explicit if possible (that might not be possible for security reasons?). Moreover, to have the error message provide instructions to help solve the issue. Still assuming the error is linked to failed authentication, something along the lines of: “the k6 cloud was unable to authenticate your request. Have you logged in using the `k6 login cloud` command already?”.
Another improvement could be to have the command immediately exit with an error exit code on failure. I was a bit confused that the command's output was still active, and I didn't initially see the error message…

**Comment by mstoykov** [comment]
Tried this and am currently getting 

> ERRO[0001] (403/E4) Missing Authorization token or trying to run an anonymous test    

I went back to version 0.30.0 and same message so it might've been fixed in the k6 cloud. 

Shall we close @oleiade or can you still reproduce it.

**Comment by oleiade** [comment]
Just gave it another try, and the error message is much better indeed!

![Screenshot 2023-10-12 at 14 51 04](https://github.com/grafana/k6/assets/690867/985c56ea-e383-46b6-9c33-0582c84cf5de)

Closing 🙇🏻
