### ISSUE TITLE
Issue with HEAD requests in 0.36.0?

### ISSUE THREAD

**Issue by grantyoung** [grafana/k6#2401]
### Brief summary

After upgrading to `0.36.0` we noticed that in one of our tests it started failing with no successful requests. Uniquely this was the only test that was sending HEAD requests (`http.head`).

Digging further we identified our nginx server was rejecting all requests vaguely with 400 errors. After switching back to `0.35.0` the issue was no longer happening suggesting this is an issue on the k6 side.

### k6 version

0.36.0

### OS

Ubuntu 18.04, Mac OS 12.2.1

### Steps to reproduce the problem

- Create a test sending HEAD requests, possibly against a standard nginx server
- Notice that they fail with 400 errors

### Expected behaviour

HEAD requests are successful

### Actual behaviour

HEAD requests are being rejected with 400 errors

**Comment by MStoykov** [comment]
Hi @grantyoung I think this as in v0.36.0 we did refactor this code and it seems that we made `http.head` take `body` as second argument as all other helpers except `http.get` :thinking: 

Can you confirm that adding a `null` body fixes this for you?

**Comment by na--** [comment]
Sorry @grantyoung, this seems to be a bug I introduced with https://github.com/grafana/k6/pull/2226 that the tests didn't catch as a regression :disappointed: We plan to release v0.37.0 in a couple of weeks and we'll fix it in there.

**Comment by grantyoung** [comment]
No problem at all @na--, thanks for the update.
