### ISSUE TITLE
Dependecies update after the `v0.37.0` release

### ISSUE THREAD

**Issue by olegbespalov** [grafana/k6#2445]
Based on the https://github.com/grafana/k6/blob/master/Dependencies.md

This issue collects the list of the dependencies that will be updated after the release:

```
modtools check --direct-only
Some dependencies are out-of-date. Please upgrade by running 'modtools update' or the following commands:

(no new version since the last release) go get github.com/PuerkitoBio/goquery@v1.8.0
(no new version since the last release) go get github.com/andybalholm/brotli@v1.0.4
(+) go get github.com/dop251/goja@v0.0.0-20220214123719-b09a6bfa842f
(no new version since the last release) go get github.com/fatih/color@v1.13.0
(Maybe update?) go get github.com/gorilla/websocket@v1.5.0
(Maybe update? Many fixes) go get github.com/jhump/protoreflect@v1.12.0
(Maybe update?) go get github.com/klauspost/compress@v1.15.1
(no new version since the last release) go get github.com/mattn/go-colorable@v0.1.12
(no new version since the last release) go get github.com/mattn/go-isatty@v0.0.14
(+) go get github.com/spf13/cobra@v1.4.0
(no new version since the last release) go get github.com/tidwall/gjson@v1.14.0
(+) go get golang.org/x/crypto@v0.0.0-20220315160706-3147a52a75dd
(+) go get golang.org/x/net@v0.0.0-20220225172249-27dd8689420f
(+) go get golang.org/x/term@v0.0.0-20210927222741-03fcf44c2211
(+) go get golang.org/x/time@v0.0.0-20220224211638-0e9765cccd65
(Maybe update?) go get google.golang.org/grpc@v1.45.0
```

- [x] Goja: https://github.com/grafana/k6/pull/2441
- [x] `golang/x/*`: https://github.com/grafana/k6/pull/2443
- [x] `github.com/spf13/cobra`: https://github.com/grafana/k6/pull/2446
- [x] Other dependencies part 1 https://github.com/grafana/k6/pull/2449
- [x] Other dependencies part 2 https://github.com/grafana/k6/pull/2452

**Comment by MStoykov** [comment]
@olegbespalov you can definitely update all the ones that I did skip the previous few times. Some of those are now 1year+ without updates so as long as they aren't huge it's probably good idea to just update them. 

This also means that we won't be reminded that we haven't and have to go look up if there is anything we want from them.
