### ISSUE TITLE
Support Any.proto for GRPC

### ISSUE THREAD

**Issue by CandiedCode** [grafana/k6#2447]
### Brief summary

For a GRPC service whose message type uses Any.proto.  K6 is unable to locate the protobuf to serialize to the given type.

Given a data object such as 
```javascript
{ context: 'test',
   payload: {
            "@type": "type.googleapis.com/test.Client",
            "client_id": 1234,
          },
}
```

k6 will throw an error:
`unable to serialise request object to protocol buffer: proto: (line 1:157): unable to resolve "type.googleapis.com/test.Client": "not found"`

### k6 version

k6 v0.36.0 ((devel), go1.17.6, darwin/amd64)

### OS

macOS Montery

### Steps to reproduce the problem

For a given grpc service such as 

```yaml
syntax = "proto3";

package test;

import "google/protobuf/any.proto";

service Publisher {
    rpc Publish (PublishRequest) returns (PublishResponse);
}

message PublishRequest {
    string context = 1;
    google.protobuf.Any payload = 3;
}
...
```
That references Any.proto, k6 is not able to serialize to the expected protobuf type, even if it's part of the client.load protobuf definitions.

```javascript
client.load(['event-schemas/protobufs', '../../protos'],
    'context.proto',
    'action.proto',
    'client.proto',  # example protobuf definitions from event-schema that we want to pack as Any.proto
    'relay.proto',  # part of the grpc service
    );
``` 
The protobuf descriptors seem to load correctly, but since they aren't directly related to a service descriptor I think they are filtered out [here](https://github.com/grafana/k6/blob/master/js/modules/k6/grpc/client.go#L179-L180) possibly and fails [here](https://github.com/grafana/k6/blob/master/js/modules/k6/grpc/client.go#L503-L509). 

### Expected behaviour

Any.proto is able to seralize to any proto passed into client.load.serialize

### Actual behaviour

Exception thrown

`unable to serialise request object to protocol buffer: proto: (line 1:157): unable to resolve "type.googleapis.com/test.Client": "not found"`

**Comment by jamie-macdonald** [comment]
has this been released? and what version is it in?

**Comment by na--** [comment]
Yes, this has been released in k6 v0.39.0, as the issue milestone suggests: https://github.com/grafana/k6/blob/master/release%20notes/v0.39.0.md#bug-fixes

If you think there is another bug, please open a new issue about it. And if you are having problems with using it, feel free to ask for advice in the community forum at https://community.k6.io/

**Comment by jamie-macdonald** [comment]
Thanks its working, after the usual amount of playing. yeah!

**Comment by amnbcw** [comment]
I am using k6 `v0.54.0 (commit/baba871c8a, go1.23.1, linux/amd64)`, and still running into this issue. :/

**Comment by inancgumus** [comment]
Hi @amnbcw, can you give us the steps to reproduce the issue?
