### ISSUE TITLE
Please join to us #standwithukraine

### ISSUE THREAD

**Issue by id-dan** [grafana/k6#2454]
Please support Ukraine, more infos here: https://github.com/vshymanskyy/StandWithUkraine

**Comment by id-dan** [comment]
Hi, @MStoykov 

Could you pls check it?

**Comment by ppcano** [comment]
Hi Roman,

we appreciate your intention and want to emphasize that Grafana Labs condemns the illegal attack on Ukraine.

As with other large-scale societal issues, Grafana Labs has donated to Ukranian relief efforts and offers a matching programme for Grafanistas who donate. As we believe that actions speak louder than words, you will not find big PR announcements around our donations and matching programmes. For the same reason, please understand that we prefer to close this issue without public action.
