### ISSUE TITLE
Redirects without location are broken due to current version of go

### ISSUE THREAD

**Issue by mstoykov** [grafana/k6#2474]
## Summary:
`Location` header isn't required for any redirect (`3xx`), this was previously not correctly supported in go for 301-303 statuses, for which it was a requirement. 

This has [been fixed](https://github.com/golang/go/commit/a41763539c7ad09a22720a517a28e6018ca4db0f) in the current gotip(possibly to be released in 1.19). 

K6 did previously have a test for this [that has been removed](https://github.com/grafana/k6/pull/2473).

But this is still broken on all currently released version of go (up to 1.18).

## Suggested fix:
Given that this is behavior from the stdlib fixing it seems impossible without forking it so - we are unlikely to fix it. We will just wait for go version with the fix to be released and use that. 

So this issue mostly exist to document the fact that currently k6 isn't compliant with the RFC and will likely be closed when a version of k6 is released with a go version that fixes it.

### Other "fixes:
As discussed in https://github.com/grafana/k6/pull/2472 we could keep the broken behavior for a time even with a version of go that fixes it. This has been mostly been abandoned as an idea, but is linked for reference.

**Comment by agilob** [comment]
When can we expect a new image with go 1.19? Just hit this nasty bug in our tests

**Comment by na--** [comment]
k6 v0.41.0, the next official release that will be published around the end of October will most likely use Go 1.19, unless we find some issue in the meantime. We will probably update the CI [test](https://github.com/grafana/k6/blob/master/.github/workflows/test.yml) and [build](https://github.com/grafana/k6/blob/master/.github/workflows/build.yml) files, and the [Dockerfile](https://github.com/grafana/k6/blob/master/Dockerfile) soon and once the PR is merged, you should be able to use the official `grafana/k6:master` Docker image even before v0.41.0 is released. If you want, feel free to submit a PR and we can merge it sooner.

**Comment by agilob** [comment]
```
❯ podman run --rm -i grafana/k6:master version
k6 v0.40.0 (2022-09-27T10:12:18+0000/v0.40.0-7-gb5bbf7e9, go1.18.6, linux/amd64)
```

sorry if I misunderstood, but `grafana/k6:master` still uses buggy go?

**Comment by agilob** [comment]
This bug is pretty wild, because locally our k6 0.40 was working correctly, both on linux and mac, but scripts started failing when running in a container. 3 people wasted a day together trying to find bug in our helm, dockerfile or handing of __ENV in k6 code...

**Comment by mstoykov** [comment]
@agilob how did you install k6 build with 1.19.1 locally? I am pretty sure we should have build everything with 1.18 instead of 1.19 :thinking:

**Comment by agilob** [comment]
On archlinux it will be compiled from source and use latest version of go https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=k6

on max installed using brew:

```
❯ k6 version
k6 v0.40.0 ((devel), go1.19.1, darwin/amd64)
```

**Comment by agilob** [comment]
https://formulae.brew.sh/formula/k6#default brew "depends on go 1.19.1"

**Comment by mstoykov** [comment]
I've opened #2699 for the brew recipe.

The arch aur package is not under our control but they should probably download the prebuild binary instead. As I have feeling requesting a particular go version in it will be a bit more involved then in brew, but I really don't know much about AUR :shrug:

**Comment by agilob** [comment]
>should probably download the prebuild binary instead

there is one that downloads bin, but it's out of date
