### ISSUE TITLE
Add a way to delete cookies from `CookieJar`

### ISSUE THREAD

**Issue by imiric** [grafana/k6#2476]
### Feature Description

Currently (`v0.37.0`) there's no way to delete a cookie from the `CookieJar`. Users can override a cookie by passing a local jar (`http.CookieJar`) or a `cookies` parameter per request, but there's no easy way of actually deleting a cookie from the `Cookie` header.

See [this forum post](https://community.k6.io/t/how-to-prevent-cookies-generation/3353) for the use case.

<hr>

Setting the cookie on the VU jar to `null` actually sends it as an empty string:

```javascript
import http from 'k6/http';

export default function () {
  http.get('https://httpbin.test.k6.io/cookies/set?one=1&two=2');
  const jar = http.cookieJar();  // get the VU specific jar
  jar.set('https://httpbin.test.k6.io/cookies', 'one', null);
  const res = http.get('https://httpbin.test.k6.io/cookies');
  console.log(JSON.stringify(res.json().cookies));
}
```

<details>
  <summary>Output</summary>

```
INFO[0001] Request:
GET /cookies HTTP/1.1
Host: httpbin.test.k6.io
User-Agent: k6/0.37.0 (https://k6.io/)
Cookie: one=; two=2
Accept-Encoding: gzip

INFO[0001] Response:
HTTP/1.1 200 OK
Content-Length: 54
Access-Control-Allow-Credentials: true
Access-Control-Allow-Origin: *
Connection: keep-alive
Content-Type: application/json
Date: Mon, 04 Apr 2022 13:55:47 GMT

{
  "cookies": {
    "one": "",
    "two": "2"
  }
}

INFO[0001] {"one":"","two":"2"}                          source=console
```
</details>

Similarly setting both the name and value to `null` (`jar.set('https://httpbin.test.k6.io/cookies', null, null)`) sends a new cookie with both empty values:

<details>
  <summary>Output</summary>

```
INFO[0001] Request:
GET /cookies HTTP/1.1
Host: httpbin.test.k6.io
User-Agent: k6/0.37.0 (https://k6.io/)
Cookie: one=1; two=2; =
Accept-Encoding: gzip

INFO[0001] Response:
HTTP/1.1 200 OK
Content-Length: 68
Access-Control-Allow-Credentials: true
Access-Control-Allow-Origin: *
Connection: keep-alive
Content-Type: application/json
Date: Mon, 04 Apr 2022 14:02:00 GMT

{
  "cookies": {
    "": "",
    "one": "1",
    "two": "2"
  }
}

INFO[0001] {"":"","one":"1","two":"2"}                   source=console
```
</details>

### Suggested Solution (optional)

Setting a cookie to `null` with `jar.set(url, 'cookie', null)` could be a way to delete a specific cookie. If the user wanted to send an empty string they could just set the value to `''` instead.

Similarly `jar.set(url, null, null)` could be used to delete _all_ cookies for that URL, or `jar.set(null, null, null)` to delete _all_ cookies in the jar.

A more intuitive approach suggested by @MStoykov would be to add another method, e.g. `CookieJar.delete`, to make this more explicit.

**Comment by stevenebutler** [comment]
While looking at this issue, I would sometimes find it useful to be able to clear the cookie jar completely, but was unable to find a way to do that.

My use case would be where I want each iteration to use the same vuser, but on error with the site, fail() out of the iteration, clear all cookies when the iteration fails and login again, possibly with a new user id.
```js
    http.cookieJar().clear()
```
