### ISSUE TITLE
Add TLS/SSL key logging for SSL debuggability support

### ISSUE THREAD

**Issue by kkriegkxs** [grafana/k6#2482]
### Feature Description

Add SSL decryption support for CAP e.g. Wireshark in the same fashion as Chrome & Firefox do:
* if env SSLKEYLOGFILE is set, output keys to it

### Suggested Solution (optional)

1. Extend tlsConfig to add KeyLogWriter (https://pkg.go.dev/crypto/tls#Config.KeyLogWriter) if a corresponding debug flag is set
2. Add required flags

### Already existing or connected issues / PRs (optional)

https://github.com/grafana/k6/pull/2481

**Comment by MStoykov** [comment]
There already is an issue with all of this info https://github.com/grafana/k6/issues/1043

**Comment by kkriegkxs** [comment]
👍 dint find it on a quick scan
