### ISSUE TITLE
K6 returns HTTP 413 for POST with payload size > 65536 bytes

### ISSUE THREAD

**Issue by matsaleh13** [grafana/k6#2489]
## Summary
My K6 load test fails with HTTP 413 ("Request Entity Too Large") when it sends a `POST` with payload > 65536 bytes in size.

The system under test (SUT) receives JSON "blobs" via `POST` and stores them in a DB. The size limit for stored data is ~1MB.

This restriction appears to be in K6, as the SUT doesn't even receive the request (nothing logged in access logs), no errors in the server at all.

## Other Info
This happens when running on both macOS and in the official K6 Docker container (macOS host machine).

I have no plans to run this load test in the k6 cloud, as I realize payload size limits might be appropriate there.

## Help Requested
Please advise whether this is a bug or a deliberate restriction.

If it's a restriction, please advise how I might be able to increase it, even if it means forking the code and hard coding a change, just for my particular use case.

If it's a bug, I'd love a suggestion on the general area of the code to look at for a fix. I'll be glad to submit a PR if I'm able to fix it.

Many thanks in advance.

### k6 version

k6 v0.37.0 ((devel), go1.17.8, darwin/amd64)

### OS

macOS 10.15.7 and alpine:3.15

### Docker version and image (if applicable)

Docker engine v20.10.12 / grafana/k6:0.37.0 (75fe50949474) 

### Code
```Javascript
import http from "k6/http";

export const options = {
  scenarios: {
    load_blobs: {
      executor: "shared-iterations",
      vus: 1,
      iterations: 1,
    },
  },
};

export default function (data) {
  const url = `http://localhost:57994/storage/v1/app/0000/blob/repro_413/user/1`;

  // CreateBlob
  const blob = {
    payload: {
      ttl: 0,
      value: "X".repeat(65505), // this plus the rest of the object = 65537
    },
  };

  const blobStr = JSON.stringify(blob);

  const res = http.post(url, blobStr, {
    headers: { "Content-Type": "application/json" },
  });

  console.info(
    `payload size: ${blobStr.length} res.status_text: ${res.status_text}`
  );

  if (res.status === 413) {
    // Request Entity Too Large error
    console.warn(
      `Load failed with status 413 for payload size: ${blobStr.length}`
    );
  }
}
```
### Execution
```bash
$ k6 run tests/minimal-413-repro.js

          /\      |‾‾| /‾‾/   /‾‾/
     /\  /  \     |  |/  /   /  /
    /  \/    \    |     (   /   ‾‾\
   /          \   |  |\  \ |  (‾)  |
  / __________ \  |__| \__\ \_____/ .io

  execution: local
     script: tests/minimal-413-repro.js
     output: -

  scenarios: (100.00%) 1 scenario, 1 max VUs, 10m30s max duration (incl. graceful stop):
           * load_blobs: 1 iterations shared among 1 VUs (maxDuration: 10m0s, gracefulStop: 30s)

INFO[0000] payload size: 65537 res.status_text: 413 Request Entity Too Large  source=console
WARN[0000] Load failed with status 413 for payload size: 65537  source=console

running (00m00.0s), 0/1 VUs, 1 complete and 0 interrupted iterations
load_blobs ✓ [======================================] 1 VUs  00m00.0s/10m0s  1/1 shared iters

     data_received..............: 60 B    6.0 kB/s
     data_sent..................: 66 kB   6.6 MB/s
     http_req_blocked...........: avg=1.77ms min=1.77ms med=1.77ms max=1.77ms p(90)=1.77ms p(95)=1.77ms
     http_req_connecting........: avg=272µs  min=272µs  med=272µs  max=272µs  p(90)=272µs  p(95)=272µs
     http_req_duration..........: avg=3.29ms min=3.29ms med=3.29ms max=3.29ms p(90)=3.29ms p(95)=3.29ms
     http_req_failed............: 100.00% ✓ 1          ✗ 0
     http_req_receiving.........: avg=417µs  min=417µs  med=417µs  max=417µs  p(90)=417µs  p(95)=417µs
     http_req_sending...........: avg=515µs  min=515µs  med=515µs  max=515µs  p(90)=515µs  p(95)=515µs
     http_req_tls_handshaking...: avg=0s     min=0s     med=0s     max=0s     p(90)=0s     p(95)=0s
     http_req_waiting...........: avg=2.36ms min=2.36ms med=2.36ms max=2.36ms p(90)=2.36ms p(95)=2.36ms
     http_reqs..................: 1       100.452034/s
     iteration_duration.........: avg=7.3ms  min=7.3ms  med=7.3ms  max=7.3ms  p(90)=7.3ms  p(95)=7.3ms
     iterations.................: 1       100.452034/s
```

### Expected behaviour

K6 `POST` request allows Content-Length up to 1MB, or allows user configuration of the maximum payload size.

### Actual behaviour

A `POST` request with a payload larger than 65536 bytes fails with HTTP 413 ("Request Entity Too Large") status without even sending the request to the SUT.

**Comment by na--** [comment]
This restriction is definitely not on the k6 side, k6 doesn't have any artificial restrictions on request sizes. The only potential limitation on the k6 side are some inefficiencies that cause it to use too much RAM when because it copies request bodies around (https://github.com/grafana/k6/issues/2311).

HTTP 413 is an error returned by the server, or by some (reverse-)proxy between you and the server. I tried your script but changed the URL to `https://httpbin.test.k6.io/anything` and that worked fine, I got a 200 response back.

**Comment by matsaleh13** [comment]
Thanks a lot for your reply and advice!

> This restriction is definitely not on the k6 side, k6 doesn't have any artificial restrictions on request sizes. 

I did think it was unlikely but when I didn't see the requests coming into the server, I wasn't sure where else to look. Everything is running on my dev box currently.

> The only potential limitation on the k6 side are some inefficiencies that cause it to use too much RAM because it copies request bodies around a few times (#2311), but if you hit those, you would get an OOM error, not HTTP 413.

Good to know, thanks.

> HTTP 413 is an error returned by the server, or by some (reverse-)proxy between you and the server. I tried your script but changed the URL to `https://httpbin.test.k6.io/anything` and that worked fine, I got a 200 response back.

Thanks very much for this. I guess I wasn't as creative as I could have been once I was unable to find any evidence that the requests were making it to the server.

The SUT is running in a docker-compose stack on the same machine as K6 (this is just for ad-hoc testing to get things working, not the "real" load test). I think a proxy is unlikely, but there must be *something* in front of the server interfering, with it. Or, maybe a middleware layer in front of the server request handling code, I guess.

Anyway, thanks for eliminating this possibility and giving me a reason to press on! Cheers!
