### ISSUE TITLE
js: options.scenarios return an empty object

### ISSUE THREAD

**Issue by codebien** [grafana/k6#2495]
### Brief summary

Using as an example the reported script, it prints an unexpected `{}` object using `>v0.37.0`. This change has been introduced by https://github.com/grafana/k6/pull/2392.

This is happening because the logic sets the `scenarios` property after the change from 2392.
https://github.com/grafana/k6/blob/737dfa7ced6e4f94dbb3d6f2c2837085e783ac09/js/bundle.go#L290-L294
Unfortunately, the `goja.Value.Export` doesn't work well for the `options.Scenarios`' Go type and it sets an empty object.

In `v0.36.0` and previous versions, the `scenarios` key wasn't set during the `js.Bundle.Instantiate` because the key used for it was the wrong `scenarios,omitempty` as mentioned in 2393.

Note: We could consider not fixing this bug mostly because the correct API to use for fetching the options should be the new `exec.test.options` and we would avoid users accessing options using the variable defined and exported from the script.

### k6 version

v0.37.0

### OS

Linux

### Steps to reproduce the problem

k6-v0.37.0 run script.js

### Expected behaviour

```javascript
console.log(JSON.stringify(options.scenarios)) // {}
---
INFO[0000] {"contacts":{"executor":"shared-iterations","iterations":1}}  source=console
``` 

### Actual behaviour

```javascript
import exec from 'k6/execution';

export const options = {
	scenarios: {
		contacts: {
			executor: 'shared-iterations',
			iterations: 1,
		},
	},
};

export default function() {
	console.log(JSON.stringify(options.scenarios))
}
---
INFO[0000] {}  source=console
```

**Comment by Mert-Z** [comment]
I believe due to this bug, the solution described in this question here: https://community.k6.io/t/multiple-scenarios-metrics-per-each/1314/2 stops working on k6 versions v0.37.0+

**Comment by codebien** [comment]
As we have right now the proper way to access `options` via `k6/execution.test.options` is not expected anymore to directly access the original `options` variable that doesn't contain the consolidated values.

```js
export default function() {
	console.log(exec.test.options.scenarios)
}
```

```js
INFO[0000] {"contacts":{"executor":"shared-iterations","startTime":null,"gracefulStop":null,"env":null,"exec":null,"tags":null,"vus":null,"iterations":1,"maxDuration":null}}  source=console
```
