### ISSUE TITLE
go.k6.io doesn't support specifying tag when installing xk6

### ISSUE THREAD

**Issue by jsravn** [grafana/k6#2514]
### Brief summary

The vanity domain doesn't seem to implement the meta tags that lets us pin specific versions.

```
go install go.k6.io/xk6/cmd/xk6@v0.37.0
go: go.k6.io/xk6/cmd/xk6@v0.37.0: unrecognized import path "go.k6.io/xk6/cmd/xk6": parse https://go.k6.io/xk6/cmd/xk6?go-get=1: no go-import meta tags ()
```

Main reason I was doing this is because https://github.com/grafana/k6/pull/2433 introduced breaking changes so our k6 plugin broke. We'd like to pin the version to mitigate that kind of breakage if possible.

### k6 version

0.38.0

### OS

Linux

### Steps to reproduce the problem

Try to install a specific version of xk6.

### Expected behaviour

It should work.

### Actual behaviour

It doesn't as the go-import meta tag is missing.

**Comment by na--** [comment]
xk6 doesn't have a `v0.37.0` version, it isn't using the same versioning scheme as k6. The latest xk6 version is [v0.6.1](https://github.com/grafana/xk6/releases/tag/v0.6.1).

So you can either install k6:
```sh
go install go.k6.io/k6@v0.37.0
```

Or go install a specific xk6 version:
```sh
go install go.k6.io/xk6/cmd/xk6@v0.6.1
```

_(though I suggest using `@latest` in both cases)_

Finally, if you want to build a custom version of k6 with some extensions bundled in, you can run:
```sh
xk6 build v0.37.0 --with <extension-module-path>
```
