### ISSUE TITLE
NPM version 0.0.0 as latest

### ISSUE THREAD

**Issue by tot-ra** [grafana/k6#2516]
### Feature Description

Hey. Any plans to update NPM when you release new version? its 0.0.0 there
https://www.npmjs.com/package/k6

**Comment by na--** [comment]
k6 currently cannot be installed from npm, it's not one of our supported [installation methods](https://k6.io/docs/getting-started/installation/), even unofficially.

That seems like an empty package created by the original k6 maintainer, probably to reserve the name, but I have no idea how it can be downloaded 23575 times per week when it doesn't do anything... :confused: We'll have to see if we still have access to that package, to update the description at the very least...

Though, if I recall correctly, npm supported binary non-JS packages :thinking:  So we might also see about actually adopting the package and using it as a distribution channel :man_shrugging: Thanks for reminding us that this actually existed, I had completely forgotten about it... :sweat_smile:

**Comment by rcoy-v** [comment]
The documentation uses the `k6` package in the modules bundler setup example: https://k6.io/docs/using-k6/modules/#setting-up-the-bundler. 

This is the description for the `k6` usage:
> A dummy package used to provide type-ahead in VSCode and similar

**Comment by imiric** [comment]
@MohamadKh75 Thanks for explaining.

The team has discussed this issue internally, and we've decided to not support NPM as a distribution channel. We understand it would be convenient to have k6 together with all other NPM dependencies in your project, but publishing to NPM would require a maintenance and support effort from our side that we can't currently afford.

We suggest installing k6 using one of the [supported installation methods](https://k6.io/docs/get-started/installation/), and pinning the version in a Dockerfile or script, depending on how you manage your environment. Apologies for any inconvenience.
