### ISSUE TITLE
Rate thresholds with no values now will show NaN in the summary

### ISSUE THREAD

**Issue by mstoykov** [grafana/k6#2540]
### Brief summary

After v0.38.0 you will always get thresholds evaluated and see them in the final summary even if no samples were emitted.

This though now means that for Rate it will be NaN instead of 0 which can probably be a bit confusing. 

### k6 version

v0.38.0

### OS

all

### Steps to reproduce the problem

Run a script such as 
```javascript
export let options = {
  thresholds: {
    'http_req_failed': ['rate<0.1'],
  },
}
export default () => { }
```

### Expected behaviour

```
     data_received..................: 0 B  0 B/s
     data_sent......................: 0 B  0 B/s
     http_req_duration..............: avg=0s  min=0s  med=0s  max=0s  p(90)=0s  p(95)=0s
     ✓ { expected_response:true }...: avg=0s  min=0s  med=0s  max=0s  p(90)=0s  p(95)=0s
   ✓ http_req_failed................: 0% ✓ 0           ✗ 0
     iteration_duration.............: avg=6µs min=6µs med=6µs max=6µs p(90)=6µs p(95)=6µs
     iterations.....................: 1    1184.191517/s
```

On another note thought it also isn't 0% ... I would just argue this will be *less* confusing for users - maybe we should have warning messages for metrics with thresholds that didn't get any samples and tell users that the summary for them will show 0 and NaN :shrug: 

### Actual behaviour

```
     data_received..................: 0 B  0 B/s
     data_sent......................: 0 B  0 B/s
     http_req_duration..............: avg=0s  min=0s  med=0s  max=0s  p(90)=0s  p(95)=0s
     ✓ { expected_response:true }...: avg=0s  min=0s  med=0s  max=0s  p(90)=0s  p(95)=0s
   ✓ http_req_failed................: NaN% ✓ 0           ✗ 0
     iteration_duration.............: avg=6µs min=6µs med=6µs max=6µs p(90)=6µs p(95)=6µs
     iterations.....................: 1    1184.191517/s
```

**Comment by na--** [comment]
This was closed by https://github.com/grafana/k6/pull/2542, right?

**Comment by oleiade** [comment]
👍🏻
