### ISSUE TITLE
How to solve concurrency in js script?

### ISSUE THREAD

**Issue by heliping** [grafana/k6#2592]
### Feature Description

I used mqtt function. 
first I subscribed a topic, and hold on for waiting message coming. 
second I request a restful api to let the server send the mqtt message.

I found mqtt consume is pending, didnot able to hold on and continue to send request to server.

so how to fillful this situation? does anyone have the experience?
Need two processes.

**Comment by na--** [comment]
Sorry, but the k6 GitHub issues are [not the right place to ask questions](https://github.com/grafana/k6/blob/master/SUPPORT.md), especially about an xk6 extension that is not maintained by the k6 team. Please use the [k6 community forum](https://community.k6.io/) or the extension repo itself: https://github.com/pmalhaire/xk6-mqtt
