### ISSUE TITLE
rps=0 value causes a GoError

### ISSUE THREAD

**Issue by Vmihajlovic** [grafana/k6#2613]
### Brief summary

Setting the above parameter in the options object causes a GoError to be thrown during the run. Tested this on both local runs and k6 Cloud, the behaviour is the same.

### k6 version

k6 v0.38.3

### OS

macOS 12.4

### Steps to reproduce the problem

setting an option `rps` in the options object to a value of 0

`export let options = {
    rps: 0,
    "stages": [
        {
            "duration": "5s",
            "target": 15
        },
        {
            "duration": "2m",
            "target": 15
        },
        {
            "duration": "5s",
            "target": 0
        }`
        
causes the following exeption:

`ERRO[0042] GoError: rate: Wait(n=1) exceeds limiter's burst 0
Run    [at go.k6.io/k6/js/modules/k6/http.(*RootModule).NewModuleInstance.func2 (native)
        at file:///Users/nobody/Documents/GitHub/Demo-scripts/SimpleDemo.js:34:12(5)
        at native
 executor=ramping-vus scenario=default  instance_id=1 lz="amazon:ie:dublin" source=stacktrace test_run_id=1429887
` 

### Expected behaviour

It would be expected either a validation/config error to be thrown out or that the `rps` limit is disabled/unlimited.

### Actual behaviour

the test runs successfully, but it throws out the errors constantly in the console:

`ERRO[0042] GoError: rate: Wait(n=1) exceeds limiter's burst 0
Run    [at go.k6.io/k6/js/modules/k6/http.(*RootModule).NewModuleInstance.func2 (native)
        at file:///Users/nobody/Documents/GitHub/Demo-scripts/SimpleDemo.js:34:12(5)
        at native
 executor=ramping-vus scenario=default  instance_id=1 lz="amazon:ie:dublin" source=stacktrace test_run_id=1429887
`

**Comment by na--** [comment]
I think it will be both easier to implement and somewhat beneficial if any `rps` value less than or equal to `0` should mean that the RPS limit is disabled, i.e. for that condition to be added to this `if` statement: https://github.com/grafana/k6/blob/2cb1315424681c33c54158c31b52d68354aaefcf/js/runner.go#L438-L440

This way you'd be able to overwrite an `rps` value set from the exported script `options` from the CLI `--rps` flag, for example.

**Comment by tbourrely** [comment]
Hi 😄,
I'd be glad to work on this, would it be ok ?
