### ISSUE TITLE
Unable to install key

### ISSUE THREAD

**Issue by gdcmarinho** [grafana/k6#2657]
### Brief summary

I'm unable to install the latest k6 version when trying to add the key in the docs.

### k6 version

Latest

### OS

Ubuntu WSL

### Steps to reproduce the problem

Execute the command: sudo gpg --no-default-keyring --keyring /usr/share/keyrings/k6-archive-keyring.gpg --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys C5AD17C747E3415A3642D57D77C6C491D6AC1D69

### Expected behaviour

Key added successfully

### Actual behaviour

com:80 --recv-keys C5AD17C747E3415A3642D
gpg: failed to create temporary file '/root/.gnupg/.#lk0x00005571b4b446e0.DESKTOP-.2122': No such file or directory
gpg: connecting dirmngr at '/root/.gnupg/S.dirmngr' failed: No such file or directory
gpg: keyserver receive failed: No dirmngr

I removed some letters to protect some personal data.

**Comment by imiric** [comment]
Hi, please see the [installation troubleshooting section](https://k6.io/docs/getting-started/installation/troubleshooting/#error-importing-k6s-gpg-key) for the solution.

**Comment by gdcmarinho** [comment]
Fixed, thanks @imiric!
