### ISSUE TITLE
Add support for StatsD Socket

### ISSUE THREAD

**Issue by ghostsquad** [grafana/k6#2659]
### Feature Description

This is a request to allow metrics to be shipped to a socket instead of just UDP.

This is because there's no "origin detection" available when shipping metrics via StatsD UDP to Datadog.

https://docs.datadoghq.com/developers/dogstatsd/?tab=kubernetes#origin-detection-over-udp

**Comment by na--** [comment]
Thanks for opening this issue! I don't have an easy way to test this right now, but are you sure that k6 doesn't support this already?

From what I can see in the code, we don't do any checks for this and we use the datadog statsd library directly, so you should just be able to use `K6_STATSD_ADDR=unix:///path/to/socket` and that should work?

**Comment by ghostsquad** [comment]
I'm not super sure, the documentation only mentions UDP. I will try it and see. If it works I can change this issue to reflect a documentation update.

**Comment by ghostsquad** [comment]
> we use the datadog statsd library directly

Oh that's even better! This all stems from needing origin detection.

**Comment by na--** [comment]
Does it work? And, if it does, can you please close this issue and open a new one in https://github.com/grafana/k6-docs/issues? :sweat_smile:

**Comment by mmailhos** [comment]
Hey @ghostsquad, have you been able to use `K6_STATSD_ADDR=unix:///path/to/socket`?

**Comment by kkopachev** [comment]
It works

**Comment by mmailhos** [comment]
I can confirm too, it works

**Comment by ghostsquad** [comment]
Yes it works. Sorry for the super late reply!
