### ISSUE TITLE
K6 outputting duplicate metrics

### ISSUE THREAD

**Issue by perrinj3** [grafana/k6#2662]
### Brief summary

When using more that 1 vu and generating a high TPS we get a percentage of duplicate metrics. The duplicates can be seen in a JSON file and comprise 2% of the total number of samples at TPS = 848 with 5 VUs

### k6 version

v0.39.0

### OS

Windows

### Steps to reproduce the problem

A simple script with 3 endpoints and more than 1 VU will result in duplicates being generated. 

### Expected behaviour

No duplicates generated

### Actual behaviour

With 5 VUs and a sleep time of 0.0001 secs we get 848 TPS and 2% duplicates generated when K6 outputs to a JSON file.
If we output to Prometheus we also see duplicate sample errors in the Prometheus log. No actual data is lost though

**Comment by na--** [comment]
What exactly do you mean by "duplicate metrics"? Can you paste a sample of the JSON output file and maybe your script (with any sensitive details redacted), so we can understand what you mean and investigate the issue.

**Comment by perrinj3** [comment]
Hi. I think I mean  sample or one line in the JSON file. Sorry if metric is confusing but each line contains a single metric.
Sample of JSON file below followed by script. In this short 50s test there were 476877 samples of which 54883 were duplicates. 
The sample with time":"2022-08-26T09:24:55.6691184+10:00 is the one duplicated in the extract from the JSON file. I guess it's possible under high load for 2 samples to have the timestamp and values but I'm not clear what is expected behaviour and Prometheus does log every duplicate as an error. If they are valid then we are losing the samples that Prometheus rejects as duplicates. I've tried to replicate the behaviour using a simple script. With or P&V testing they scripts are much more complex but we still see the same errors in the Prometheus log.
```
{"type":"Point","data":{"time":"2022-08-26T09:24:55.6691184+10:00","value":116,"tags":{"group":"","scenario":"default"}},"metric":"data_sent"}
{"type":"Point","data":{"time":"2022-08-26T09:24:55.6691184+10:00","value":12252,"tags":{"group":"","scenario":"default"}},"metric":"data_received"}
{"type":"Point","data":{"time":"2022-08-26T09:24:55.6691184+10:00","value":5.9914,"tags":{"group":"","scenario":"default"}},"metric":"iteration_duration"}
{"type":"Point","data":{"time":"2022-08-26T09:24:55.6691184+10:00","value":1,"tags":{"group":"","scenario":"default"}},"metric":"iterations"}
{"type":"Point","data":{"time":"2022-08-26T09:24:55.6691184+10:00","value":116,"tags":{"group":"","scenario":"default"}},"metric":"data_sent"}
{"type":"Point","data":{"time":"2022-08-26T09:24:55.6691184+10:00","value":12252,"tags":{"group":"","scenario":"default"}},"metric":"data_received"}
{"type":"Point","data":{"time":"2022-08-26T09:24:55.6691184+10:00","value":5.9914,"tags":{"group":"","scenario":"default"}},"metric":"iteration_duration"}
{"type":"Point","data":{"time":"2022-08-26T09:24:55.6691184+10:00","value":1,"tags":{"scenario":"default","group":""}},"metric":"iterations"}
{"type":"Point","data":{"time":"2022-08-26T09:24:55.6701347+10:00","value":1,"tags":{"url":"http://appau401mel5154.globaltest.anz.com","name":"http://appau401mel5154.globaltest.anz.com","method":"GET","status":"200","proto":"HTTP/1.1","expected_response":"true","group":"","scenario":"default"}},"metric":"http_reqs"}
{"type":"Point","data":{"time":"2022-08-26T09:24:55.6701347+10:00","value":1.0163,"tags":{"status":"200","proto":"HTTP/1.1","expected_response":"true","group":"","scenario":"default","url":"http://appau401mel5154.globaltest.anz.com","name":"http://appau401mel5154.globaltest.anz.com","method":"GET"}},"metric":"http_req_duration"}
{"type":"Point","data":{"time":"2022-08-26T09:24:55.6701347+10:00","value":0,"tags":{"method":"GET","status":"200","proto":"HTTP/1.1","expected_response":"true","group":"","scenario":"default","url":"http://appau401mel5154.globaltest.anz.com","name":"http://appau401mel5154.globaltest.anz.com"}},"metric":"http_req_blocked"}
{"type":"Point","data":{"time":"2022-08-26T09:24:55.6701347+10:00","value":0,"tags":{"group":"","scenario":"default","url":"http://appau401mel5154.globaltest.anz.com","name":"http://appau401mel5154.globaltest.anz.com","method":"GET","status":"200","proto":"HTTP/1.1","expected_response":"true"}},"metric":"http_req_connecting"}
{"type":"Point","data":{"time":"2022-08-26T09:24:55.6701347+10:00","value":0,"tags":{"method":"GET","status":"200","proto":"HTTP/1.1","expected_response":"true","group":"","scenario":"default","url":"http://appau401mel5154.globaltest.anz.com","name":"http://appau401mel5154.globaltest.anz.com"}},"metric":"http_req_tls_handshaking"}
{"type":"Point","data":{"time":"2022-08-26T09:24:55.6701347+10:00","value":0,"tags":{"name":"http://appau401mel5154.globaltest.anz.com","method":"GET","status":"200","proto":"HTTP/1.1","expected_response":"true","group":"","scenario":"default","url":"http://appau401mel5154.globaltest.anz.com"}},"metric":"http_req_sending"}
{"type":"Point","data":{"time":"2022-08-26T09:24:55.6701347+10:00","value":1.0163,"tags":{"name":"http://appau401mel5154.globaltest.anz.com","method":"GET","status":"200","proto":"HTTP/1.1","expected_response":"true","group":"","scenario":"default","url":"http://appau401mel5154.globaltest.anz.com"}},"metric":"http_req_waiting"}
{"type":"Point","data":{"time":"2022-08-26T09:24:55.6701347+10:00","value":0,"tags":{"status":"200","proto":"HTTP/1.1","expected_response":"true","group":"","scenario":"default","url":"http://appau401mel5154.globaltest.anz.com","name":"http://appau401mel5154.globaltest.anz.com","method":"GET"}},"metric":"http_req_receiving"}
{"type":"Point","data":{"time":"2022-08-26T09:24:55.6701347+10:00","value":0,"tags":{"expected_response":"true","group":"","scenario":"default","url":"http://appau401mel5154.globaltest.anz.com","name":"http://appau401mel5154.globaltest.anz.com","method":"GET","status":"200","proto":"HTTP/1.1"}},"metric":"http_req_failed"}
{"type":"Point","data":{"time":"2022-08-26T09:24:55.6711154+10:00","value":116,"tags":{"group":"","scenario":"default"}},"metric":"data_sent"}
{"type":"Point","data":{"time":"2022-08-26T09:24:55.6711154+10:00","value":12252,"tags":{"group":"","scenario":"default"}},"metric":"data_received"}
{"type":"Point","data":{"time":"2022-08-26T09:24:55.6711154+10:00","value":1.9969,"tags":{"group":"","scenario":"default"}},"metric":"iteration_duration"}
```
Script is as follows.

```
import http from 'k6/http';
import { sleep } from 'k6';

export default function () {

  let res1 = http.get('http://apacheHost',);
  
  sleep(.0001)
}


```

**Comment by na--** [comment]
Hmm :thinking: Not sending duplicate metrics to Prometheus is probably an issue for [xk6-output-prometheus-remote](https://github.com/grafana/xk6-output-prometheus-remote/). And it should soon be possible to fix easily, after https://github.com/grafana/k6/pull/2594 is merged.

In JSON/CSV/etc. other outputs, it's not a problem if you have the same duplicate metrics, if that happens coincidentally. However, it is somewhat suspicious you have so many duplicates :confused: In the snippet you gave, you have a two sets of metrics k6 emits at the end of an iteration with exactly the same timestamp, `iteration_duration`, `data_sent` and `data_received` values... That is possible for the first several iterations, especially since your script is so simple and deterministic, but I find it unlikely that it will happen 54883 times :confused: So it's worth investigating if this might be a bug in k6.

For now, if you want to avoid this, you can probably do so by enabling the `vu` and `iter` system tags, see:
- https://k6.io/docs/using-k6/tags-and-groups/#system-tags
- https://k6.io/docs/using-k6/k6-options/reference/#system-tags

We are going to make some breaking changes to them in k6 v0.41.0 (https://github.com/grafana/k6/issues/2584), but for now they should afford you a temporary workaround. And if you have duplicate metric samples with these two flags enabled, I'd say that there is definitely a bug in k6 or the k6 JSON output somewhere...

**Comment by perrinj3** [comment]
Thanks for looking at this. I agree that it seems strange to have so many duplicates with the same timestamp. We've seen this is more complex scripts so I created a simple script to allow easier analysis of the JSON file.
Good suggestion on the optional system tags. I've run a test with vu and iter enabled and now get zero duplicates. So we can use that in the interim. Much appreciated.
