### ISSUE TITLE
Support for configuring maximum call receive message size 

### ISSUE THREAD

**Issue by mihir-nference** [grafana/k6#2666]
### Feature Description

Currently there is no way to change maximum call receive message size for grpc client.
I use this snippet to create a client, but there is no param to configure max message size
```
const client = new grpc.Client();
client.load(['protobuf'], 'vormir.proto');
client.connect('hz-mihirn01.nferx.com:50051', {
  plaintext: true,
  timeout: '1m',
  // need to add max message size here
});
```

### Suggested Solution (optional)

```
const client = new grpc.Client();
client.load(['protobuf'], 'vormir.proto');
client.connect('hz-mihirn01.nferx.com:50051', {
  plaintext: true,
  timeout: '1m',
  // add new param
  max_receive_size: 100000,
});
```

**Comment by na--** [comment]
Thanks for opening this issue, it's indeed a missing functionality :disappointed: These are the options on the Go side:
- https://pkg.go.dev/google.golang.org/grpc#MaxCallRecvMsgSize
- https://pkg.go.dev/google.golang.org/grpc#MaxCallSendMsgSize

So it's probably best to expose them separately and to have the option names in `camelCase`, to match the rest of the flags.

**Comment by mihir-nference** [comment]
Any update on this @na-- , when will this be added?

**Comment by na--** [comment]
We haven't prioritized it yet, so I can't say when one of the k6 devs might work on it, sorry. We'll probably accept a good pull request that adds the feature though, and it should be easy enough to add, that's why I tagged it as a `good first issue`.

**Comment by ariasmn** [comment]
Hi! I'm working on this.
Might take some time since I'm not that proficient in Golang, but I'll try to have it ready ASAP!

**Comment by ariasmn** [comment]
So, before I open a PR I want to make sure that everything is correct.

I created a commit which you can see [here](https://github.com/ariasmn/k6/commit/71ea856a1712af542860f552d8d0cbd93e278dd2).

To test it, I used the following `.proto` definition:
```
// ./definitions/hello.proto

// based on https://grpc.io/docs/guides/concepts.html

syntax = "proto2";

package hello;

service HelloService {
  rpc SayHello(HelloRequest) returns (HelloResponse);
  rpc LotsOfReplies(HelloRequest) returns (stream HelloResponse);
  rpc LotsOfGreetings(stream HelloRequest) returns (HelloResponse);
  rpc BidiHello(stream HelloRequest) returns (stream HelloResponse);
}

message HelloRequest {
  optional string greeting = 1;
}

message HelloResponse {
  required string reply = 1;
}
```

The test looks like:
```
import grpc from 'k6/net/grpc';
import { check, sleep } from 'k6';

const client = new grpc.Client();
client.load(['.'], 'hello.proto');

export default () => {
  client.connect('grpcbin.test.k6.io:9001', {
    plaintext: false,
    maxReceiveSize: 1,
    maxSendSize: 1
  });

  const data = { greeting: 'Bert' };
  const response = client.invoke('hello.HelloService/SayHello', data);

  check(response, {
    'status is OK': (r) => r && r.status === grpc.StatusOK,
  });

  console.log(JSON.stringify(response.message));

  client.close();
  sleep(1);
};
```

When testing it, you can clearly see that it's clearly working since the reply never shows, however, the report data still shows that the `data_received` and `data_sent` are higher than the declared values.

Before looking any further into it, does it makes sense? Am I missing something? (sure I am)

Sorry if it comes as an stupid question, but I honestly don't know and I feel like is easier to ask than dive deep down into the codebase.

**Comment by na--** [comment]
> the report data still shows that the `data_received` and `data_sent` are higher than the declared values.

`data_received` and `data_sent` measure the raw network traffic that a VU makes, so it's normal that they are higher. The connection establishment and all of the metadata are also counted there.

**Comment by ariasmn** [comment]
@na-- Makes sense, thank you so much for the explanation!

I just opened a PR. Please, if something is not right, just let me know and I will try to work on it.
