### ISSUE TITLE
base64 decoding is broken (k6/encoding package)

### ISSUE THREAD

**Issue by vologab** [grafana/k6#2670]
### Brief summary

This sample script https://github.com/grafana/k6/blob/a33b054344416f32a5034732be1da06018a682bc/samples/base64.js from the repo doesn't work both locally (MAC OS) and inside docker container

### k6 version

k6 v0.39.0 ((devel), go1.18.3, darwin/amd64)

### OS

macOS

### Docker version and image (if applicable)

7cf3c740cfce

### Steps to reproduce the problem

1. Copy this script https://github.com/grafana/k6/blob/a33b054344416f32a5034732be1da06018a682bc/samples/base64.js
2. Run it 
2.1 directly `k6 run base64.js`
2.2 via docker `cat base64.js | docker run -i grafana/k6 run -`
3. In both cases decoding is failing

### Expected behaviour

Decoding is working :)

### Actual behaviour

Decoding is not working

**Comment by mstoykov** [comment]
Hi @vologab, thanks for reporting this :bow:.

It seems like we didn't update this sample after a [breaking change over a year ago](https://github.com/grafana/k6/pull/1841). I have now opened a PR fixing it.

**Comment by vologab** [comment]
Hi @mstoykov. Thanks for so fast reaction, updated sample works properly 🙇
