### ISSUE TITLE
Global variables declared in init context no longer work when running tests with docker

### ISSUE THREAD

**Issue by geaninahutanu** [grafana/k6#2680]
`k6 run k6-tests/test-main-file.js` works without problem.

`docker run -v $(pwd)/k6-tests:/k6-tests -i loadimpact/k6 run /k6-tests/test-main-file.js` throws an error 
 "msg="ReferenceError: context is not defined\n\tat first_scenario"

**test-main-file.js**
```
import {first_scenario as first_scenario} from "./first_scenario.js"
export {first_scenario as first_scenario}

const context = {
  id: __VU,
  expiresAt: '2023-08-12T09:20:36.148Z',
  requestBody: JSON.parse(open("request-template")),
}

export let options = {
  thresholds: {
    http_req_failed: ['rate < 0.01'],   // http errors should be less than 1%
    http_req_duration: ['p(95) < 10000', 'p(99) < 15000'], // 95% of requests should be below 200ms
  },
  noConnectionReuse: true,
  scenarios: {
    first_scenario: {
      exec: "first_scenario",
      executor: 'ramping-arrival-rate',
      timeUnit: '1s',
      startRate: 10,
      preAllocatedVUs: 10,
      maxVUs: 50,
      stages: [{target: 30, duration: '3s'}]
    }
  }
}
```
**first_scenario.js**
```
import {clone} from "./util/util.js";

export function first_scenario() {
    let request = clone(context.requestBody)
    request.expires_at = context.expiresAt
    ...
}
```

**Comment by mstoykov** [comment]
Hi @geaninahutanu, 

why would you expect that you will be able to access `context` from the main module without importing it in the `first_scenario.js` ?

This is exactly that modules are supposed to prevent. Unfortunately k6 did have a [bug](https://github.com/grafana/k6/pull/2571) where that was *not* the case until the [last release](https://github.com/grafana/k6/releases/tag/v0.40.0), done last week. You can also look at the `Breaking changes` section it is basically just after the list of smaller breaking changes.

As mentioned there if you want something to be *just* globally available you should use the [global object `globalThis`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/globalThis)

I would expect that you are running the latest version in docker, but not outside.

A previous issue with a more confusing error was https://github.com/grafana/k6/issues/2623
