### ISSUE TITLE
k6/net/grpc: load a protoset rather than individual proto files

### ISSUE THREAD

**Issue by jklipp** [grafana/k6#2700]
### Feature Description

We use buf.build along with the buf schema registry to pull in some well-known protos (googleapis, envoyproxy/protoc-gen-validate) rather than vendor them in our own repo.  As such, it's a bit awkward to try to provide these protos to the grpc `Client.load` function as our proto dependencies may not be around locally on disk.  

### Suggested Solution (optional)

It's pretty common for grpc tooling to accept a protoset (a proto-serialized set of protos) rather than individual proto files and import paths, and would be nice of there was an additional `Client.loadProtoset` or similar functionality on the k6 grpc interface.

This looks pretty straightforwad, would k6 be interested in a PR?

**Comment by bourquep** [comment]
@jklipp Have you been able to load protosets from the Buf schema registry with k6?
