### ISSUE TITLE
Websockets should return HTTP error codes

### ISSUE THREAD

**Issue by brietaylor** [grafana/k6#2711]
### Feature Description

Given the example code from https://k6.io/docs/using-k6/protocols/websockets/

```js
import ws from 'k6/ws';
import { check } from 'k6';

export default function () {
  const url = 'ws://echo.websocket.org';
  const params = { tags: { my_tag: 'hello' } };

  const res = ws.connect(url, params, function (socket) {
    socket.on('open', () => console.log('connected'));
    socket.on('message', (data) => console.log('Message received: ', data));
    socket.on('close', () => console.log('disconnected'));
  });

  check(res, { 'status is 101': (r) => r && r.status === 101 });
}
```

I'd like to extend this code with some custom behaviour for different status codes.  For example:

```js
if (res.status == 429) {
  console.log("Slow down");
  sleep(3); // backoff
} else {
  // error handling
}
```

However, if you try to run this code against a server that returns 429, `res.status` gets set to 0.  And there is no apparent workaround.

I think this is probably a bug and not a feature, given that the examples on the website explicitly check `res.status`.  Although I couldn't find any documentation indicated whether this was expected behaviour or not.

### Suggested Solution (optional)

I think this is a short change in `modules/k6/ws/ws.go`.  I've written a brief PR, which I'll link here.

### Already existing or connected issues / PRs (optional)

https://github.com/grafana/k6/pull/2712

**Comment by mstoykov** [comment]
closed with #2712
