### ISSUE TITLE
k6/ws: connect doesn't emit wssessionduration on exception in setup

### ISSUE THREAD

**Issue by mstoykov** [grafana/k6#2734]
### Brief summary

The `k6/ws` module's 'connect` doesn't emit `WSSessionDuraiton` if there is exception the first callback it has.

Given that at that point k6 will emit `ws_sessions` (and `ws_connecting) (since 0.27.1 at least) - it seems reasonable to also emit `ws_session_duration` 

This was noticed while rewriting test for lint issues and it turn out [one of them](https://github.com/grafana/k6/pull/2732#discussion_r996756991) was checking for this, but was getting false possitive due to reusage of test setup. 

### k6 version

v0.40.0

### OS

linux

### Steps to reproduce the problem

run 
```
import ws from 'k6/ws';

export default function() {
  let url = `wss://test-api.k6.io/ws/crocochat/test/`;

  let res = ws.connect(url, function(socket) { throw "oops" });
}
```

Obviously the real code will be probably something that fails with an exception then actually just throwing within ;)

### Expected behaviour

Emit all the three ws metrics even with very low valuse

### Actual behaviour

emitting 2 of the 3 metrics

**Comment by mstoykov** [comment]
The "fix" for this will mostly entail moving (parts) of this defer 
https://github.com/grafana/k6/blob/ab810e79c9f2428be82b641d1b02d0d843c49c54/js/modules/k6/ws/ws.go#L324-L337
 up, before this line
https://github.com/grafana/k6/blob/ab810e79c9f2428be82b641d1b02d0d843c49c54/js/modules/k6/ws/ws.go#L300-L301

This might turn out to require more changes though due to some more shared state.

**Comment by codebien** [comment]
>it seems reasonable to also emit `ws_session_duration`

I agree

>up, before this line

@mstoykov Why do we emit `WSSessions` a few lines before? Should we move it to the same place where we set the defer? I would expect to emit always `ws_session_duration` if we are emitting `ws_sessions`.

**Comment by mstoykov** [comment]
This was *changed* as part of https://github.com/grafana/k6/pull/1367. Before it everything was done when the websocket ends. This had a couple of different problems, the biggest one being that long running websocket connections with a lot of ws_message_received, used to take quite a while to push all the metrics when this ended. It was also very strange that we were emitting metrics a few minutes after they happened. And caching all of that was taking a lot of memory. All in all, it was a bad and this PR fixed that.

Looking at the description I meant to leave the emittion of the sesions and connectio nmetrics at the end but @na-- [asked](https://github.com/grafana/k6/pull/1367#discussion_r395081802) to be moved as much "up" as possible. 

From purely logical point of view - we do have a session from the moment the connection happens. The "open" callback is called after that and might take as much time as it wants to complete.

So it makes a lot of senses to also send `ws_session_duration` even if the "open" callback aborts.
