### ISSUE TITLE
SSLKEYLOGFILE not working on Windows

### ISSUE THREAD

**Issue by martinp999** [grafana/k6#2736]
### Brief summary

When the environment variable SSLKEYLOGFILE is set, k6 seems to append the value to the current path when looking for the key log file.  This results in `C:\BitBucket\performance_testing_tpg\C:\Tools\sslkeylogfile\ssl.log`, which results in an error "The filename, directory name, or volume label syntax is incorrect.".

I have worked around this by setting that environment variable to `\ssl.log`, but then traffic from the browsers is not captured.

### k6 version

k6 v0.39.0 (2022-07-05T10:50:14+0000/v0.39.0-0-g5904fd8, go1.18.3, windows/amd64)

### OS

Windows 10

### Steps to reproduce the problem

On Windows - 

`PS C:\Temp> SetX SSLKEYLOGFILE "$(get-location)\ssl.log"`

run some load from k6

### Expected behaviour

TLS keys for traffic from k6 should be logged into `C:\Temp\ssl.log`

### Actual behaviour

WARN[0000] SSLKEYLOGFILE was specified, logging TLS connection keys to 'C:\Temp\ssl.log'...  test_path="file:///C:/BitBucket/performance_testing_tpg/scenarios/contracts.js"
ERRO[0000] could not initialize '.\scenarios\contracts.js': open C:\BitBucket\performance_testing\C:\Temp\ssl.log: The filename, directory name, or volume label syntax is incorrect.

**Comment by mstoykov** [comment]
Hi @martinp999, thanks for reporting this. 

Can you please try [v0.40.0](https://github.com/grafana/k6/releases/tag/v0.40.0) as I think maybe you are hitting https://github.com/grafana/k6/pull/2604 which was fixed in v0.40.0

**Comment by mstoykov** [comment]
I am closing this as I am pretty sure this was fixed in v0.40.0 and @martinp999 hasn't come back. 

We can reopen it if needed.
