### ISSUE TITLE
Flaky csv output test

### ISSUE THREAD

**Issue by mstoykov** [grafana/k6#2740]
It seems like after #2727  CSV output test is [failing](https://github.com/grafana/k6/actions/runs/3281412666/jobs/5403385124) as the metadata isn't ordered the same way every time 
![image](https://user-images.githubusercontent.com/312246/196689625-17325af8-8299-4785-ae57-5e0d5e970cc9.png)

**Comment by na--** [comment]
Ah, yeah... IIRC, the output doesn't sort the tags and metadata (probably for performance reasons, though we can certainly optimize the tags output further now...), but rather the tests account for the unsorted tags and use this: https://github.com/grafana/k6/blob/b60fe887f035adcfb59cd7fd0869f69c5442b5b8/output/csv/output_test.go#L370

So we should just use the same for the last column now

**Comment by codebien** [comment]
Closed by https://github.com/grafana/k6/pull/2741
