### ISSUE TITLE
Provide timestamps in the final report for the beginning and end of the execution

### ISSUE THREAD

**Issue by martinp999** [grafana/k6#2748]
### Feature Description

This would make it easier to correlate results.  For example, what time period should I be looking at in Grafana, or in perfmon.

**Comment by na--** [comment]
You can already do this with the current k6 version. For example, measure the current time in `setup()` and return it, and then in `handleSummary()` you can measure the end time and output both. See these:
- https://k6.io/docs/using-k6/test-life-cycle/
- https://k6.io/docs/results-output/end-of-test/custom-summary/

Is this sufficient for your needs?

**Comment by codebien** [comment]
Closing as no reported details, feel free to reopen if you have more details.
