### ISSUE TITLE
Thresholds over Trend metrics fail as the `med` sink's value remains zero 

### ISSUE THREAD

**Issue by oleiade** [grafana/k6#2755]
### Brief summary

As reported by a user on the [OSS support forum](https://community.k6.io/t/bug-with-k6-threshold-validation/5038), there seems to be an issue with Thresholds applying to the median value of Trend metrics. Both core and custom metrics are affected.

Setting a threshold on a Trend metric's value, such as `http_req_duration`, will always fail, regardless of the expression used.

### k6 version

>= v0.40.0

### OS

Docker + Linux

### Docker version and image (if applicable)

loadimpact/k6:latest

### Steps to reproduce the problem

Here is an example script demonstrating the issue. It depends on having [Lhotse](https://github.com/oleiade/lhotse) running locally to simulate the desired performance of a target HTTP server. 

```javascript
import { check } from "k6";
import http from "k6/http";
import { Trend } from "k6/metrics";

export let options = {
  thresholds: {
    http_req_duration: ["med>39"],
    custom_trend: ["med>39"],
  },

  scenarios: {
    issueHappensWithCoreTrendMetric: {
      executor: "constant-arrival-rate",
      exec: "exampleFunction",
      rate: 1,
      timeUnit: "30s",
      duration: "30s",
      preAllocatedVUs: 2,
      exec: "issueHappensWithCoreTrendMetric",
    },
    issueHappensWithCustomTrendMetric: {
      executor: "constant-arrival-rate",
      exec: "exampleFunction",
      rate: 1,
      timeUnit: "30s",
      duration: "30s",
      preAllocatedVUs: 2,
      exec: "issueHappensWithCustomTrendMetric",
    },
  },
};

export function issueHappensWithCoreTrendMetric() {
  // Server produces requests that will take between 70, and 80ms
  // to complete. Hence, the resulting http_req_duration metric
  // should have a median value well above the 39ms threshold.
  const res = http.get("http://localhost:3434/latency/70ms-80ms", {}, {});

  check(res, {
    "is status 200": (r) => r.status === 200,
  });
}

const customTrend = new Trend("custom_trend");

export function issueHappensWithCustomTrendMetric() {
  // Add values to the custom trend metric so that its median
  // value is well above the 39ms threshold.
  customTrend.add(70);
  customTrend.add(80);
  customTrend.add(90);
}
```

In this example, both thresholds on the `http_req_duration`, and `custom_trend` will fail, although the performance of the target HTTP server, and the values fed into the Trend should lead them to pass.

### Expected behaviour

We would expect thresholds to pass.

### Actual behaviour

```
     checks.........................: 100.00% ✓ 1                    ✗ 0  
   ✗ custom_trend...................: avg=80       min=70       med=80       max=90       p(90)=90       p(95)=90      
     data_received..................: 156 B   5.1996295251830835 B/s
     data_sent......................: 97 B    3.233102973992046 B/s
     http_req_blocked...............: avg=271.89µs min=271.89µs med=271.89µs max=271.89µs p(90)=271.89µs p(95)=271.89µs
     http_req_connecting............: avg=148.23µs min=148.23µs med=148.23µs max=148.23µs p(90)=148.23µs p(95)=148.23µs
   ✗ http_req_duration..............: avg=75.52ms  min=75.52ms  med=75.52ms  max=75.52ms  p(90)=75.52ms  p(95)=75.52ms 
       { expected_response:true }...: avg=75.52ms  min=75.52ms  med=75.52ms  max=75.52ms  p(90)=75.52ms  p(95)=75.52ms 
     http_req_failed................: 0.00%   ✓ 0                    ✗ 1  
     http_req_receiving.............: avg=86.24µs  min=86.24µs  med=86.24µs  max=86.24µs  p(90)=86.24µs  p(95)=86.24µs 
     http_req_sending...............: avg=73.97µs  min=73.97µs  med=73.97µs  max=73.97µs  p(90)=73.97µs  p(95)=73.97µs 
     http_req_tls_handshaking.......: avg=0s       min=0s       med=0s       max=0s       p(90)=0s       p(95)=0s      
     http_req_waiting...............: avg=75.36ms  min=75.36ms  med=75.36ms  max=75.36ms  p(90)=75.36ms  p(95)=75.36ms 
     http_reqs......................: 1       0.033331/s
     iteration_duration.............: avg=25.42ms  min=65.8µs   med=68.75µs  max=76.12ms  p(90)=60.91ms  p(95)=68.51ms 
     iterations.....................: 3       0.099993/s
     vus............................: 4       min=4                  max=4
     vus_max........................: 4       min=4                  max=4
```

Although the displayed median values are consistent with a threshold that should be passing, we observe the opposite.

**Comment by oleiade** [comment]
I have traced back the issue to the [`Thresholds.Run` method](https://github.com/grafana/k6/blob/master/metrics/thresholds.go#L191). As I debug through the execution of this script's execution, the `ts.sinked["med"]` value remains `0`.

**Comment by na--** [comment]
I think this might be happening because we are not calling the `TrendSink`'s `Calc()` method: https://github.com/grafana/k6/blob/11deb073b9dd628f68b8c00aa7cc4de427955694/metrics/sink.go#L123-L137

Or at least I don't see where we are calling it in `Thresholds.Run()`, while it internally is called by both the percentile and the format methods:
https://github.com/grafana/k6/blob/11deb073b9dd628f68b8c00aa7cc4de427955694/metrics/sink.go#L139-L140
https://github.com/grafana/k6/blob/11deb073b9dd628f68b8c00aa7cc4de427955694/metrics/sink.go#L103-L114

And if there is a threshold on `med` for a `Trend` metric without a percentile threshold on the same metric to call `Calc()` eventually, the value of `Med` will never actually be calculated: https://github.com/grafana/k6/blob/11deb073b9dd628f68b8c00aa7cc4de427955694/metrics/thresholds.go#L191-L202

I might be missing something, but I think this is at least part of the problem. An easy workaround would be to just use `p(50)` instead of `med`, since they are basically the same thing, but this feels like a major bug :disappointed: Potentially enough for releasing v0.41.1 :thinking:

**Comment by na--** [comment]
Here is a simpler script that demonstrates the issue:
```js
import { Trend } from 'k6/metrics';

export let options = {
    scenarios: {
        issueHappensWithCoreTrendMetric: {
            executor: 'constant-arrival-rate',
            rate: 1,
            duration: '10s',
            preAllocatedVUs: 2,
        },
    },
    thresholds: {
        custom_trend: [{
            threshold: 'med<39',
            abortOnFail: true
        }],
    },
};

const customTrend = new Trend('custom_trend');

export default function () {
    customTrend.add(80);
}
```

If you run it with `--verbose`, you'd see something like this:
```
...
DEBU[0002] running thresholds                            component=metrics-engine metric_name=custom_trend
DEBU[0004] running thresholds                            component=metrics-engine metric_name=custom_trend
DEBU[0006] running thresholds                            component=metrics-engine metric_name=custom_trend
DEBU[0008] running thresholds                            component=metrics-engine metric_name=custom_trend
DEBU[0010] running thresholds                            component=metrics-engine metric_name=custom_trend
...
DEBU[0010] Processing metrics and thresholds after the test run has ended...  component=engine
...
DEBU[0010] running thresholds                            component=metrics-engine metric_name=custom_trend
DEBU[0010] Engine run terminated cleanly                
...
DEBU[0010] Engine: Thresholds terminated                 component=engine
...

   ✓ custom_trend.........: avg=80      min=80      med=80      max=80      p(90)=80      p(95)=80     
     data_received........: 0 B 0 B/s
     data_sent............: 0 B 0 B/s
     iteration_duration...: avg=40.28µs min=31.58µs med=37.69µs max=63.47µs p(90)=62.05µs p(95)=62.76µs
     iterations...........: 11  1.099916/s
     vus..................: 2   min=2      max=2
     vus_max..............: 2   min=2      max=2

DEBU[0010] Waiting for engine processes to finish...    
DEBU[0010] Metrics processing winding down...            component=engine
DEBU[0010] running thresholds                            component=metrics-engine metric_name=custom_trend
DEBU[0010] Thresholds failed                             component=metrics-engine metric_name=custom_trend
DEBU[0010] Everything has finished, exiting k6!         
DEBU[0010] Stopping 1 outputs...                         component=output-manager
DEBU[0010] Stopping...                                   component=metrics-engine-ingester
DEBU[0010] Stopped!                                      component=metrics-engine-ingester
ERRO[0010] some thresholds have failed                  
exit status 99
```

The threshold has always been breached, and k6 was supposed to abort the script immediately when it noticed. However, it was happily running it until the end, as if the threshold was seemingly not being crossed. However, after the summary was generated, which required calculation of percentiles and thus the calling of `TrendSink.Calc()`, the next time the thresholds were calculated, k6 realized the `med` threshold was crossed and exited the test with the right exit code.

**Comment by na--** [comment]
This bug seems to have been introduced in k6 v0.37.0, probable due to the [threshold refactoring there](https://github.com/grafana/k6/blob/master/release%20notes/v0.37.0.md#introduced-stricter-thresholds-parsing-2400). 

And, for anyone that has hit it, the solution is to just replace `med` with `p(50)` in your threshold definitions. They are the same thing, after all, `med` is just there for convenience.

**Comment by oleiade** [comment]
Heads up, I've started working on a fix for this 👋🏻

**Comment by na--** [comment]
Closed by https://github.com/grafana/k6/pull/2759
