### ISSUE TITLE
K6 does not send metrics like k6.http_req_duration.avg to datadog statsd

### ISSUE THREAD

**Issue by papatelst** [grafana/k6#2776]
### Brief summary

I am using the K6 datadog integration as mentioned here -
https://k6.io/docs/results-visualization/datadog/
I am using docker container to send metrics to datadog from K6 run through teamcity.
The issue is - `k6.http_req_duration.avg` in datadog UI is close to, but never the same as K6 build log. K6 is not sending certain metrics to Datadog.
The details of the issue logged on K6 community website can be found here - https://community.k6.io/t/http-req-duration-wrong-datadog/440/8
see my datadog config below
![image](https://user-images.githubusercontent.com/45948323/202544161-549b917d-0dae-48dd-b1fd-363fa958b479.png)
I opened a ticket with datadog team here - https://help.datadoghq.com/hc/en-us/requests/954788
However, datadog team told me that this is a K6 issue where it is not sending certain metrics for example - `k6.http_req_duration.avg:13930.0 in milliseconds`. Here is a snapshot from their response.
![image](https://user-images.githubusercontent.com/45948323/202544871-b296f1aa-11d9-462c-bd0d-94a7d6768221.png)
Please fix this as it does not seem to be datadog agent issue.

### k6 version

~0.37.0

### OS

Linux

### Steps to reproduce the problem

Run K6 tests using docker and send data to datadog using statsd agent. Compare metrics like k6.http_req_duration.avg in k6 build log and datadog UI timeseries graph

### Expected behaviour

The value of the metric should be the same.

### Actual behaviour

The values are close but never the same.

**Comment by bucurrobert** [comment]
I have a question we have the same issue in our organisation, any update with the bug?

**Comment by LeonAdato** [comment]
Per [@olegbespalov](https://github.com/olegbespalov) and  [@javaducky](https://github.com/javaducky), this issue should probably be part of the StatsD project. Feel free to transfer it here: 

[https://github.com/LeonAdato/xk6-output-statsd](https://github.com/LeonAdato/xk6-output-statsd)

**Comment by olegbespalov** [comment]
Closing in favor of https://github.com/LeonAdato/xk6-output-statsd/issues/25
