### ISSUE TITLE
Wrong percentile values for metrics shown in Datadog

### ISSUE THREAD

**Issue by imiric** [grafana/k6#2819]
### Brief summary

As reported several times on the forum ([1](https://community.k6.io/t/trend-metrics-on-datadog-percentile/3995), [2](https://community.k6.io/t/http-req-duration-wrong-datadog/440/), [3](https://community.k6.io/t/why-do-k6-http-req-duration-max-and-k6-http-req-duration-95percentile-have-the-same-value-in-datadog/5487/3)), the percentile values users can visualize in Datadog are often wrong when compared to the end-of-test summary shown by k6.

As explained [here](https://community.k6.io/t/http-req-duration-wrong-datadog/440/5), this is likely caused by the additional aggregation done by the DogStatsD agent, which by default only generates the `95percentile` metric, which is then aggregated again by the query used in the Datadog graph.

Besides resulting in wrong values, users are unable to use raw metric data to generate any percentile value they need.

### k6 version

0.41.0

### OS

any

### Steps to reproduce the problem

1. Follow the steps to setup the Datadog Agent, and run a test as explained [here](https://k6.io/docs/results-output/real-time/datadog/).

2. Go to the Datadog web UI and visualize the `k6.http_req_duration.max` and `k6.http_req_duration.95percentile` metrics, and compare them to the end-of-test summary shown by k6. Notice that they don't match.

### Expected behaviour

- The percentiles shown in Datadog should match the end-of-test summary shown by k6.

- The user should be able to generate any percentile over raw metric data sent to Datadog. Ideally, the Datadog Agent (DogStatsD) shouldn't do any aggregation at all.

### Actual behaviour

- The percentiles are different, and the Datadog `95percentile` is confusing.

- The user can only use a limited number of metrics, and most pre-aggregated ones show wrong values.

### Suggested solution

After going through the Datadog documentation, it seems it's possible to send raw data that won't be aggregated by the Datadog Agent using the distribution metric type ([1](https://docs.datadoghq.com/metrics/distributions/), [2](https://docs.datadoghq.com/metrics/types/?tab=distribution#metric-types)). This would not only avoid the aggregation, but allow users to generate any percentile value they need over the raw data.

The drawback would possibly be overloading the ingest pipeline (either of the Datadog Agent or of Datadog itself, hitting some API limits, etc.), so this needs to be thoroughly tested.

[Currently we send `Count`, `Gauge` and other metric types that will be aggregated](https://github.com/grafana/k6/blob/a2ab89abfdc8c12fa28b3d25092b2a1d9310f8c4/output/statsd/output.go#L52-L71), but the `datadog-go/statsd` client we use [also supports the `Distribution` metric](https://github.com/DataDog/datadog-go/blob/6391269270019b7fa3888a91b854a4a00d6772bd/statsd/statsd.go#L197-L198).

In addition to evaluating whether this change works for some of our metric types, we should also ensure that we don't break support for any other StatsD backends.

**Comment by imiric** [comment]
I think sending our `Trend` metric as a `Distribution` metric would also fix querying percentiles in New Relic. See the [New Relic data types documentation](https://docs.newrelic.com/docs/data-apis/understand-data/metric-data/metric-data-type/#metric-types), specifically for the `distribution` type. Notice that it supports the `percentile` and `histogram` functions, which are not supported by the other types.

Currently this is not supported, and we removed the documentation about the previously wrong query in https://github.com/grafana/k6-docs/pull/895.

**Comment by vieiraes** [comment]
waiting for a updtae about it... all % metrics are different in Datadog...

**Comment by LeonAdato** [comment]
Per [@olegbespalov](https://github.com/olegbespalov) and  [@javaducky](https://github.com/javaducky), this issue should probably be part of the StatsD project. Feel free to transfer it here: 

[https://github.com/LeonAdato/xk6-output-statsd](https://github.com/LeonAdato/xk6-output-statsd)

**Comment by olegbespalov** [comment]
Closing in favor of https://github.com/LeonAdato/xk6-output-statsd/issues/24
