### ISSUE TITLE
Exponential memory leaks in two latest versions

### ISSUE THREAD

**Issue by raykov** [grafana/k6#2836]
### Brief summary

I noticed that with two latests versions of k6 `0.41.0` & `0.42.0` it started to consume a lot of memory for no reason.

Deep investigation pointed out that this happens with http calls when url is random on each call. E.g.

```js
http.get(`http://test.k6.io?a=${randomString(10)}&c=${randomString(10)}`);
```

This will cause process to consume over 2GiB in 10 minutes with only 100 VUs

### k6 version

0.41.0 & 0.42.0

### OS

macOS

### Docker version and image (if applicable)

Docker 4.3.2, Images grafana/k6:0.41.0 & grafana/k6:0.42.0

### First experiment: http://test.k6.io
script.js

```js
import { sleep, randomSeed } from "k6";
import http from "k6/http";
import { randomString } from 'https://jslib.k6.io/k6-utils/1.4.0/index.js';

export function setup() {
    randomSeed(new Date().getTime());
}

export default function() {
    http.get(`http://test.k6.io`);

    sleep(0.5)
}

```

```bash
docker run  -e K6_STAGES="1m:100,10m:100" -v current_dir_with_script:/app   -i grafana/k6:0.41.0   run /app/test.js
```

### Second experiment: http://test.k6.io?a=b&c=d
script.js

```js
import { sleep, randomSeed } from "k6";
import http from "k6/http";
import { randomString } from 'https://jslib.k6.io/k6-utils/1.4.0/index.js';

export function setup() {
    randomSeed(new Date().getTime());
}

export default function() {
    http.get(`http://test.k6.io?a=b&c=d`);

    sleep(0.5)
}

```

```bash
docker run  -e K6_STAGES="1m:100,10m:100" -v current_dir_with_script:/app   -i grafana/k6:0.41.0   run /app/test.js
```

### Third experiment: http://test.k6.io?a=${randomString(10)}&c=${randomString(10)}

script.js

```js
import { sleep, randomSeed } from "k6";
import http from "k6/http";
import { randomString } from 'https://jslib.k6.io/k6-utils/1.4.0/index.js';

export function setup() {
    randomSeed(new Date().getTime());
}

export default function() {
    http.get(`http://test.k6.io?a=${randomString(10)}&c=${randomString(10)}`);

    sleep(0.5)
}

```

```bash
docker run  -e K6_STAGES="1m:100,10m:100" -v current_dir_with_script:/app   -i grafana/k6:0.41.0   run /app/test.js
```

Memory consumption over 3 tests, MiB
![chart](https://user-images.githubusercontent.com/133789/210278362-d1c48309-7494-48c0-ba0a-a896697688cf.png)
![Screenshot 2023-01-02 at 22 13 55](https://user-images.githubusercontent.com/133789/210278449-bc962022-8c17-414e-938b-430f0f8d13cf.png)

### First experiment: http://test.k6.io
script.js

```js
import { sleep, randomSeed } from "k6";
import http from "k6/http";
import { randomString } from 'https://jslib.k6.io/k6-utils/1.4.0/index.js';

export function setup() {
    randomSeed(new Date().getTime());
}

export default function() {
    http.get(`http://test.k6.io`);

    sleep(0.5)
}

```

```bash
docker run  -e K6_STAGES="1m:100,10m:100" -v current_dir_with_script:/app   -i grafana/k6:0.40.0   run /app/test.js
```

### Second experiment: http://test.k6.io?a=b&c=d
script.js

```js
import { sleep, randomSeed } from "k6";
import http from "k6/http";
import { randomString } from 'https://jslib.k6.io/k6-utils/1.4.0/index.js';

export function setup() {
    randomSeed(new Date().getTime());
}

export default function() {
    http.get(`http://test.k6.io?a=b&c=d`);

    sleep(0.5)
}

```

```bash
docker run  -e K6_STAGES="1m:100,10m:100" -v current_dir_with_script:/app   -i grafana/k6:0.40.0   run /app/test.js
```

### Third experiment: http://test.k6.io?a=${randomString(10)}&c=${randomString(10)}

script.js

```js
import { sleep, randomSeed } from "k6";
import http from "k6/http";
import { randomString } from 'https://jslib.k6.io/k6-utils/1.4.0/index.js';

export function setup() {
    randomSeed(new Date().getTime());
}

export default function() {
    http.get(`http://test.k6.io?a=${randomString(10)}&c=${randomString(10)}`);

    sleep(0.5)
}

```

```bash
docker run  -e K6_STAGES="1m:100,10m:100" -v current_dir_with_script:/app   -i grafana/k6:0.40.0   run /app/test.js
```

Memory consumption over 3 tests, MiB
![chart (1)](https://user-images.githubusercontent.com/133789/210279656-d573957d-10b4-43ba-986f-347e938d21b9.png)
![Screenshot 2023-01-02 at 22 39 21](https://user-images.githubusercontent.com/133789/210279663-0e2d14db-7755-4e9d-a833-3ad062e95ea5.png)

## Conclusions 

As you can see, there is no such a drastically jump in memory consumption with version 0.40.0 with random url's in get requests

ps. I also tested with v 0.42.0, situation is the same. 

### Expected behaviour

stable memory consumption around 150 MiB over the test

![Screenshot 2023-01-02 at 22 23 15](https://user-images.githubusercontent.com/133789/210278940-bbdcc286-decd-4315-baf7-c0fa414fada9.png)

### Actual behaviour

memory consumption growth exponentially over 2 GiB

![Screenshot 2023-01-02 at 22 24 04](https://user-images.githubusercontent.com/133789/210278955-9a65a340-9996-48ca-925d-3cf8bbd3d9ab.png)

**Comment by na--** [comment]
Thank you for the super-detailed issue. Unfortunately, this is a known and unavoidable side-effect of our switch to support metric time-series in [k6 v0.41.0](https://github.com/grafana/k6/releases/tag/v0.41.0) - every unique URL will now create a new time series, and thus use up a ton of RAM... :disappointed: Previously, this used to be a problem only for certain [outputs](https://k6.io/docs/results-output/real-time/), since k6 itself didn't keep track of different time series, but we now need to do it for a whole bunch of reasons. 

Fortunately, there is an easy workaround - use [URL grouping](https://k6.io/docs/using-k6/http-requests/#url-grouping). In your case, unless you want to set the `name` tag manually, the only thing that you need to change is to use the [`http.url` helper](https://k6.io/docs/javascript-api/k6-http/urlurl/) for the template literal, like this:
```js
http.get(http.url`http://test.k6.io?a=${randomString(10)}&c=${randomString(10)}`);
```

For more details, you can read up the previous discussion on the topic in https://github.com/grafana/k6/issues/2762. I'll close this issue, since https://github.com/grafana/k6-docs/issues/883, https://github.com/grafana/k6/issues/2765 and https://github.com/grafana/k6/issues/2766 track the actionable parts of it that we plan to fix.

**Comment by raykov** [comment]
Thank you @na-- for the prompt response!
