### ISSUE TITLE
Async/Await update affected k6-browser JS scripts

### ISSUE THREAD

**Issue by inancgumus** [grafana/k6#2842]
### Brief summary

As an experiment, we tried updating k6-browser to the latest async/await update in 8418147.

However, we can no longer run our [example JS tests](https://github.com/grafana/xk6-browser/tree/main/examples). Note that our examples were working with k6 v0.42.

You can see the CI output [here](https://github.com/grafana/xk6-browser/actions/runs/3875450875/jobs/6619503274).

Also see for more context: https://github.com/grafana/xk6-browser/pull/695#issuecomment-1376838090.

### k6 version

8418147

### OS

macOS 13.1 and Github CI

### Steps to reproduce the problem

1. Clone the xk6-browser repository and switch to the folder
3. Run: `xk6 build master --with github.com/grafana/xk6-browser=.`
4. Run: `./k6 run examples/launch_naked.js`

### Expected behaviour

To see the expected behavior, try running a browser script (i.e., `examples/launch_naked.js`) using k6 v0.42. We were not getting a "Not a function" error (which you can see in the actual behavior heading below) while running our example scripts with k6 v0.42.

### Actual behaviour

The following error happens when we use the k6 commit 8418147 in https://github.com/grafana/xk6-browser/pull/695:

```bash
ERRO[0000] test aborted: TypeError: Not a function: [object Object] at file:///Users/inanc/grafana/k6browser/feature/async-await-k6/examples/launch_naked.js:13:20(21)
```

Here's the full output:

```bash
$ xk6 build master --with github.com/grafana/xk6-browser=.
...
$ ./k6 run examples/launch_naked.js
running (00m00.2s), 0/1 VUs, 0 complete and 1 interrupted iterations
default ✗ [======================================] 1 VUs  00m00.2s/10m0s  1/1 iters, 1 per VU
ERRO[0000] communicating with browser: websocket: close 1006 (abnormal closure): unexpected EOF  category=cdp elapsed="0 ms" goroutine=98
ERRO[0000] process with PID 73411 unexpectedly ended: signal: killed  category=browser elapsed="0 ms" goroutine=80

     data_received........: 0 B 0 B/s
     data_sent............: 0 B 0 B/s
     iteration_duration...: avg=242.34ms min=242.34ms med=242.34ms max=242.34ms p(90)=242.34ms p(95)=242.34ms
     iterations...........: 1   4.122317/s

ERRO[0000] test aborted: TypeError: Not a function: [object Object] at file:///Users/inanc/grafana/k6browser/feature/async-await-k6/examples/launch_naked.js:13:20(21)
```

---

### Update

It seems [the xk6-browser mappings](https://github.com/grafana/xk6-browser/blob/main/browser/module.go#L25) no longer work with the latest k6 update (8418147). It was working with k6 v0.42.0. I can run the scripts when I remove the mappings. However, this still indicates a problem somewhere that we need to figure out. What might have changed on the Goja or k6-core side? 🤔

### Related

* https://github.com/grafana/xk6-browser/issues/698
* https://github.com/grafana/xk6-browser/pull/695#issuecomment-1376838090
* https://github.com/grafana/k6/issues/2842
* https://github.com/dop251/goja/issues/469
* https://github.com/grafana/xk6-browser/pull/695

**Comment by mstoykov** [comment]
I did open an [upstream bug](https://github.com/dop251/goja/issues/469) and that was fixed pretty quickly :heart:
