### ISSUE TITLE
Replace gorilla/websocket

### ISSUE THREAD

**Issue by imiric** [grafana/k6#2866]
The current WebSocket library used by both `k6/ws` and `k6/experimental/websockets` is [gorilla/websocket](https://github.com/gorilla/websocket). That repo was archived on Dec. 9, 2022, and the README shows:

> The Gorilla project has been archived, and is no longer under active maintainenance. You can read more here: https://github.com/gorilla#gorilla-toolkit

This is not urgent, as the existing version will continue to work, but it won't receive any more updates. Maybe one of the 3.2k forks will carry on, but considering we've had issues with it ourselves, we can take advantage of the experimental module and do the change there in the upcoming months, before it eventually replaces `k6/ws`.

**Comment by mstoykov** [comment]
This is kind of already tracked in https://github.com/grafana/xk6-websockets/issues/9

**Comment by codebien** [comment]
https://github.com/gorilla/websocket is back and it seems active enough so I don't evaluate it as a requirement. We can track the eventual library switch in the other issue.
