### ISSUE TITLE
Current file path is not taken into account when caching duplicate relative import paths

### ISSUE THREAD

**Issue by PieterJanVdb** [grafana/k6#2902]
### Brief summary

k6 appears to be re-using a cached import for a relative path `../fragments/index.js` wherever you use it in the code that's being used in a testrun. 

### k6 version

0.42

### OS

macOS11 / Ubuntu Linux

### Steps to reproduce the problem

Using the relative path from the brief summary, if imported first in `src/graphql/a/operations/index.js` (to indicate `src/graphql/a/fragments/index.js`) and then later in `src/graphql/b/operations/index.js` (to indicate `src/graphql/b/fragments/index.js`) it will provide me with the former import (`src/graphql/a/fragments/index.js`).

We recently updated to v0.42.0 from v0.40 (where this issue did not occur) and after some digging into any recent changes, it appears to me (though bear in mind I have next to no knowledge in Go) that is what introduced the issue: https://github.com/grafana/k6/blob/b750e206859a495b8a1fe12aa016dc8ed0e1c9db/js/initcontext.go#L109

At this point it seems to me that `../fragments/index.js` is what will serve as key in the cache, instead of the full URL (or anything that includes the file that is doing the importing).

### Expected behaviour

For the relative import to provide me with the correct file relative to whatever file it is being imported from.

### Actual behaviour

A cached import for the exact same relative path name is being returned regardless of where it is being imported from.

**Comment by mstoykov** [comment]
Thanks for reporting this :bow: 

Unfortunately you are right. That code was added to the module caching mostly for internal modules (implemented in go) as source modules (as the one you are talking about) have had separate cache for ... years. 

Unfortunately none of our tests caught this and apperantly it isn't as common to happen so  nobody else has reported for over a month of this public.

I have created a [bug fix](https://github.com/grafana/k6/pull/2903) and there is already a [PR refactoring](https://github.com/grafana/k6/pull/2881) this in a way that it is already fixed there. 

The fix will land in v0.43.0 which is slatted for release in 2 weeks. I am not certain we will be making a bugfix release for v0.42.0 given when v0.43.0 comes out, but this might change if other people report this.

The refactoring PR is likely to be merged for v0.44.0 as we are already in code freeze for v0.43.0 and it is doing quite a lot more things than simple fixing this bug :(
