### ISSUE TITLE
`k6 archive` doesn't work on windows with go1.20

### ISSUE THREAD

**Issue by codebien** [grafana/k6#2925]
After the bump of the Go version to 1.20, the Windows tests for the archive command are failing because an error is returned, so the exit code is not zero as expected.

https://github.com/grafana/k6/actions/runs/4232890600/jobs/7353760998

From a quick debug in a Windows VM, k6 or the tests generate a wrong path `\\c:test`.
![Screenshot from 2023-02-22 09-42-51](https://user-images.githubusercontent.com/2103732/220580143-f81576b5-3749-4e6d-a38d-217b0ac6d75c.png)

**Comment by mstoykov** [comment]
Seems likely this was related to the [changes](https://go.dev/doc/go1.20#minor_library_changes) to `archive/tar`: 
> When the GODEBUG=tarinsecurepath=0 environment variable is set, [Reader.Next](https://go.dev/pkg/archive/tar/#Reader.Next) method will now return the error [ErrInsecurePath](https://go.dev/pkg/archive/tar/#ErrInsecurePath) for an entry with a file name that is an absolute path, refers to a location outside the current directory, contains invalid characters, or (on Windows) is a reserved name such as NUL. A future version of Go may disable insecure paths by default.

Can we get a dump of the whole archive contents and maybe to see if other tests fail or just this one?

Also it is a bit strange that this only fails on Windows ... 

Also we technically do not have *absolute* paths inside we have them under `file` which is relative :shrug:

**Comment by imiric** [comment]
:thinking: Could this be related to https://github.com/golang/go/issues/58348 ?

**Comment by olegbespalov** [comment]
I guess @mstoykov is right. Check this out :cry: 

![VirtualBox_WinDev2301Eval_22_02_2023_13_13_43](https://user-images.githubusercontent.com/5425600/220617080-1ad24943-9fbf-4764-980a-a915734e9e13.png)

It seems like the `k6 archive` doesn't work with a binary that was built using go 1.20

The good news, tests are good :+1:
