### ISSUE TITLE
Allow isolated options configuration when running parallel scripts

### ISSUE THREAD

**Issue by pranatikolla** [grafana/k6#2944]
Hello,

I am trying to run two test scripts in parallel by calling their functions within a main script.

export { default as func01 } from './Script1.js';
export { default as func02 } from './Script2.js';

export let optionsFunc02 = {
  scenarios: {
  executor: 'constant-vus',
  gracefulStop: '10s',
  duration: '1m30s',
  vus: 1,
  exec: 'func02',
},
  insecureSkipTLSVerify: true
};

export let options = {
  scenarios: {
    'irisPages' : {
       executor: 'constant-vus',
       gracefulStop: '10s',
       duration: '1m30s',
       vus: 1,
       exec: 'func01',
     },
     'addMocks' : optionsFunc02.scenarios,
  },

  noVUConnectionReuse: true,
  noConnectionReuse: true,
  insecureSkipTLSVerify: optionsFunc02.insecureSkipTLSVerify

};

However the below three options get applied to both the scripts. I want to be able to set these differently for individual scripts just like we can for scenarios.
 noVUConnectionReuse: true,
  noConnectionReuse: true,
  insecureSkipTLSVerify: optionsFunc02.insecureSkipTLSVerify

**Comment by na--** [comment]
This is something that we can't currently do, and it's already tackled in two different issues, so I'll close this one in favor of them:
1. On the network connection side, it should be possible to specify custom HTTP (and other) clients that don't rely on the global `insecureSkipTLSVerify` / `noConnectionReuse` / `noVUConnectionReuse` / etc. options to define this behavior. This is currently tracked in https://github.com/grafana/k6/issues/2461
2. On the test execution side, it should be possible for k6 to execute multiple scripts, each with different options. This is currently tracked in https://github.com/grafana/k6/issues/1342

Also, please use the issue templates in the future, or ask your questions in the [community forum](https://community.k6.io/), not as github issues.

**Comment by pranatikolla** [comment]
Sure. I'd been asked to raise this issue here by Alex and Pawel so that they can plan and add it to the pipeline. 
Thanks for the references though and I will go through them.
