### ISSUE TITLE
Documentation for getting access tokens is missing a param setting

### ISSUE THREAD

**Issue by phil-nelson-bt** [grafana/k6#2957]
### Brief summary

There is a great article on how to fetch access tokens as part of the test initialization at https://k6.io/blog/how-to-load-test-oauth-secured-apis-with-k6/. I was able to get it adapted to my multi scenario tests but spent a lot of time trying to figure out why the response body was null even though with `--http-debug=full` I could see the token was present. The article does not include the `{  "responseType": "text" }` option that actually makes it work. Could you add that to the article?

### k6 version

v0.43.1

### OS

N/A

### Steps to reproduce the problem

Attempt to use the sample code in the article

### Expected behaviour

The sample code includes the param setting

### Actual behaviour

Sample code fails to retrieve the token with `response.json()`

**Comment by na--** [comment]
Why did you need to add `responseType: "text"`? It is the default unless you had `discardResponseBodies: true` in your script `options`? 

And `discardResponseBodies` doesn't appear in the blog examples, from what I can see :confused:

**Comment by phil-nelson-bt** [comment]
I was not setting the value to anything, wasn't aware of it at all. The default seems to be to be discardResponse bodies is what I found in other issues related to this and how I thought to try the setting in my code. And that is a reasonable default since doing checks is not the most common way of using the http code.

**Comment by na--** [comment]
I am super confused - `discardResponseBodies` is not enabled by default in k6, and it and `responseType` are not mentioned anywhere in that blog article, as far as I can see :confused:

**Comment by phil-nelson-bt** [comment]
Is this a bug with the default then? I have `responseType` set in only one place in my code and before doing that `response.json()` was failing 100% of the time with an error saying the body was null

**Comment by na--** [comment]
And have you by chance also set the [`discardResponseBodies` global script option](https://k6.io/docs/using-k6/k6-options/reference/#discard-response-bodies)?

> Is this a bug with the default then? 

No, because this k6 script works perfectly well, right?
```js
import http from 'k6/http';

export default function () {
    let resp = http.get('https://httpbin.test.k6.io/anything?foo=bar');
    console.log(resp.json())
}
```

See, I don't need `responseType: 'text'`, [because that is the default value](https://k6.io/docs/javascript-api/k6-http/params/). I'd only need to set it manually if I had specified `discardResponseBodies` in the global script `options`. In contrast to the script above, this script won't work, unless you uncomment the params:
```js
import http from 'k6/http';

export const options = {
    discardResponseBodies: true,
}

export default function () {
    let resp = http.get('https://httpbin.test.k6.io/anything?foo=bar', /* { responseType: 'text' } */);
    console.log(resp.json())
}


```

**Comment by phil-nelson-bt** [comment]
Yeah very confusing. Could it be a difference in how multiple scenario tests setup http? Here is the code I have. If I remove the `responseType` it fails 100% of the time

```
const url = `https://${oktaDomain}/oauth2/${authServerId}/v1/token`;
  const requestBody = { scope: scope };
  let response;

  requestBody['grant_type'] = 'client_credentials';

  const encodedCredentials = encoding.b64encode(`${clientId}:${clientSecret}`);
  const params = {
    auth: 'basic',
    headers: {
    Authorization: `Basic ${encodedCredentials}`,
    "Content-Type": 'application/x-www-form-urlencoded',
    },
    responseType: "text",
  };

  response = http.post(url, requestBody, params);
  return response.json();
  ```

**Comment by phil-nelson-bt** [comment]
I've confirmed by putting your sample code, with the responsBodyDiscard present and commented out and the result is the same, into my multiple scenario test. Here is the response
ERRO[0001] GoError: the body is null so we can't transform it to JSON - this likely was because of a request error getting the response
running at reflect.methodValueCall (native)
facilityat file:///Users/philnelson/Projects/tools/load-test-script/response.js:9:16(11)
k6_repsoat responsetest (file:///Users/philnelson/Projects/tools/load-test-script/combined.js:87:17(6))  executor=constant-vus scenario=k6_repsonse source=stacktrace

The scenario is setup like
`
scenarios: {
      k6_repsonse: {
        executor: 'constant-vus',
        vus: 1,
        duration: '1m',
        gracefulStop: '0s', // do not wait for iterations to finish in the end
        tags: { test_type: 'website' }, // extra tags for the metrics generated by this scenario
        exec: 'responsetest', // the function this scenario will execute
      },
      ...
      `

**Comment by phil-nelson-bt** [comment]
trying to create a complete failing example of using your sample with a scenario based test I came up with this

`import http from 'k6/http';

export const options = {

    //iterations: 1,
    scenarios: {
      k6_repsonse: {
        executor: 'constant-vus',
        vus: 1,
        duration: '1m',
        gracefulStop: '0s', // do not wait for iterations to finish in the end
        tags: { test_type: 'website' }, // extra tags for the metrics generated by this scenario
        exec: 'responsetest', // the function this scenario will execute
      },
  }
}

export function responsetest (data) {
let resp = http.get('https://httpbin.test.k6.io/anything?foo=bar', /* { responseType: 'text' } */);
console.log(resp.json())

}`

And of course it works perfectly. The only other difference I can think of is that in my real test, the http.post is in a setup function, not the actual test

**Comment by phil-nelson-bt** [comment]
Ugh! I found it. I had worked from sample code for the scenarios and in that code, while it doesn't specify responseMethod, it does set discardResponseBodies to true. The rest is history! Thanks for helping to debug this.
