### ISSUE TITLE
handleSummary() accept promise return OR synchronous redisClient

### ISSUE THREAD

**Issue by michael-sw-id** [grafana/k6#2959]
### Feature Description

Provide blocking/sync RedisClient or change handleSummary() to accept promise.

### Already existing or connected issues / PRs (optional)

We would like to use redis and handleSummary to export created customers to json during "test customer creation" run so that we can feed customers to actual load test runs.

Unfortunately:
- RedisClient is non-blocking and requires promises
- HandleSummary() cannot return a promise so we can't use async:await

Example using async:await for handleSummary (because redisclient uses promise api)
```
export const  handleSummary = async (data) => {
  let parsedCustomers = [];

  sleep(1) // for some reason need to wait for redis 
  let redisCustomers = await redisClient.smembers('created_customers')

  console.log(redisCustomers.length + " customers found in redis..")
  redisCustomers.forEach(c => {
    parsedCustomers.push(JSON.parse(c))
  });

  redisClient.del("created_customers")
  return {
    "created-customers.json": JSON.stringify(parsedCustomers),
    "customer-creation-summary.html": htmlReport(data),
    // 'stdout': textSummary(data, { indent: ' ', enableColors: true }),
  };
}
```

The above fails with
```
ERRO[0002] failed to handle the end-of-test summary      error="handleSummary() should return a map with string keys"
```

Using promises it's not possible to pass result to return:

```
export function handleSummary(data) {
  let created_customers = [];

  sleep(1) // for some reason need to wait for redis 
  redisClient.smembers('created_customers')
    .then((customers) => {
      console.log(customers.length + " customers found in redis..")
      customers.forEach(c => {
        created_customers.push(JSON.parse(c))
      });
    })
    .then((_) => {
      redisClient.del("created_customers")
    })
    return {
      'stdout' : textSummary(data, { indent: ' ', enableColors: true }),
      'customer-creation-summary.html': htmlReport(data),
      'created-customers.json': JSON.stringify(created_customers)
    };
}
```

**Comment by michael-sw-id** [comment]
it worked, thanks

```
export function handleSummary(data) {
  let result = {
    'stdout': textSummary(data, { indent: ' ', enableColors: true }),
    "customer-creation-summary.html": htmlReport(data),
  };
  getCreatedCustomersAsync(result).then(
    (customers) => (result["created-customers.json"] = JSON.stringify(customers))
  );
  return result;
}


export const  getCreatedCustomersAsync = async () => {
  let parsedCustomers = [];

  sleep(1) // for some reason need to wait for redis 
  let redisCustomers = await redisClient.smembers('created_customers')

  console.log(redisCustomers.length + " customers found in redis..")
  redisCustomers.forEach(c => {
    parsedCustomers.push(JSON.parse(c))
  });

  redisClient.del("created_customers")
  return parsedCustomers;
}

```

**Comment by michael-sw-id** [comment]
> I will probably be fixing both of them for v0.44.0

@mstoykov another potential use case for async await could be SharedArray. e.g. to load data from redis

**Comment by stewardor** [comment]
`export function handleSummary(data: any) {
  let result: any = {};
  let reportDate = moment().format('YYYY-MM-DD hh-mm-ss');

  result['stdout'] = textSummary(data);
  result['reports/customer-creation-report-' + reportDate + '.html'] = htmlReport(data);

  getCreatedCustomersAsync().then(
    (customers) => (result['data/created-customers-' + reportDate + '.json'] = JSON.stringify(customers, null, 2))
  );

  return result;
}

const getCreatedCustomersAsync = async () => {
  let parsedCustomers: any = [];

  sleep(1) // for some reason need to wait for redis 
  let redisCustomers = await redisClient.smembers('created_customers');

  console.log(redisCustomers.length + " customers found in redis..");
  redisCustomers.forEach(c => {
    parsedCustomers.push(JSON.parse(c))
  });

  redisClient.del(["created_customers"]);
  return parsedCustomers;
}`

I have my k6 project written in typescript through this template and it seems like after webpack translation from ts to js, it's still throwing the Uncaught (in promise) error.

`ERRO[0001] Uncaught (in promise) unsupported type provided for argument at index 1, supported types are string, number, and boolean  executor=per-vu-iterations scenario=contacts`

Any possible work around for typescript?

**Comment by mstoykov** [comment]
@stewardor what you are seeing is an exception due to coding error. 

Looking at your code I can't figure out which line this is from (I would expect this is not the exact code given that), but this errors definitely comes from the experimental redis module. 

Do you not have a stack attached to it as that will be a separate issue :thinking:

**Comment by michael-sw-id** [comment]
@mstoykov the issue is that sadd() method signature exoects any[] for members argument, so TS forced us to pass an array.

The same method later complains at runtime it should be string, number or boolean.
