### ISSUE TITLE
influxdb docker compose setup datasource seems broken

### ISSUE THREAD

**Issue by kdelee** [grafana/k6#2969]
### Brief summary

I followed https://k6.io/docs/results-output/real-time/influxdb-grafana/ to setup grafana+influxDB

The dashboard has the error:
![image](https://user-images.githubusercontent.com/29239279/224162791-d40d042b-a2ee-46fb-8caa-379469cc02a9.png)

And when I looked at the datasource it also had an error saying no databse was provided.

I made an identical datasource except I specified "myk6db" as the "database" and it started to pull in the data.

### k6 version

master

### OS

fedora

### Steps to reproduce the problem

git clone 'https://github.com/grafana/k6'
cd k6
docker-compose up -d \
    influxdb \
    grafana
docker-compose run -v \
    $PWD/samples:/scripts \
    k6 run /scripts/es6sample.js

follow docs from https://k6.io/docs/results-output/real-time/influxdb-grafana/

### Expected behaviour

datasource works

### Actual behaviour

missing config, and because its a file provisioned datasource not editable from UI

**Comment by mstoykov** [comment]
It should work after I pinned the version in #2970, but I will leave this open until we actually decide whether we will move this or fix it to work with latest grafana versions.

**Comment by itsmylife** [comment]
@mstoykov @kdelee This issue is fixed in https://github.com/grafana/grafana/pull/62790
In the next release of grafana `v9.5.0` it will be fixed. 
@zoltanbedi Do you think we should backport your change to `v9.4.x`?

**Comment by zoltanbedi** [comment]
@itsmylife I've backported it to 9.4.

**Comment by itsmylife** [comment]
@mstoykov Please advise if we should close this issue since the fix is known and backported to `v9.4.x`

**Comment by mstoykov** [comment]
But good job on quick find and backport :clap: :hand:

**Comment by imiric** [comment]
Thanks for the quick fixes! :bow:

I would actually prefer it if we kept the `grafana` image version pinned in the Compose file. We want to have a stable and working setup by default, and version pinning is usually a good idea. We do so for the `influxdb` image, though we should probably switch to Prometheus now.

Are we still planning to move this file to a separate repo? Maybe we should take the opportunity to do this now, and discuss any stack changes there.

**Comment by itsmylife** [comment]
@mstoykov @imiric 
Then I think my job here is done :) I am gonna deassign myself. If you think I should still be the assignee feel free to assign it to me.

**Comment by codebien** [comment]
This is fixed we can close.

>Are we still planning to move this file to a separate repo? Maybe we should take the opportunity to do this now, and discuss any stack changes there.

If we want it then we should open a dedicated issue.
