### ISSUE TITLE
Publish `loadimpact/k6` Docker image with a deprecation warning

### ISSUE THREAD

**Issue by imiric** [grafana/k6#2979]
Given that [Docker Hub is sunsetting Free Team organizations](https://www.docker.com/blog/we-apologize-we-did-a-terrible-job-announcing-the-end-of-docker-free-teams/) effective April 14th, 2023, we need to deprecate our [loadimpact/k6 image](https://hub.docker.com/r/loadimpact/k6/), which is on that tier.

Our plan is to continue to support it for at most a year from now, but we need to add a deprecation warning to it pointing users to the [grafana/k6 image](https://hub.docker.com/r/grafana/k6/) instead.

This can be done with an entrypoint script that wraps k6, and prints a warning before running. A few months before the end of that year period, tentatively towards the end of 2023, the entrypoint script will additionally start returning a non-zero exit code as well.

**Comment by imiric** [comment]
This is no longer a high priority since [Docker backtracked their decision](https://www.docker.com/blog/no-longer-sunsetting-the-free-team-plan/) :roll_eyes:, but we should still do this regardless, since we're not Load Impact anymore.

**Comment by andrewslotin** [comment]
Closed by https://github.com/grafana/k6/pull/3121
