### ISSUE TITLE
HTTP methods are wrongly overwritten in the tracing instrumented client

### ISSUE THREAD

**Issue by marcin-maciej-seweryn** [grafana/k6#2983]
### Brief summary

Tracing instrumentation wrongly overwrites HTTP methods in the client and assigns `PATCH` method to both `POST` and `PUT` requests.

### k6 version

0.43

### OS

all

### Steps to reproduce the problem

1. Instrument code with `tracing.instrumentHTTP`
2. Call `http.post` or `http.put`

### Expected behaviour

Instrumented tracing HTTP client sends:
* a `POST` request when `http.post` is invoked
* a `PUT` request when `http.put` is invoked

### Actual behaviour

Methods `http.post` and `http.put` methods after calling `tracing.instrumentHTTP` send HTTP `PATCH` request.
I'm not familiar with k6 code base but these [two lines](https://github.com/grafana/k6/blob/12f5dd846338d251b5d7702111b3a3533d3e0dc6/js/modules/k6/experimental/tracing/module.go#L155-L156) seem to be a reason for this behavior.

If you agree that these two lines are causing this issue, I'll be happy to provide a fix.

**Comment by na--** [comment]
Thanks for reporting this, it indeed looks like a copy-paste bug :disappointed:
