### ISSUE TITLE
ReferenceError: response is not defined

### ISSUE THREAD

**Issue by mikocot** [grafana/k6#2996]
### Brief summary

http.post returning undefined object as result

### k6 version

0.43.1

### OS

linux, github-actions

### Steps to reproduce the problem

We're running k6 tests in github actions, using https://github.com/grafana/k6-action v2 and therefore using the latest version of k6.

Some of our tests, always the same cases, fail in an unexpected way, reporting only:
> ✗ Exception raised "ReferenceError: response is not defined"

Based on the documentation there is no case in which response (`http.post`) should be null or especially undefined. Also this happens only during some of the runs, in the other all the checks pass successfully.

The case is specified as:

```
var baseUrl = __ENV.MGMT_URL;
var params = {
  headers: { 'Content-Type': 'application/json', },
  timeout: '180s'
};

 describe('Manage Destination', () => {
    let tenant = getTenant();
    
    let payload = JSON.stringify({
      "name": qaTempDestination + Math.floor(Math.random() * 1000)
    });
    
    let basePathUrl = baseUrl + "/tenant/" + tenant.tenantId + "/destination";
    
    let response = http.post(basePathUrl, payload, params);    
    expect(response.status, 'CREATE response status ' + response.status).to.equal(201);

    let entityId = JSON.parse(response.body).destinationId;    
    let extPathUrl = basePathUrl + "/" + entityId;

    describe('Get destination by id', () => {
      response = http.get(extPathUrl);
      expect(response.status, 'response status ' + response.status).to.equal(200);
      expect(response.body, 'response body').to.include(entityId);
    })
    [...]
```

imports are as follows:
```
import http from 'k6/http';
import { sleep } from 'k6';
import { describe, expect } from 'https://jslib.k6.io/k6chaijs/4.3.4.2/index.js';
```

Since no checks are reported I assume the exception happened at top level and not in one of the further describes, but I'm not 100% sure how exception handling works. All the cases look similar, though and response is always assigned to a result of http.post / get / del

Below a failed and successful run
![image](https://user-images.githubusercontent.com/9884950/229073712-dda10331-9d59-45db-a566-e5a1e4c23423.png)
![image](https://user-images.githubusercontent.com/9884950/229073922-29b0bf67-0c6b-459a-b1b4-e0f58b3acde0.png)

### Expected behaviour

response is not null, tests passing

### Actual behaviour

exception thrown when trying to read response, tests failing most of the time

**Comment by mstoykov** [comment]
Hi @mikocot, thanks for reporting this :bow:

I can't reproduce it locally and looking at the code and the output, the body of `Manage Rule` and stuff around it is actually the interesting part.

It will be really beneficial if you can provide an example that is small as possible and if you can use `https://httpbin.test.k6.io` as the end point that will also help us with debugging. As well as with you not sharing too much info that might be confidential otherwise.

**Comment by mikocot** [comment]
> Hi @mikocot, thanks for reporting this 🙇
> 
> I can't reproduce it locally and looking at the code and the output, the body of `Manage Rule` and stuff around it is actually the interesting part.
> 
> It will be really beneficial if you can provide an example that is small as possible and if you can use `https://httpbin.test.k6.io` as the end point that will also help us with debugging. As well as with you not sharing too much info that might be confidential otherwise.

We also couldn't replicate it locally, and only once a while in CI/CD so it was hard to find, finally a fresh look at the some code a day or two later made us realize we have an issue in our own code, it only happened ocassionally as it was hidden in the retry logic that we've added. 

At the same time, the real missing point was any kind of stack trace or number of line throwing exception. Having such we'd have a solution within minutes. Is there any way to get it?

**Comment by na--** [comment]
Generally there should be proper stack traces for k6 JS exceptions... :thinking: Maybe k6chaijs silences them? Please create an issue in https://github.com/grafana/k6-jslib-k6chaijs, if that turns out to be the problem.
