### ISSUE TITLE
Redis Hset cannot use string as value parameter

### ISSUE THREAD

**Issue by deejiw** [grafana/k6#3003]
### Brief summary

Cannot use string for value via `hset(key, field, value)` function. Must use literal string to bypass the error.

redisClient.hset('foo', 'firstname', `${firstname}`)

### k6 version

0.43.1

### OS

Linux

### Steps to reproduce the problem

```
const firstname = bar
redisClient.hset('foo', 'firstname', firstname)
```

### Expected behaviour

Successfully SET `firstname` field of `foo` key as `bar`

### Actual behaviour

return 0 but the `firstname` field failed to SET.

**Comment by oleiade** [comment]
Hi @deejiw, thanks for reporting this 👋🏻 

I was, unfortunately, unable to reproduce the issue you reported. Could you please share which version of k6 and redis you are using to help us reproduce it?  If possible, could you also share some example script that demonstrates the issue happening on your side?

Here's the sample code I've used to try and reproduce your issue, based on what I understood from the description you've given:

```javascript
import redis from 'k6/experimental/redis';

// Get the redis instance(s) address and password from the environment
const redis_addrs = __ENV.REDIS_ADDRS || '';
const redis_password = __ENV.REDIS_PASSWORD || '';

// Instantiate a new redis client
const redisClient = new redis.Client({
  addrs: redis_addrs.split(',') || new Array('localhost:6379'), // in the form of 'host:port', separated by commas
  password: redis_password,
});

export default async function () {
    const firstname = 'babar';
    
    try {
        await redisClient.hset('myhash', 'myfield', firstname);
    } catch (e) {
        console.log(JSON.stringify(e));
    }
}
```

After running this script, redis reports the `myhash.myfield` set correctly holding the `babar` value. 

```
127.0.0.1:6379> HGET myhash myfield
"babar"
```

Thanks for your help 🤝

**Comment by deejiw** [comment]
I did switch back to variable and it is working. Closing the issue as there is no bug as previously reported. Thank you all for clarifying this 👍🏻
