### ISSUE TITLE
K6 problem with AzureB2C AAD token

### ISSUE THREAD

**Issue by PassionateDeveloper86** [grafana/k6#3074]
### Brief summary

I want to get a token for my gRPC calls with k6. 
I allready implenented K6 successfully with my gRPC in Azure Cloud with an anonymous call, but got stuck on the token-task.

### k6 version

latest

### OS

w11

### Steps to reproduce the problem

I want to get a token for my gRPC calls with k6. 
I allready implenented K6 successfully with my gRPC in Azure Cloud with an anonymous call, but got stuck on the token-task.

I am using this example to get my gRPC running:
https://k6.io/blog/performance-testing-grpc-services/
Which works fine for me, this is my script which works:
https://pastebin.com/Bjg6Rmyi
https://imgur.com/a/APSUeh2

Now my main goal is, as said, to go against our secured gRPC endpoints.
For that we have an acure b2c AAD service.

Within Postman it works like this:
![grafik](https://github.com/grafana/k6/assets/20551244/3b8ffea9-f61d-4bca-a38d-842782375d2f)

So I go to this address:
https://[AzureB2CName].b2clogin.com/[AzureB2CName]onmicrosoft.com/[Policy]/oauth2/v2.0/authorize

I get a token with this request and use this later as Bearer in the header - which works fine.

Within K6 I found this example::
https://k6.io/docs/examples/oauth-authentication/

I used this so my code is like this:
(Azure.js) https://pastebin.com/P3eMLxSx
(Test itself) https://pastebin.com/HjeAuuiz

At first I got a few errors, which I solved thorugh settings in Azure B2C, now I have the following bug which I have no idea about meaning or how to solve:
_INFO[0001] {"error":"server_error","error_description":"AADB2C90108: The orchestration step '1' does not specify a CpimIssuerTechnicalProfileReferenceId when one was expected.\r\nCorrelation ID: 72c0033a-04de-4b43-be24-7bd477eb40a3\r\nTimestamp: 2023-05-17 07:45:31Z\r\n"}  source=console
INFO[0001] {"error":{"code":"InvalidAuthenticationToken","message":"CompactToken parsing failed with error code: 80049217","innerError":{"date":"2023-05-17T07:45:31","request-id":"773832f0-8cea-43a1-9015-85ba4d31bd4b","client-request-id":"773832f0-8cea-43a1-9015-85ba4d31bd4b"}}}  source=console_

### Expected behaviour

Get the Token

### Actual behaviour

Error:
INFO[0001] {"error":"server_error","error_description":"AADB2C90108: The orchestration step '1' does not specify a CpimIssuerTechnicalProfileReferenceId when one was expected.\r\nCorrelation ID: 72c0033a-04de-4b43-be24-7bd477eb40a3\r\nTimestamp: 2023-05-17 07:45:31Z\r\n"}  source=console
INFO[0001] {"error":{"code":"InvalidAuthenticationToken","message":"CompactToken parsing failed with error code: 80049217","innerError":{"date":"2023-05-17T07:45:31","request-id":"773832f0-8cea-43a1-9015-85ba4d31bd4b","client-request-id":"773832f0-8cea-43a1-9015-85ba4d31bd4b"}}}  source=console

**Comment by imiric** [comment]
Hi,

what makes you think this is a k6 bug? That error is coming from Azure's API, and we can't help you with that here.

Looking at your test script, you have 2 returns in your `setup()` function, where the second is unreachable, and the gRPC code is commented out, so this is failing to get a token using HTTP. I don't see how this could be a k6 bug, and don't see anything obviously wrong with your script.

If you need help with writing k6 scripts, I suggest you post on the [community forum](https://community.k6.io/). And if you need help with the Azure API, try an Azure forum instead.

**Comment by imiric** [comment]
The OAuth examples in the documentation are for illustrative purposes, and if they don't work as expected, then you should open an issue in https://github.com/grafana/k6-docs/ so we can update them. Or better yet, open a PR to fix them. :)

But this doesn't mean that there's an issue with k6 or the `k6/http` module. It's likely that something changed on the Azure side and we just need to update the examples. I see you've changed the URLs in your script, which may or may not be related.

Unfortunately, I don't have an Azure account to test this, so yours, or anyone else's help is appreciated.
