### ISSUE TITLE
Expose test lifecycle step

### ISSUE THREAD

**Issue by jade-lucas** [grafana/k6#3090]
### Feature Description

Currently, it appears that init context code gets executed on every life cycle step. This is not ideal for cases where you load large blobs of data (like pdfs) in the init context as the current documentation suggests. Also not ideal if you do any db or connection establishing as you would establish many connections. Then how would you keep track of all those connection and properly tear those connection down?

To help address this duplicate initialization, could k6 expose some property that would tell what lifecycle step that it was on? Then we can have logic to only load files on the VU initialization. 

Here is a snippet of my logs. From these logs I can see that I am loading my test pdfs multiple times from the init context.
![image](https://github.com/grafana/k6/assets/14896787/1c9bd3a8-9221-4c87-9b31-431825eabd8c)

### Suggested Solution (optional)

Expose a property that would reflect what lifecycle stage k6 was in. Perhaps something in k6/execution could export something reflecting the lifecycle stage. 

Something like this?
![image](https://github.com/grafana/k6/assets/14896787/9668dd61-4c6e-4889-9ca5-0e9fa93b71ae)

**Comment by jade-lucas** [comment]
Thanks for the thorough response @mstoykov . I mostly follow what you are saying. As mentioned, there appears to be some really beneficial enhancements coming soon with file handling that will make this mute. I am looking forward to those enhancements.

I guess I was just calling attention to that the "init" code gets called multiple times. It perhaps to me at first feels unnatural that your "init" is executed multiple times, even so just for 1 VU and 1 iteration. I typically think of init being called once per instance. When I saw my log output, I thought I was doing something wrong. But your explanation outlines the reasons for this, so it just a matter of understanding on my end.

**Comment by mstoykov** [comment]
I am closing this now - it seems like all questions have been answered
