### ISSUE TITLE
Local module -- export default does not work

### ISSUE THREAD

**Issue by mason-liu** [grafana/k6#3091]
### Brief summary

For local module, export function blabla() is working well, but export **default** function blabla() is not

### k6 version

0.44.1

### OS

macOS 13

### Steps to reproduce the problem

//helpers.js
export default function someHelper() {
  // ...
}

//my-test.js
import { someHelper } from './helpers.js';

export default function () {
  someHelper();
}

k6 run my-test.js

### Expected behaviour

Should run without error

### Actual behaviour

Got error message:
ERRO[0000] TypeError: Value is not an object: undefined
	at file:///**/my-test.js:5:2(4)  executor=per-vu-iterations scenario=default source=stacktrace

**Comment by mstoykov** [comment]
Hi @mason-liu, 
```javascript
export default function someHelper() {
```
This line exports *only* a `default` binding. The fact that in the module the function `someHelper` is also defined does not mean it is exported with the name `someHelper. That can be done if you drop the `default` or if you define it and then export as default as well.

``` javascript
export function someHelper() { ...}
export default someHelper
```

So to use your current code you just need to import the *default* binding not a named one.
```javascript
import someHelper from './helpers.js';
```
The Identifier of the default binding does not need to be `someHelper`. If you are going to be having more helpers (as the name suggests) it is likely better to have them only named.

Some doc links:
- [table](https://2ality.com/2015/07/es6-module-exports.html#exporting-bindings) of how exports work, among a much bigger and in depth explanations of modules
- MDN export [docs](https://developer.mozilla.org/en-US/docs/web/javascript/reference/statements/export)
