### ISSUE TITLE
Help to generate encrypted payload from username and password support to CryptoJs

### ISSUE THREAD

**Issue by TestwinPlay** [grafana/k6#3124]
### Feature Description

I want to load test the auth api for our back end but we are generating encrypted string from username and passing using below code. I need to know k6 support this scenario
```javascript
function aesCbcEncrypt(message, random)  {
    const key = 'BF1C6D7727' + random;
    const iv = '961E9031E2CAD84A';

    const keyHex = CryptoJS.enc.Utf8.parse(key);
    const ivHex = CryptoJS.enc.Utf8.parse(iv);
    const messageHex = CryptoJS.enc.Utf8.parse(message);
    const encrypted = CryptoJS.AES.encrypt(messageHex, keyHex, {
      iv: ivHex,
      mode: CryptoJS.mode.CBC,
      padding: CryptoJS.pad.Pkcs7
    });
    return encrypted.toString();
 }

const random = Math.floor(100000 + Math.random() * 900000);
pm.environment.set("auth-random", random);
var username = pm.environment.get("username");
var password = pm.environment.get("password");
var user = {username:username, password:password};
pm.environment.set("auth-payload", aesCbcEncrypt(JSON.stringify(user), random));
console.log(pm.environment.get("auth-payload"))
```

**Comment by mstoykov** [comment]
Hi @TestwinPlay, 

You could've probably tried it for yourself, but the following code 

```javascript
import CryptoJS from "https://unpkg.com/crypto-js@3.1.9-1/crypto-js.js";

function aesCbcEncrypt(message, random) {
	const key = "BF1C6D7727" + random;
	const iv = "961E9031E2CAD84A";

	const keyHex = CryptoJS.enc.Utf8.parse(key);
	const ivHex = CryptoJS.enc.Utf8.parse(iv);
	const messageHex = CryptoJS.enc.Utf8.parse(message);
	const encrypted = CryptoJS.AES.encrypt(messageHex, keyHex, {
		iv: ivHex,
		mode: CryptoJS.mode.CBC,
		padding: CryptoJS.pad.Pkcs7,
	});
	return encrypted.toString();
}

export default () => {
	const random = Math.floor(100000 + Math.random() * 900000);
	var user = { username: "some username", password: "a password" };
	console.log(aesCbcEncrypt(JSON.stringify(user), random));
};
```

Produces a result that looks okay. I just happen to not be using what looks like the postman-to-k6 converter.

Also of note is that k6 now implements *parts* of the [WebCrypto API](https://developer.mozilla.org/en-US/docs/Web/API/Web_Crypto_API) under the [`k6/experimental/webcrypto`](https://k6.io/docs/javascript-api/k6-experimental/webcrypto/) module which likely will have better performance, but will need to have different code that I can't provide.

What is currently supported can be seen in the [upstream project](https://github.com/grafana/xk6-webcrypto/).

As this is not a feature request or a bug  report, I would recommend that any future usage questions are asked in the [community forum](https://community.k6.io/).
