### ISSUE TITLE
Warn and discard any label equal to the reserved

### ISSUE THREAD

**Issue by codebien** [grafana/k6#3155]
# What?

Figure out what reserved labels are and discard their usage with a warning.

# Why?

Labels like `__name__` and `test_run_id` are labels used by the k6 cloud backend, so if a test defines a set of tags that contains one of them, it will generate a conflict.

**Comment by mstoykov** [comment]
Wouldn't it make more sense to just not have those as labels?

**Comment by olegbespalov** [comment]
> Wouldn't it make more sense to just not have those as labels?

@mstoykov could you please elaborate? Do you mean pre-set them?
