### ISSUE TITLE
k6 experimental websocket does not work together with k6 http protocol

### ISSUE THREAD

**Issue by sumitbhowmick** [grafana/k6#3215]
### Brief summary

Summary: k6 experimental websocket does not work together with k6 http protocol. The two protocols when put in same script, block each other and does not work in parallel. After code of one protocol finishes, code of another protocol gets executed.
This is especially true, when the majority of the script uses http protocol where websocket protocol code is expected to work in the background providing event updates in parallel.

I am working on a k6 script where a series of REST API calls will be made along with a websocket endpoint connection. The websocket endpoint publishes latest data asynchronously from time to time.
The REST API calls will utilise the latest data available from the websocket.

I have created a sample script but I observe that k6 REST API calls block the websocket connection till all REST API calls are not complete.
Is it possible to work with REST API calls, while keeping websocket connection active and work with latest data available from the socket?

The below code uses a loop intended to replicate the situation created by series of REST API calls.
Use of experimental timers (though inappropriate as per real life example) in place of sleep does not help address this problem.

```
import { WebSocket } from 'k6/experimental/websockets';
import http from 'k6/http';
import { sleep } from 'k6';

export default function () {  
  let ws
  init(ws)

  for(let i=0;i<10;i++){
    const response = http.get("https://test-api.k6.io/public/crocodiles/");
    console.log(`Attempt ${i}: `,response.body)
    sleep(10)
  }  
}

function init(ws) {
  if (ws) {
    ws.onerror = ws.onopen = ws.onclose = null;
    ws.close();
  }

  ws = new WebSocket(`wss://test-api.k6.io/ws/crocochat/publicRoom/`);
  ws.onopen = () => {
    console.log('WebSocket connection established!');
    ws.send(JSON.stringify({ event: 'SET_NAME', new_name: `Croc 6575:997` }));
    console.log('Websocket message sent')
  }

  ws.onmessage = (data) => {
    console.log(`a message received: ${JSON.stringify(data)}`);
  };

  ws.onclose = function() {
    ws = null;
  }
}
```
Response to this script is below:
```
INFO[0000] Attempt 0:  ......
INFO[0011] Attempt 1:  ......
....
....
....
INFO[0083] Attempt 8:  ......
INFO[0093] Attempt 9:  ...
INFO[0103] WebSocket connection established!             source=console
INFO[0103] Websocket message sent                        source=console                                                                                                      
INFO[0103] a message received: {"type":"message","target":{"url":"wss://test-api.k6.io/ws/crocochat/publicRoom/","readyState":1,"bufferedAmount":0,"binaryType":"ArrayBuffer"},"timestamp":1689744005564.149,"data":"{\"type\": \"send_message\", \"room\": \"publicRoom\", \"message\": \"anonymous joined\", \"user\": \"anonymous\", \"event\": \"USER_JOINED\"}","origin":"wss://test-api.k6.io/ws/crocochat/publicRoom/"}  source=console                                                                                         
INFO[0103] a message received: {"type":"message","target":{"url":"wss://test-api.k6.io/ws/crocochat/publicRoom/","readyState":1,"bufferedAmount":0,"binaryType":"ArrayBuffer"},"timestamp":1689744108150.6484,"data":"{\"type\": \"send_message\", \"event\": \"NAME_CHANGE\", \"room\": \"publicRoom\", \"user\": \"Croc 6575:997\", \"message\": \"User anonymous changed name to 'Croc 6575:997'\"}","origin":"wss://test-api.k6.io/ws/crocochat/publicRoom/"}  source=console
```

Reference: https://community.k6.io/t/websocket-and-rest-not-working-in-sync-together/7499

### k6 version

v0.44.1

### OS

Windows 11

### Steps to reproduce the problem

Develop a script using k6 https calls and k6 websocket calls both working in parallel. HTTP calls are expected to be executed in sequence. websocket code is expected to work on events.

### Expected behaviour

HTTP calls are expected to be executed in sequence as usual.
Websocket code is expected to work on events. Both are expected to work in parallel as per the script design.
Websocket code once executed, should release control to http protocol code, should maintain connection with server & listen to async updates and perform async operations as defined. These async operations are expected to be performed irrespective of sync operations. Ideally there should be a way to exchange state & control between these two protocols.

### Actual behaviour

At present, k6 experimental websocket does not work together with k6 http protocol. The two protocols when put in same script, block each other and does not work in parallel. After code of http protocol finishes, code of websocket protocol gets executed.
This is especially true, when the majority of the script uses http protocol and websocket protocol code is expected to work in the background providing event updates in parallel.

**Comment by oleiade** [comment]
Hey @sumitbhowmick 

I believe the reason for it is because you are using the blocking/synchronous HTTP API. I suggest you try switching to the `http.asyncRequest` function instead of `http.get` in this instance, which will allow k6 to perform actions asynchronously and concurrently in that instance.

```javascript
import { WebSocket } from 'k6/experimental/websockets';
import http from 'k6/http';
import { sleep } from 'k6';

// Note that we declare the default function as `async` here
export default async function () {  
  let ws
  init(ws)

  for(let i=0;i<10;i++){
    // Here we await the asynchronous http request 
    const response = await http.asyncRequest("GET", "https://test-api.k6.io/public/crocodiles/");
    console.log(`Attempt ${i}: `,response.body)
    sleep(10)
  }  
}

function init(ws) {
  // Unchanged
}
```

**Comment by codebien** [comment]
Closing as it doesn't seem to be an issue. But feel free to reopen reporting more details if any.
