### ISSUE TITLE
K6_CLOUD_TOKEN environment variable accepts whitespace

### ISSUE THREAD

**Issue by jalevin** [grafana/k6#3240]
### Brief summary

When using the golang cmd.Exec package, I can sneak whitespace into the environment variable for K6_CLOUD_TOKEN. The error produced also does not tell me about the whitespace.

### k6 version

k6 v0.43.1

### OS

darwin/arm64 12.6.3

### Steps to reproduce the problem

While writing a script to automate executing k6 tests, I am reading in the token from a file on disc and passing that in as an environment variable when executing the tests. e.g `K6_CLOUD_TOKEN=foo k6 mytest.js -o cloud`

If I were to paste that into a normal shell, it works fine, however, I'm using the golang cmd.Exec package where I set the environment variables and the command and then exec it. 

```go
cmd := exec.Command("k6", "mytest.js", "-o", "cloud")
	cmd.Env = append(os.Environ(),"K6_CLOUD_TOKEN=foo\n")
        stdoutStderr, err := cmd.CombinedOutput()
	if err != nil {
		log.Fatal(err)
	}
	fmt.Printf("%s\n", stdoutStderr)
```

which results in

`time="2023-07-31T11:52:32-08:00" level=debug msg="Everything has finished, exiting k6 with an error!" error="Post \"https://ingest.k6.io/v1/tests\": net/http: invalid header field value for \"Authorization\""`

In the k6 test, I added a debug statement underneath the imports (not in any lifecycle functions) `console.log(__ENV.K6_CLOUD_TOKEN)` which resulted in: `foo\n`.

The extra `\n` is definitely happening on my side in Go and I am now trimming whitespace on the variable, however, it might be worth doing that on k6 or adding a warning about invalid format.

### Expected behaviour

K6 should trim whitespace from the K6_CLOUD_TOKEN environment variable

### Actual behaviour

k6 leaves the whitespace in the K6_CLOUD_TOKEN environment variable

**Comment by mstoykov** [comment]
Hi @jalevin, thanks for reporting this :bow: 

I am not against there being *some* sanitizing. 

But looking at this I can imagine someone needing this as they use an env variable as an argument to something and a new line is expected at the end.

I can only imagine that this happened because when you were cutting the original data you use something that didn't remove `\n` from the end while cutting on newlines? Instead of specifically adding it?

**Comment by mstoykov** [comment]
I am closing this as this is unlikely and as I explained there are cases where this *can* be useful for other cases. 

Having special treatment for one env variables seems too much work for a problem which looks to be usage one.
