### ISSUE TITLE
add metadata to reflection in grpc

### ISSUE THREAD

**Issue by gubtos** [grafana/k6#3241]
### Feature Description

Reflection call on grpc Connect don`t support metadata.

https://github.com/grafana/k6/blob/master/js/modules/k6/grpc/client.go#L263

Current params parsing

https://github.com/grafana/k6/blob/master/js/modules/k6/grpc/client.go#L495-L583

### Suggested Solution (optional)

Add to reflection context the metadata from params argument

**Comment by olegbespalov** [comment]
Would it be helpful to introduce the GRPC connection's default metadata, which could be automatically passed by default to the places that support metadata (unary's invoke, stream's, reflection calls)? In case of the presence of in-line metadata, they should have priority.

@grafana/k6-core, what do you think?
