### ISSUE TITLE
Exception in `handleSummary()` do not have a stack

### ISSUE THREAD

**Issue by mstoykov** [grafana/k6#3257]
### Brief summary

Exceptions in handleSummary do not print stack, just a message that there was an exception. 

This makes debugging it way harder than it should

### k6 version

v0.45.1

### OS

linux

### Steps to reproduce the problem

```javascript
export default () => { };
export function handleSummary() {
        throw "here";
}
```

### Expected behaviour

```
ERRO[0000] here
        at handleSummary (file:///home/mstoykov/work/k6io/k6/handlesummary.js:3:1(2))  hint="script exception"
```

### Actual behaviour

```
ERRO[0000] handleSummary() failed with error "here", falling back to the default summary  source=console
```

**Comment by Azanul** [comment]
May I take this up?

**Comment by mstoykov** [comment]
@Azanul you are welcome to do so :+1: and sorry for the slow reply
