### ISSUE TITLE
k6 browser recorder dosnt work

### ISSUE THREAD

**Issue by AchimGrolimund** [grafana/k6#3277]
### Brief summary

The Grafana k6 Browser Recorder [1.0.1] stops recording and switches to grafana to save the recording.
"See video"

https://github.com/grafana/k6/assets/22026079/9ab94131-873c-48b6-89d8-94f65db74bbe

Chrome: Version 115.0.5790.171 (Offizieller Build) (64-Bit)
Grafana k6 Browser Recorder: 1.0.1
ID: fbanjfonbcedhifbgikmjelkkckhhidl

### k6 version

0.45.1

### OS

Windows 11 Enterprise, build: 22000.2295

### Steps to reproduce the problem

1. goto https://test.k6.io/
2. start recording
3. click on ("GET+POST | /my_messages.php | Login form + authenticated page")
4. try to login

### Expected behaviour

it is to be expected that the recorder records the "clicks" and only wants to create the script in grafana cloud when the recording is stopped.

### Actual behaviour

Currently the recoring stops as soon as I want to log in on the test page and also on other pages.

**Comment by legander** [comment]
Hey @AchimGrolimund and thanks for reporting this. I can see in the screen recording that you have the 1password browser extension installed and enabled. It is a know issue that the 1password extension interferes and stops recordings when focusing a HTML form, try temporarily disabling the extension before starting a recording and see if that helps.

**Comment by AchimGrolimund** [comment]
Hey @legander 
You were absolutely right. I have disabled 1Password (browser plugin) and now the recording works.

Thanks a lot!
