### ISSUE TITLE
Remove trying to load remote modules by prepending `https://` 

### ISSUE THREAD

**Issue by mstoykov** [grafana/k6#3287]
## What?

if currently we get module name "something" k6 will try to load it as `https://` + `something` in case it is a URL without a schema, which used to be the only way to load urls more than 4 years ago.

This is mostly confusing users when they make mistake with importing something instead of actually helping.

## History

This functionality dates back to before my involvement with the project and in one of my first big rewrite #1046 it was left as backwards compatibility. Especially as that PR also let users actually prepend `https://` infront of modules specifiers which made them more consistent and obvious. 

## Solution
Given that it has been 4 years - I am for dropping this functionality. I very much doubt anyone still uses that, and if they do they have been seeing the message all of this time.

We can also change the message to us actually deprecating it one release and removing it a few releases later, to be more consistent and to not break someone script. Although again I really doubt anyone has been using this with this message constantly logging.

**Comment by olegbespalov** [comment]
Let's go with removing that gueesing :+1: 

Alrougth having a release with the deprecation warning sounds like a good idea since at least we have tried not to "surprise" our customers.

**Comment by oleiade** [comment]
I agree with the observation, and I'm happy with the solution. This specific use case happens to me all the time, and I find it indeed confusing and frustrating 👍🏻

**Comment by codebien** [comment]
>Alrougth having a release with the deprecation warning sounds like a good idea since at least we have tried not to "surprise" our customers.

We should do something more aggressive here, in concrete that message is already a deprecation process. If they really are using it and they still need it for whatever reason then they can avoid upgrading. I'm for dropping in the upcoming release.

I don't see the benefits in doing the deprecation process, we are not removing any functionality, and I'm not even sure that we should consider it as a breaking change.
