### ISSUE TITLE
 Making the k6/experimental/timers module part of the k6 core

### ISSUE THREAD

**Issue by mstoykov** [grafana/k6#3297]
[xk6-timers](https://github.com/grafana/xk6-timers) implement the very old [setTimeout](https://developer.mozilla.org/en-US/docs/Web/API/setTimeout) and co.

The module has a single open issue https://github.com/grafana/xk6-timers/issues/3  and is used fairly commonly.

The functionality it provides is also needed to delay execution in ways similar to `sleep` but without blocking the event loop.

## Blockers:
1. ~https://github.com/grafana/xk6-timers/issues/3 - the issue should be fixed.~
2. what will be the import path `k6/timers` ? Do we want to actually just have it globally, given how it is usually used in JS. That will add more intercompatibility with other JS engines.

## Alternatives: 

While setTimeout and co are very old and known, they are not very promise/async/await friendly as they predate them.

The things that keeps poping out is `delay` both from
1. [deno std lib](https://deno.land/std@0.199.0/async/delay.ts?s=delay)
2. [npm package](https://www.npmjs.com/package/delay) 
3. a [gist](https://gist.github.com/mstoykov/7684bf54a1e2f35d048868ba6117e2cb) with a version for k6

The provided APU has the benefit of doing 

```javascript
// code A
await delay(10);
// code B
```

instead of 
```javascript
// code A
setTimeout( () => {
  // code B
}, 10)
```

But likely we should still have `setTimeout` and co.

**Comment by hrqiang** [comment]
+1 upvote

**Comment by codebien** [comment]
Feature request for having `setTimeout` as global https://github.com/grafana/k6/issues/3329
