### ISSUE TITLE
publish arm64 images to Docker hub

### ISSUE THREAD

**Issue by SvenDowideit** [grafana/k6#3301]
### Brief summary

so I found #3015, which seems to imply that the arm64 image is buildable, but when I goto https://hub.docker.com/r/grafana/k6/tags there's only a `linux/amd64` image.

### k6 version

any

### OS

OSX, Docker Desktop, Ubuntu, 

### Steps to reproduce the problem

go to https://hub.docker.com/r/grafana/k6/tags - at this point 0.46.0 is the current release, and unlike (for eg https://hub.docker.com/r/grafana/grafana/tags ), the k6 image is not multi-arch

### Expected behaviour

the desired nirvana would be that all the architectures work - in my case, it'd be nice for my arm64 systems to be happy without needing the cross-arch support :)

### Actual behaviour

multi-arch images, or a nice sentence of why it doesn't make sense to do it atm, and who could help make it happen / change that

**Comment by codebien** [comment]
Hey @SvenDowideit, a new image supporting `linux/arm64` is now available for the grafana/k6 `master` tag. https://hub.docker.com/layers/grafana/k6/master/images/sha256-ab124b905466c8b75699424e1a76eba8c46d0af0689dff3fa04764d0f3d1368e

Can you give it a try and let we know if it works for you?

We will start pushing the `linux/arm64` images for stable versions from the next published version.

**Comment by SvenDowideit** [comment]
confirmed! awesome, thanks a bunch :)

```
dowideit.sven@ABC-KC00PW16GC secure-abc-loadtest-k6-spot-instance % docker run --rm -it grafana/k6:master
Unable to find image 'grafana/k6:master' locally
master: Pulling from grafana/k6
9fda8d8052c6: Pull complete 
0433adfa6c63: Pull complete 
4c461cabc4fd: Pull complete 
4f4fb700ef54: Pull complete 
Digest: sha256:ba04b36acbeffb7d5b4d4b38c342d99b9c4781bc2712093de9f80a51d6964528
Status: Downloaded newer image for grafana/k6:master

          /\      |‾‾| /‾‾/   /‾‾/   
     /\  /  \     |  |/  /   /  /    
    /  \/    \    |     (   /   ‾‾\  
   /          \   |  |\  \ |  (‾)  | 
  / __________ \  |__| \__\ \_____/ .io
```

vs the latest release

```
dowideit.sven@ABC-KC00PW16GC secure-abc-loadtest-k6-spot-instance % docker run --rm -it grafana/k6
Unable to find image 'grafana/k6:latest' locally
latest: Pulling from grafana/k6
4db1b89c0bd1: Already exists 
1cb0eda14b0d: Already exists 
7b640e95e2ae: Already exists 
4f4fb700ef54: Already exists 
Digest: sha256:2f40a302ec1e1e3cc96b9a3871bf5d7d4697e9ecc4fe90546ba0eb005d3458e3
Status: Downloaded newer image for grafana/k6:latest
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
```
