### ISSUE TITLE
Support per-vu TLS configuration for HTTP

### ISSUE THREAD

**Issue by oleiade** [grafana/k6#3315]
### Feature Description

A user case for having the ability to have a per-vu TLS configuration for HTTP was recently reported to us.

With `v0.46`, we have introduced the ability to configure TLS per-vu for gRPC, and it might be worth considering doing that for HTTP, too. This could probably be part of the design considerations of the #2461 project. 

This might be a duplicate, if so, please feel free to reference the original and close this.

### Already existing or connected issues / PRs (optional)

#2461

**Comment by codebien** [comment]
This should be the original issue for having TLS configurable https://github.com/grafana/k6/issues/2186, we have closed it as it should be covered by the design doc. If it isn't the case then we should directly amend the design doc opening a PR.

**Comment by oleiade** [comment]
Awesome, thanks a lot @codebien 🙇🏻 I'll close this one too then.

To anyone who might read this, we intend to address this in the next major version of our HTTP module, as per [the existing design document](https://github.com/grafana/k6/blob/master/docs/design/018-new-http-api.md), whose development can be tracked in [#2461](https://github.com/grafana/k6/issues/2461).
