### ISSUE TITLE
Unable to assign a value to a global variable in setup function 

### ISSUE THREAD

**Issue by IrfanSyed-PSC** [grafana/k6#3316]
### Brief summary

Running the below code should set the value token globally and available in the default function, but the "authToken" variable is reset back to undefined.

```js
let authToken;

export let options = {
  vus: 1,
  iterations: 5,
};

function getToken() {
  return "xyz";
}

export function setup() {
  authToken = getToken();

  console.log('Setup tasks are being executed...');
  console.log('Got token:', authToken);
}

export default function () {
  console.log('authToken:', authToken);
}
```

### k6 version

0.42.0

### OS

Macos

### Steps to reproduce the problem

Run the below code

```js
let authToken;

export let options = {
  vus: 1,
  iterations: 5,
};

function getToken() {
  return "xyz";
}

export function setup() {
  authToken = getToken();

  console.log('Setup tasks are being executed...');
  console.log('Got token:', authToken);
}

export default function () {
  console.log('authToken:', authToken);
}
```

### Expected behaviour

The "authToken" variable should be set to "xyz" and should be available to the default funciton.

### Actual behaviour

The "authToken" variable is printing its value as "undefined".

**Comment by IrfanSyed-PSC** [comment]
I read somewhere that I have to return the value in setup() to pass it across the default and other functions, so changing the below code works as I expected.  Is this the right approach ? 

```js
let authToken;

export let options = {
  vus: 1,
  iterations: 5,
};

function getToken() {
  authToken = "hello"
  return authToken;
}

export function setup() {
  let authToken = getToken();

  console.log('Setup tasks are being executed...');
  console.log('Got token:', authToken);
  return getToken();
}

export default function (token) {
  console.log('authToken:', token);
}
```

**Comment by oleiade** [comment]
Hi @IrfanSyed-PSC 

You're almost there; the `setup()` function has the ability to return a "data" object, which will be received by the default function as well as the `teardown` function as their first argument.

Transposed to your case, something along those lines should work:
```javascript
 let authToken;

export let options = {
  vus: 1,
  iterations: 5,
};

function getToken() {
  authToken = "hello"
  return authToken;
}

export function setup() {
  return { token: getToken() };
}

export default function (data) {
  console.log('authToken:', data.token);
}
```

Let me know if that was successful 🙇🏻 

PS: no big deal at all, but this issue was neither a bug report nor a feature request, and I would suggest asking these more support-oriented questions on our [open-source community](https://community.grafana.com/c/grafana-k6/70) next time 👍🏻

**Comment by IrfanSyed-PSC** [comment]
Thank you, appreciate it ! Will do next time.
