### ISSUE TITLE
prometheus remote write output

### ISSUE THREAD

**Issue by freeseacher** [grafana/k6#3326]
### Brief summary

I have such a stand 
```
export K6_PROMETHEUS_RW_PUSH_INTERVAL=1s
export K6_PROMETHEUS_RW_TREND_AS_NATIVE_HISTOGRAM=true
export K6_PROMETHEUS_RW_STALE_MARKERS=true
k6 run load.js -o experimental-prometheus-rw --tag testid=xxx
```

I'm expecting that k6 would emit timeseries data every one second. 
But i observe different behavior
```
k6_vus{testid="XXX"}[10m]
3000 @1693918359.283
3000 @1693918361.284
3000 @1693918362.283
3000 @1693918363.283
```

There are no data for 60 second. also i observe this on other timeseries. 
that is why i cant do rate(...[2s]) to have per second values. 
that is especially annoying for errors. i cant show on a graph exact time when it happen.

### k6 version

k6 v0.45.1 ((devel), go1.19.12, linux/amd64)

### OS

Linux Mint 21.2

### Steps to reproduce the problem

1. create simple test with output to prometheus-remote-write
2. make it run
3. check response from prometheus with k6_http_reqs_total[10m] 
4. validate that timestamps are sequential.

### Expected behaviour

timestamps has sequential timestamps that grows every K6_PROMETHEUS_RW_PUSH_INTERVAL.

### Actual behaviour

there are holes in timestamps. 
that is not what is expected from definition of timeseries.

**Comment by oleiade** [comment]
Assigning @codebien instead, as I will be away for a while, and I'm sure he will have more immediately actionable context on this 🙇🏻

**Comment by codebien** [comment]
Hey @freeseacher,

I tried to reproduce your steps and I got the fine granularity of 1s as you can see from the graph below. You can try to re-run k6 in verbose mode using the `--verbose` flag so you can assert if you are getting the expected frequency of 1s.

```js
import http from "k6/http";
import { check } from "k6";

export let options = {
    stages: [
        { duration: "5s", target: 5 },
        { duration: "5s", target: 8 },
        { duration: "5s", target: 20 },
        { duration: "5s", target: 0 },
        { duration: "5s", target: 15 },
        { duration: "30s", target: 10 },
    ]
};

export default function() {
    let res = http.get("http://test.k6.io");
    check(res, { "status is 200": (r) => r.status === 200 });
}
```

Below the graph from Prometheus' UI:

![prom-1s](https://github.com/grafana/k6/assets/2103732/ae783a73-19fe-4de2-9c47-28a58709a49f)

If you still have the issue, please open a topic on the [Community forum](https://community.grafana.com/c/grafana-k6/70) reporting a specific script so we can better support you. I'm closing feel free to reopen if you have specific details for reproducing the issue.

**Comment by freeseacher** [comment]
could you please show not the graph but timestamps ?

**Comment by codebien** [comment]
@freeseacher 
```
2 @1694452570.026
3 @1694452571.026
4 @1694452572.026
4 @1694452573.026
5 @1694452574.026
6 @1694452575.026
6 @1694452576.026
7 @1694452577.026
7 @1694452578.026
10 @1694452579.026
12 @1694452580.026
15 @1694452581.026
17 @1694452582.026
19 @1694452583.026
17 @1694452584.026
13 @1694452585.026
```

**Comment by codebien** [comment]
Just for the report, I've used k6 v0.46 and Prometheus v0.47

**Comment by freeseacher** [comment]
wow! they are millisecond accurate. fantastic. let me check with k6 0.46

**Comment by freeseacher** [comment]
i cant reproduce your test result. 
i took exactly your script and versions of k6 and prometheus 
i've got this results for requests

k6_data_received_total[10m]
```
46459 @1694507855.889
164871 @1694507856.927
312466 @1694507857.917
442729 @1694507859.068
578491 @1694507859.844
856359 @1694507860.897
1205365 @1694507861.956
1578171 @1694507863.029
1933573 @1694507864.02
2383004 @1694507865.057
2950741 @1694507865.963
3590413 @1694507867.026
4282914 @1694507868.067
5051115 @1694507869.011
6028000 @1694507870.059
6803566 @1694507871.022
7395820 @1694507872
```

verbose log also tell a little bit about timings
```Successful flushed time series to remote write endpoint  nts=25 output="Prometheus remote write" took=3.949207ms ```

**Comment by codebien** [comment]
Why are you checking `k6_data_received_total` if you asked for `k6_vus` before?

**Comment by freeseacher** [comment]
because problem that i trying to solve is a continuous data timestamped each second. 
promethues [data model](https://prometheus.io/docs/concepts/data_model/) requests it 
>Most commonly, a time series is a taken at successive equally spaced points in time.

as far as i understand it primary keyword here is `equally`. 
so in case metric arrived in one second it must be here in every other second even if it is not changed.
if it is not here i will get graph with holes in it ![image](https://github.com/grafana/k6/assets/289277/c2344823-da63-4a06-9622-8f6af5823b50)
