### ISSUE TITLE
K6 Test Result Dashboard is not working properly

### ISSUE THREAD

**Issue by indrakit2** [grafana/k6#3330]
### Brief summary

I have imported K6 Test Result Dashboard and have a problem: if a test has failed, you cannot see it in the dashboard. Because it only shows positive tests. 
Also there is an error with histogramm_sum as you can see in the picture below. 

![image](https://github.com/grafana/k6/assets/14870637/cd177d93-3b84-461c-9d6c-d54bb02f26f5)

### k6 version

0.3.0

### OS

Linux

### Steps to reproduce the problem

- Imported K6 dashborad from https://grafana.com/grafana/dashboards/18030-official-k6-test-result/ 
- Created the test.js file, a configmap to upload the test and a custom K6 resource to run the test
- I created an error in the test to see how it displays on the dashboard

This is what i see 

![image](https://github.com/grafana/k6/assets/14870637/0a9ec37f-70df-49fd-8901-33f14bb7cf69)

### Expected behaviour

I should be able to see a check of failed and passed like this one

![image](https://github.com/grafana/k6/assets/14870637/ed0b705e-f16d-4161-9f0e-bf6a0d42262f)

### Actual behaviour

As mentioned above

**Comment by codebien** [comment]
Hey @indrakit2, a new dashboard version has been released, check out the new revision. Feel free to re-open and provide more details if you don't see it fixed.
