### ISSUE TITLE
Go install k6 broken and linter issues

### ISSUE THREAD

**Issue by gmontagu** [grafana/k6#3331]
### Brief summary

Running `go install go.k6.io/k6` results in an error due to a dependency on `github.com/jhump/protoreflect`. The latest version from this repository appears to have fixed the issue - https://github.com/jhump/protoreflect/issues/566

Additionally, and maybe related, running `golangci-lint` is also broken. Potentially due to the previous failures?

### k6 version

v0.46.0

### OS

macOS

### Steps to reproduce the problem

Run `go install go.k6.io/k6`
Run `golangci-lint run --fix -E gci,godot,gofumpt,misspell,whitespace,gosec` 

### Expected behaviour

Both processes to complete successfully.

### Actual behaviour

`go install go.k6.io/k6`
Results in

```
# github.com/jhump/protoreflect/desc/protoparse
../../go/pkg/mod/github.com/jhump/protoreflect@v1.15.1/desc/protoparse/ast.go:151:12: undefined: ast.OneOfNode
../../go/pkg/mod/github.com/jhump/protoreflect@v1.15.1/desc/protoparse/ast.go:244:47: undefined: ast.OneOfNode
../../go/pkg/mod/github.com/jhump/protoreflect@v1.15.1/desc/protoparse/ast.go:258:53: undefined: ast.OneOfElement
../../go/pkg/mod/github.com/jhump/protoreflect@v1.15.1/desc/protoparse/ast.go:271:1: missing return
../../go/pkg/mod/github.com/jhump/protoreflect@v1.15.1/desc/protoparse/parser.go:257:25: undefined: options.Index
```

`golangci-lint run --fix -E gci,godot,gofumpt,misspell,whitespace,gosec`  Tested with golangci-lint versions `v1.52.2` and `v1.54.2`)

 results in:
```
WARN [runner] Can't run linter goanalysis_metalinter: inspect: failed to load package cmd: could not load export data: no export data for "go.k6.io/k6/cmd" 
ERRO Running error: 1 error occurred:
        * can't run linter goanalysis_metalinter: inspect: failed to load package cmd: could not load export data: no export data for "go.k6.io/k6/cmd"
```

**Comment by olegbespalov** [comment]
Hi @gmontagu !

Can I add more details about how you are using `go install`? Are you trying to install the k6, or are you trying to add this as a dependency to any project? Which version of golang are you using?

Does the command work with adding the latest tag, e.g. `go install go.k6.io/k6@latest`?

Does maybe cleaning the cache help, e.g. `go clean -modcache`? 

All that I'm asking since I've tried to run `go install`, and it works for me:
```
docker run --rm golang:1.20 go install go.k6.io/k6@latest
```

**Comment by gmontagu** [comment]
Hi @olegbespalov I'm on Go 1.21.1. My project is configured to install K6 locally via a tools.go setup like this:

```
import (
       ...
	_ "go.k6.io/k6"
       ... 
)
```
And then we have a process to build our tools in a Make file:
```
	GOPRIVATE=(...) go mod download -x
	GOPRIVATE=(...) cat tools.go | grep _ | awk -F'"' '{print $$2}' | xargs -tI % go install %
```

The version of K6 set in the go.mod file is `go.k6.io/k6 v0.46.0`

Using `go clean -modcache` didn't resolve the issue. 

For more information we're building a K6 image using [Ko](https://github.com/ko-build/ko) that runs the following code which starts a java script process.
```
package main

import (
	"os"

	"go.k6.io/k6/cmd"
)

func main() {
	for i := range os.Args {
		os.Args[i] = os.ExpandEnv(os.Args[i])
	}
	cmd.Execute()
}
```
However, we aren't even trying to start this process up as it's failing during tools install and linting

**Comment by olegbespalov** [comment]
I've created the PR by updating the k6. Could you please confirm that pointing to this specific commit 481b2953868798469e6d71e873b4391f54279660 fixes your issue?

**Comment by gmontagu** [comment]
@olegbespalov This fixes the issue, thank you!

**Comment by olegbespalov** [comment]
Thanks for checking, and thanks for reporting the issue :+1: :bow:

**Comment by mstoykov** [comment]
@gmontagu can you confirm that something else requires `github.com/bufbuild/protocompile@v0.6.0` as otherwise I don't see why this will happen?
