### ISSUE TITLE
Prometheus client and output support unix sock.

### ISSUE THREAD

**Issue by fly3366** [grafana/k6#3349]
### Feature Description

now client in xk6 prometheus plugin only support http client without unix dial context.
plz support it where someone need remote write to a unix sock, which listen by prometheus locally.

### Suggested Solution (optional)

in remote package use unix dial when url parse a unix:// schema.

**Comment by codebien** [comment]
Hey @fly3366,
it's not clear to me which is the library you are referring to.

Do you want to directly write to your Prometheus instance via remote write some arbitrary data so using https://github.com/grafana/xk6-client-prometheus-remote or do you want to flush the k6's metrics to your Prometheus instance so https://github.com/grafana/xk6-output-prometheus-remote?

**Comment by codebien** [comment]
Closing, feel free to re-open providing more details.
