### ISSUE TITLE
Not all cookies are fetched in response.cookie

### ISSUE THREAD

**Issue by pranesh517** [grafana/k6#3364]
### Brief summary

When tried hitting an URL with OKTA authentication, some cookies I don't see in response.cookies but same end point is giving cookies in POSTMAN. Cannot attach end points as they are restricted to share.

Is there any way or function i can use to accept all the cookies?

authUrl = '<some url>';
let authResponse = http.get(authUrl);
console.log('status==>', authResponse.status); // giving 200
console.log('cookies===>', authResponse.cookies); // blank

### k6 version

v0.43.1

### OS

Windows 10

### Steps to reproduce the problem

When tried hitting an URL with OKTA authentication, some cookies I don't see in response.cookies but same end point is giving cookies in POSTMAN. Cannot attach end points as they are restricted to share.

### Expected behaviour

Cookies list should be available in response.cookies

### Actual behaviour

For same authentication end point cookies are visible in POSTMAN while same end point don't give cookies in K6

**Comment by codebien** [comment]
Hey @pranesh517,
can you report what are the missing cookies, please? It could be you're hitting one of the already known issues https://github.com/search?q=repo%3Agrafana%2Fk6+cookie++&type=issues&state=open

**Comment by pranesh517** [comment]
@codebien I am having some special characters within the end point. Like '/' is getting replaced by %2. I am copying the end point from postman. But same end point with same special characters is giving cookies output the postman. When i replaced special characters in both POSTMAN and K6 i am getting 400. Is this issue related to some special characters in end point?

**Comment by pranesh517** [comment]
@codebien Found the cookies i was looking for using cookiesForURL() method
