### ISSUE TITLE
Generalize resulting request duration name

### ISSUE THREAD

**Issue by bedefaced** [grafana/k6#3403]
### Feature Description

Hello,

1. There are several built-in metrics' names for different protocols (`http_req_duration`, `grpc_req_duration` and something like these in third-party extensions for other protocols). Wouldn't be better to use generalized name like `req_duration` to describe _main_ metric name?
2. Wouldn't be better to create built-in custom metric and provide function which users (or third-party extensions developers) could use to save custom metrics (requests' duration and status) in results (like "lr_set_transaction" in LoadRunner / Dummy Sampler in Jmeter)?

**Comment by codebien** [comment]
Hey @bedefaced,

>Wouldn't be better to use generalized name like req_duration to describe main metric name?

I'm not against this in principle, but they are a very important part of the product and a change to them will be a big change with a relevant impact. There are a lot of details to consider in a change like this, for example, if you have a test with both, how do you differentiate between them? If something like this will be implemented, I don't think is realistic to be considered before https://github.com/grafana/k6/issues/1321 that introduces a granular control over each metric to compute and expose.

>Wouldn't be better to create built-in custom metric and provide function which users (or third-party extensions developers) could use to save custom metrics

This is why custom metrics exist, and what the built-in metrics are exporting should be possible to be recreated in a specific custom metric writing some JavaScript code or in very specific and/or advanced cases via extensions. [Just an example from the custom metric documentation](https://k6.io/docs/using-k6/metrics/create-custom-metrics/#example-create-a-trend-metric-for-waiting-time).

In any case, they both sound to me like solution proposals, but before it is relevant for us to understand the problems with the current implementation. What are the use cases you're trying to improve with your proposals?

**Comment by codebien** [comment]
At the moment, this is not planned, feel free to re-open or add more details.
