### ISSUE TITLE
Typo 'Reponse' instead of 'Response' in the log file

### ISSUE THREAD

**Issue by HakamFostok** [grafana/k6#3404]
### Brief summary

Typo writing 'Reponse' instead of 'Response' in the log file

### k6 version

k6 v0.46.0 (2023-08-14T13:23:26+0000/v0.46.0-0-gcbd9e9ad, go1.20.7, windows/amd64)

### OS

k6 v0.46.0 (2023-08-14T13:23:26+0000/v0.46.0-0-gcbd9e9ad, go1.20.7, windows/amd64)

### Steps to reproduce the problem

In the resulting log file, there is a typo
the `Response code` is written as `Reponse code` (the first `s` is missing)
I discovered this when I searched for Re**s**ponse word and did not find it in the log file

### Expected behaviour

writing `Response code` to the log file

### Actual behaviour

writing `Reponse code` to the log file

**Comment by oleiade** [comment]
Hi @HakamFostok 👋🏻 

Thanks for bringing this to our attention. You mention a log file. To avoid misunderstandings and facilitate addressing the issue, could you clarify which command you used and which result file you're referring to?

🙇🏻

**Comment by HakamFostok** [comment]
I executed the following command

```
k6 run --http-debug="full" --logformat=raw --console-output=./log.json myscript.js
```

and after the execution is completed, a new file is generated with the name `log.json` (although the content of it is not json, but not important to our point).

If I understood correctly the `log.json` file is logging the requests that happening.

here is an line from that file, as an example

```
Method - SomeMethod; Virtual User - 5; Reponse code - 400; Response Time - 319.7501; Response - { someJson object}; Request Headers - Content-Type,application/x-www-form-urlencoded,User-Agent,k6/0.46.0 (https://k6.io/), Authorization,Bearer MyBaearerToken
```

**Comment by oleiade** [comment]
Thanks a lot for providing additional information @HakamFostok 🙇🏻 

I don't seem to be able to reproduce the issue you are pointing out with the latest version of k6. Could it be that you use an older version of k6 by any chance?

**Comment by HakamFostok** [comment]
Sorry @oleiade it is my fault
the script file was using the `console.log` and it was logging this.
I did not write the script, it was given to me, that is why I thought that was k6 bug.
sorry so much again, I am closing this

**Comment by oleiade** [comment]
No worries at all, I'm glad you found a solution after all 🎉
