### ISSUE TITLE
Separate proxy configuration for outputs

### ISSUE THREAD

**Issue by IvanovOleg** [grafana/k6#3418]
### Feature Description

Hello,
In my organization InfluxDB cluster is not available for direct connections from certain locations, but it is possible using a proxy.
I tried to use a command like this:
```
HTTP_PROXY=proxy:3128 HTTPS_PROXY=proxy:3128 k6 run /tests/generic_endpoint.js --out influxdb=$K6_INFLUXDB_URL:$K6_INFLUXDB_PORT/$K6_INFLUXDB_DATABASE
```
but it looks like k6 uses those vars only for the testing requests. I also tried to export those vars, but got the same results. But even if it would work like that, it is still not a good solution since I don't want to send my requests through the same proxy.

### Suggested Solution (optional)

Add the K6_INFLUXDB_PROXY env var

**Comment by mstoykov** [comment]
Hi @IvanovOleg, thanks for opening this issue.

Looking at this I don't think it will be great idea to have one overarching configuration for all outputs. This will just get to the next point where someone needs 2 outputs one of them going through one proxy one going through another.

This also allows outputs to potentially not need to support this. 

So your solution seems okay.

While I don't think we will continue working on influxdb output and I feel like soon it will follow statsd, although probably after prometheus remote write is more stabalized, I do think we can take an outside PR on adding this if you want to open one. 

Hope to see a PR soon and please see the https://github.com/grafana/k6/blob/master/CONTRIBUTING.md :heart:
