### ISSUE TITLE
Allow removing unneded built-in metrics from the sampe output

### ISSUE THREAD

**Issue by MurzNN** [grafana/k6#3472]
### Feature Description

Regarding https://k6.io/docs/using-k6/metrics/create-custom-metrics/ we have a way to add custom metrics, but I can't find a way to remove built-in metrics.

I want to keep my database compact with only needed values, so I want to remove some built-in metrics. And not only from the summary (that can be handled by the function `handleSummary()`) but also from each sample metric. 

And for now, I see no way to do this.

For example, I don't need the `http_req_tls_handshaking` or `http_req_blocked` and want to get rid of it, I want to store only the one `http_req_duration` metric.

**Comment by oleiade** [comment]
Hi @MurzNN 👋🏻

Thanks for bringing this to our attention. We already have an issue tracking this specific need, I believe https://github.com/grafana/k6/issues/1321. 

It is our intent to look into this but both the solutions appear not trivial and we haven't had the opportunity to prioritize addressing it so far. 

Marking this as duplicate and closing 🙇🏻
