### ISSUE TITLE
Message sent to the server for Server streaming gRPCs

### ISSUE THREAD

**Issue by Marcel-MD** [grafana/k6#3567]
### Feature Description

When creating a new gRPC Stream there is no way to send a request message with the opening of a stream. This makes `Stream` unusable for Server streaming RPCs. This is the existing implementation:

```js
// Stream(client, method [, params])
// - client - already initialized and connected client with the loaded definitions.
// - method - a gRPC method URL to invoke.
// - params - an object with additional params that could be passed to the stream.
const stream = new Stream(
  client,
  'foo.BarService/sayHello',
  params
)
```

### Suggested Solution (optional)

A possible solution would be adding a new `request` parameter to the `Stream()` constructor:

```js
const request = {
  messsage: 'hello'
}

// Stream(client, method [, params] [, request])
// - client - already initialized and connected client with the loaded definitions.
// - method - a gRPC method URL to invoke.
// - params - an object with additional params that could be passed to the stream.
// - request - a canonical request object, as per the Protobuf JSON Mapping.
const stream = new Stream(
  client,
  'foo.BarService/sayHello',
  params,
  request
)
```

**Comment by mstoykov** [comment]
Thanks for reporting this @Marcel-MD :bow: 

If I get this right you ahve a server-only streaming API. Where the client shouldn't be sending more than one message but the server will stream a lot of them. But you still need to send a message.

I do expect this needs a separate API on our side within go - but I can't find good examples on this.

The [one](https://github.com/pramonow/go-grpc-server-streaming-example/blob/1cdc9a9cd5f711963b4fc60c381817ca29c81160/src/proto/data.pb.go#L239-L250) I can find  seems to suggest that what you should do is just open a new stream, send the message and just close the send stream.

so 
```javascript
const request = {
  messsage: 'hello'
}

// Stream(client, method [, params] [, request])
// - client - already initialized and connected client with the loaded definitions.
// - method - a gRPC method URL to invoke.
// - params - an object with additional params that could be passed to the stream.
// - request - a canonical request object, as per the Protobuf JSON Mapping.
const stream = new Stream(
  client,
  'foo.BarService/sayHello',
  params
)
stream.write(request);
// some stream.on likely
stream.end();
```
Should work - have you tried that?

**Comment by Marcel-MD** [comment]
I've tried using `Stream.write()` but it doesn't work. The method is invoked when the `Stream` is created, but with an empty request. After that the server doesn't listen to other requests because it's server-only streaming.

**Comment by mstoykov** [comment]
Does it return some error? Log anything?

Also it will be benefecial if you can provide a reproducible example as that will make it a lot easier to see if it is a bug in how it is currently implemented or something we need to add.

Or even reproduce the problem you are having.

**Comment by mstoykov** [comment]
Glad this worked as intented :)

Can you just tell us also what you did wrogn to not work in the first place. It is good idea for us to know what didn't go well. Potentially making changes to make it better.

**Comment by Marcel-MD** [comment]
First time I created a `Map` using `new Map()`. For some reason in this case there were no topics in the request object. Disclaimer I'm a Golang Developer and rarely write JavaScript so maybe I don't understand how maps work in JS.

```js
export function subscriber() {
    client.connect(randomItem(nodes), {
        plaintext: true,
    });

    let topicsMap = new Map();
    let request = {
        topics: topicsMap.set(randomItem(topics), 0)
    };

    let stream = new grpc.Stream(client, 'broker.Broker/Subscribe');
    stream.write(request);
```

That's why I fixed it by not using `new Map()`.
```js
export function subscriber() {
    client.connect(randomItem(nodes), {
        plaintext: true,
    });

    let request = {
        topics: {}
    };

    let topic = randomItem(topics);
    request.topics[topic] = 0;

    let stream = new grpc.Stream(client, 'broker.Broker/Subscribe');
    stream.write(request);
```

**Comment by Marcel-MD** [comment]
You can make it better by adding some examples in documentation for server-only streaming or client-only streaming RPCs.

**Comment by Marcel-MD** [comment]
Yes, it looks good. Only thing, I think you have a typo here, should be "The example below demonstrates server streaming.".
<img width="747" alt="image" src="https://github.com/grafana/k6/assets/70024859/8217bc36-2bd7-4109-85bb-21f2c2602b23">

**Comment by olegbespalov** [comment]
You're :100: correct; thanks! I'm going to fix that. Thanks!
