### ISSUE TITLE
k6 grpc Examples inport error

### ISSUE THREAD

**Issue by owanio1992** [grafana/k6#3571]
### Brief summary

in this doc 
https://grafana.com/docs/k6/latest/javascript-api/k6-experimental/grpc/stream/
`import { Client, Stream } from 'k6/experimental/grpc';`

but in git 
https://github.com/grafana/k6/blob/master/examples/grpc_client_streaming.js
https://github.com/grafana/k6/blob/master/examples/grpc_server_streaming.js
it's 
```
import { Client, Stream } from 'k6/net/grpc';
```

and use git script (both `grpc_client_streaming.js`, `grpc_server_streaming.js` )
it's will get error
```
ERRO[0000] TypeError: Cannot read property 'name' of undefined
        at pointSender (file:///k6-master/examples/grpc_client_streaming.js:112:12(5))
        at file:///k6-master/examples/grpc_client_streaming.js:102:16(60)  executor=per-vu-iterations scenario=default source=stacktrace
```

### k6 version

v0.48.0

### OS

linux ubuntu 22

### Docker version and image (if applicable)

latst Digest: sha256:4f9845e7f2efc9abdc3aba5d49e96fd6020ea167a722e0014e848409cc9cd4f5

### Steps to reproduce the problem

```
# start server
git clone git@github.com:grafana/k6.git
go run -mod=mod examples/grpc_server/*.go

# test
k6 run examples/grpc_client_streaming.js
```

### Expected behaviour

no error

### Actual behaviour

get error
```
ERRO[0000] TypeError: Cannot read property 'name' of undefined
        at pointSender (file:///k6-master/examples/grpc_client_streaming.js:112:12(5))
        at file:///k6-master/examples/grpc_client_streaming.js:102:16(60)  executor=per-vu-iterations scenario=default 
```

**Comment by olegbespalov** [comment]
Hi @owanio1992 

In the [k6 v0.49](https://github.com/grafana/k6/releases/tag/v0.49.0), which just happened, the gRPC experimental module was graduated, and streams became part of the core.

The examples in git were updated since the change was merged. So if you update to the v0.49 you could import as:

```js
import { Client, Stream } from 'k6/net/grpc';
```

However, the error 

```
ERRO[0000] TypeError: Cannot read property 'name' of undefined
        at pointSender (file:///k6-master/examples/grpc_client_streaming.js:112:12(5))
        at file:///k6-master/examples/grpc_client_streaming.js:102:16(60)  executor=per-vu-iterations scenario=default source=stacktrace
```

seems like the `pointSender` picked the point from `sample DB` without the `name` property defined, which is weird.

Are you trying to run an unmodified version of the example?

**Comment by owanio1992** [comment]
I tried use v0.49.0 
it's can work use
```
import { Client, Stream } from 'k6/net/grpc';
```

thank very much
