### ISSUE TITLE
K6 Docker Image: update-ca-certificates not found on release 0.49.0, working fine on 0.48.0 

### ISSUE THREAD

**Issue by reinhartbuit** [grafana/k6#3582]
### Brief summary

I currently create a custom Docker Image where I copy .crt files into the container and then finally it runs 'update-ca-certificates'. I have been using the docker image grafana/k6:0.48.0 and did not encounter any issues. 

I now changed the docker file to use grafana/k6:0.49.0 instead, and now I get /bin/sh: update-ca-certificates: not found.

`FROM grafana/k6:0.49.0

USER root

COPY certs/xxxxx.crt /usr/local/share/ca-certificates/ixxxxx.capi.crt
RUN  update-ca-certificates

COPY test /test

USER 1000

EXPOSE 6565

ENV TZ="Africa/Johannesburg"

ENTRYPOINT ["k6", "run"]`

### k6 version

0.49.0

### OS

macOS

### Docker version and image (if applicable)

grafana/k6:0.49.0

### Steps to reproduce the problem

1. Create DockerFile with contents:

`FROM grafana/k6:0.48.0

USER root

COPY certs/xxxxxx.crt /usr/local/share/ca-certificates/xxxxxx.crt
RUN  update-ca-certificates

COPY test /test

USER 1000

EXPOSE 6565

ENV TZ="Africa/Johannesburg"

ENTRYPOINT ["k6", "run"]`

2. Run command: 'docker build .'
3. Build is successful.

4. Change the Docker file FROM to 0.49.0 instead of 0.48.0
5. Run command: 'docker build.

### Expected behaviour

Docker build to be successful

### Actual behaviour

 > [5/6] RUN  update-ca-certificates:
0.197 /bin/sh: update-ca-certificates: not found

**Comment by joanlopez** [comment]
Hey @reinhartbuit,

I guess that's because after [this commit](https://github.com/grafana/k6/commit/f9ee99de8d97d0bf461ac943ec1f7ccb53613086), the k6 Docker image no longer has `ca-certificates` installed by default.

So, in order to get it back working, since `v0.49.0`, you'll need to slightly modify your Dockerfile, from:

```
RUN update-ca-certificates
```
to: 
```
RUN apk add --no-cache ca-certificates && \
    RUN update-ca-certificates
```

Can you try with that, please?

Thanks!

**Comment by reinhartbuit** [comment]
Thank you. That makes sense. 
Yes it worked, thanks for the help
