### ISSUE TITLE
Making SetTimeout and co. globally available by default

### ISSUE THREAD

**Issue by mstoykov** [grafana/k6#3589]
### Feature Description

Make the newly stabilized `k6/timers` exports:
1. SetTimeout
2. SetInterval
3. ClearTimeout
4. ClearInterval

globally available

### Suggested Solution (optional)

Keep the module, and just have code that imports and set them on `globalThis` by default that is run an VU initialization. 

### Already existing or connected issues / PRs (optional)

Stabilization PR #3587 
Original stabilization issue #3297 
SetTimeout not being globally available #3329

**Comment by olegbespalov** [comment]
I feel that having these functions globally accessible is what users will expect. However, I can't say I'm a JavaScript expert, so I am unsure if my feelings are relevant.

**Comment by joanlopez** [comment]
Similar to @olegbespalov, not a JS expert neither, but I guess that's what experienced JS users would expect, while for the rest it doesn't matter. So 👍🏻

**Comment by oleiade** [comment]
For clarification and my understanding, what does the target user-experience look like?

My assumption reading this is:

```javascript
// No need to import the `k6/timers` module

export default function () {
    setTimeout(...)  // timer functions are available in the runtime "natively", like in v8 browser runtimes
    setInterval(...)
    clearTimeout(...)
    clearInterval(...)
 }
```

If so, I think that makes a lot of sense, and although I'm not completely set on that, it is also something we might want to consider also for "Web APIs" we integrate in the future (webcrypto, streams, fetch (if we do), etc...) to provide a user-experience close to what is available in other runtimes. 

🙇🏻

**Comment by amills-vibeirl** [comment]
there is no event loop in Gofa (TMK). So I am not sure who/what would call the global setInterval. Using Goja for this lib seems like a terrible mistake and frankly I am gonna run as far as I can in another direction (no offense but hopefully this helps other people..)

**Comment by mstoykov** [comment]
@amills-vibeirl, while goja doesn't have an event loop in itself, k6 adds one. As will most projects using any js engine that want to have control over its event loop.
