### ISSUE TITLE
Lots of EOF and status code 0 errors at high # of virtual users

### ISSUE THREAD

**Issue by sallamander317** [grafana/k6#3597]
### Brief summary

I'm doing some load testing on a `BentoML` server in Python that runs an image classification model. Under large numbers of virtual users, I get back lots of EOF and status code 0 errors. I'm wondering what I can do to track these down on the K6 front. There are no errors showing on the server itself, so it seems that this might be related to a timeout and / or a connection error. But, I am able to trip these errors within 12 seconds of the test starting, and there are no timeouts (that I know) with this server that are lower than that. 

<img width="763" alt="Screen Shot 2024-02-13 at 8 50 58 AM" src="https://github.com/grafana/k6/assets/124316637/0ef64651-62ab-4a4e-9af2-b098eb40f7c3">

### k6 version

0.48.0

### OS

Amazon Linux

### Docker version and image (if applicable)

20.10.25, continuumio/miniconda3 is our base image

### Steps to reproduce the problem

1. Fire up `BentoML` server
2. Run k6 test with loads of virtual users (I've seen the problem from 90 all the way up to 300) 

### Expected behaviour

Requests that fail come back with a sensible status code that provides information about the failure (or maybe 0 is meaningful in a way that I don't understand). 

### Actual behaviour

Lots of EOF errors with 0 status code are returned, despite there being no errors on the server itself.

**Comment by oleiade** [comment]
Hi @sallamander317 👋🏻 

Would it be possible for you to share a script that reproduces the issue so we can try to track what happens? 🙇‍♂️

**Comment by sallamander317** [comment]
@oleiade I think below is the best I can do! For privacy reasons, I can't share the `BentoML` code itself (it's also incredibly cumbersome). And I've obfuscated the request call parameters a bit below, but feel free to ask follow up questions and I will answer as openly as I can! This is the load testing script that I run with `k6 run`. 

```
import http from 'k6/http';
import { sleep } from 'k6';
import { Counter } from 'k6/metrics';

export const CounterErrors = new Counter('Errors');

export const options = {
    // Key configurations for avg load test in this section
    thresholds: {
        'Errors': [
            {
                threshold: 'count<5',
                abortOnFail: true,
                delayAbortEval: "1s"
            }
        ]
    },
    stages: [
        { duration: '4800s', target: 480 }
        { duration: '60s', target: 480 }
        { duration: '60s', target: 0 }
    ],
};

export default () => {
    const urlRes = http.post('http://127.0.0.1:8000/analyze', JSON.stringify({
        "s3Path": [insert path to S3 URL],
        "modelsToRun": [insert list of strings that specify what models to run in BentoML]
    }), { headers: { 'Content-Type': 'application/json' }, timeout: '120s' });
    const contentOK = (
        urlRes.status === 200
    )
    if ( contentOK === false ) {
        console.log(urlRes.status, urlRes.body)
    }
    CounterErrors.add(!contentOK)
    sleep(0.001);
};
```

**Comment by oleiade** [comment]
Thanks a lot for the anonymized script, @sallamander317 🙇🏻 That's helpful!

I see no immediate/obvious candidate for the EOF error you encounter. However, considering that specific message and that you start observing the issue within a certain VU range, here are a couple of intuitions that might be worth exploring:
* I have a hunch those EOF messages hint at the connection being closed/dropped thus it might be worth taking a look at the performance/load monitor of the machine you run the test on, specifically CPU usage, and verify that k6 is not using the whole CPU.
* Would be worth checking the same for the system under test, the BentoML side, and if observability is available for that system, ensure that the system under test still has resources available to serve those connections.
* I also see that although I don't find the VU number particularly high, your iterations sleep for only 0.001, which feels very small. Coincidentally, when running the test, what iteration rate do you observe 🔍

**Comment by sallamander317** [comment]
@oleiade thanks for the quick response! I had forgotten that I didn't paste CPU findings here, but I had tracked that down as part of this (and I think just posted it to the bug I had filed with BentoML). As hopefully additional context, I think this graphic might help. It's from BentoML's website but does depict fairly well the underlying infra that we're hitting. 

<img width="796" alt="image" src="https://github.com/grafana/k6/assets/124316637/d084fb15-9394-4061-bea4-5b0812c3b5cc">

Basically, we've got two Python processes running: 
1. API Server - this accepts the requests and holds on to them / sends them asynchronously to the ML model process as it is ready for them.
2. ML Model process - this holds an ML model that asynchronously accepts inputs from the API server to run the model on.


RE the system usage...

- I only saw one process using significant CPU, and it was that 2nd process mentioned above, the one holding the ML Model. The errors seemed to be loosely correlated to when CPU usage spiked to about ~230 - 250%. But...
- There were other cases where I was able to alter this setup and have the CPU(s) run just as hot and not experience the error. In particular, when I ran two of those ML model processes (so now we have 3 processes in general), both of the ML model processes where able to run at ~250% CPU usage consistently without these EOF errors. So it seems as if these EOF errors might be a timeout of sorts. But that being said, I'm able to trigger them within ~12 seconds of the test running, and our server configuration doesn't have timeouts anywhere close to that low. 
- I did not see any RAM usage spikeage, either at the system or process level. The ML processes above only appeared to use ~5-10% of the RAM. 

RE the # of iterations, I'm seeing something along the lines of 40 - 120, depending on how our server is configured (e.g. one model versus two, batch size of the ML model, etc). 

I'll go back and double check these things today, but any initial thoughts and / or other details I can grab?

**Comment by oleiade** [comment]
Based on the information you provided and the workflow you described, my best-uninformed guess (as someone external to your workflows) is that the connections are getting dropped for a reason only you can establish. I do not see reasons to believe this is a k6 bug.

A bit of Googling outlined that the EOF message you're seeing is happening in Go when a socket connection is dropped, which can be caused by multiple factors but is most likely performance or timeout-related.

To get down to the bottom of it and verify if this hypothesis stands, I would suggest to:
- Use the k6 `--http-debug="full"` option to look at the detail of every HTTP request/response manipulated by k6. Is there a hint in there?
- If there aren't sufficient clues, use Wireshark and look at the TCP connections between your machine and your BentoML server, specifically looking for dropped packets, connections, and timeouts.
- Otherwise, if possible/available, it might be worth installing Prometheus+Grafana and observing metrics specific to sockets and TCP connections. Specifically, if you observe packets and connections dropped going up during your test, you might have found your culprit.
- Finally, depending on how you run your BentoML server, you might have a proxy/loadbalancer in front of it that logs connections and errors. If the connections are dropped, I expect the logs will contain more information.

🙇🏻

**Comment by sallamander317** [comment]
@oleiade this is fantastic - thank you for all the suggestions here! From my Googling it had also seemed likely to be a performance and / or timeout-related, but I was unsure of how to move forward to test that and further debug. So this is exactly what I was looking for, here, and I'll give all of this a go! 

I think it makes sense to close the issue here given that we don't think it's a k6 bug. I can test the hypothesis using all the above methods and circle back if those don't seem to yield fruit. Really appreciate the help and your expertise here, and all of the quick responses ❤️ !
