### ISSUE TITLE
Misleading error message when using invalid character in scenario name

### ISSUE THREAD

**Issue by dAnjou** [grafana/k6#3601]
### Brief summary

When using an invalid character in a **_scenario_** name, K6's error message is referring to the **_executor_** name instead:
```
ERRO[0000] There were problems with the specified script configuration:
        - scenario danjou.dev has configuration errors: the executor name should contain only numbers, latin letters, underscores, and dashes 
```

### k6 version

k6 v0.49.0 (go1.21.6, darwin/arm64)

### OS

macOS 14.3 (23D56)

### Steps to reproduce the problem

Using the following setup: https://gist.github.com/dAnjou/930e0263d7be45b97233959a4c02f792
```
k6 run --env CONFIG=default.json script.js
k6 run --env CONFIG=scenario.json script.js
k6 run --env CONFIG=buggy.json script.js
```

### Expected behaviour

The first 2 commands run a test.

The last one fails telling me there is an invalid character in the **_scenario_** name.

### Actual behaviour

The first 2 commands run a test.

The last one fails telling me there is an invalid character in the **_executor_** name.

**Comment by joanlopez** [comment]
Yeah, after a quick look, I'm pretty sure the [validation function](https://github.com/grafana/k6/blob/master/lib/executor/base_config.go#L48-L72) could be easily improved in terms of user experience and error message correctness. 

I'll open a PR soon with some refinements, including the one your reported.

Good catch @dAnjou, thanks! 🙌🏻
