### ISSUE TITLE
Will k6 support distributed agents?

### ISSUE THREAD

**Issue by yuanxiaomama** [grafana/k6#3609]
### Feature Description

The current k6 script only supports execution on one agent. Is there any plan to support distributed agents?
1. support distributed agents to execute script
2. collect script result from distributed agents

**Comment by codebien** [comment]
Hey @yuanxiaomama,
we have some options, but before I would like to hear what is your specific need. Can you describe it and give me a bit of context, please? Why are you looking to distribute a k6 execution? Did you hit some specific issues?

**Comment by codebien** [comment]
Closing, feel free to re-open reporting details.

**Comment by yuanxiaomama** [comment]
> Closing, feel free to re-open reporting details.

Thanks for reply! 
Actually dropped interations often occur when using k6 for testing. This issue can be solved by improving the configuration of the execution pod, but often we do not have such a high-configuration to use.

**Comment by codebien** [comment]
>Actually dropped interations often occur when using k6 for testing

Why do you think scaling is the solution? Are you sure your test script is well-designed? k6 can create a very high load with just one single instance.

>but often we do not have such a high-configuration to use

Are you using the `k6-operator`?
