### ISSUE TITLE
Memory growth due to TrendSink of K6 Metrics

### ISSUE THREAD

**Issue by AshwinAmbal** [grafana/k6#3618]
### Brief summary

Trend metrics memory usage keeps increasing because we keep accumulating all metrics throughout the test to show the end of test summary. This gives the false pretense that there is a memory leak in the application as seen in the screenshot below:
![Screen Shot 2024-02-28 at 11 37 16 AM](https://github.com/grafana/k6/assets/29573024/d4cf24d7-3467-49e3-acf6-1b7539bd56d2)

### k6 version

0.49.0

### OS

Alpine Linux

### Docker version and image (if applicable)

N/A

### Steps to reproduce the problem

I use K6 as a gRPC client that I've custom built using xk6 but i believe this should occur with any k6 client in general as it is k6 internals which are causing this. 

Use the k6 version 0.49.0 and run a load test with gRPC. 
Run the test for 15 minutes and a QPS of 20K per K6 client to see the memory growth trend. 
The more you increase the QPS, the faster the memory will grow in the client. 
I am using the `constant-arrival-rate` executor depicted here: https://k6.io/blog/how-to-generate-a-constant-request-rate-with-the-new-scenarios-api/

The environment I use is an AWS EKS cluster with a gRPC server and k6 client. 
The pod metrics are exported to prometheus and visualized using Grafana. 

I do use an extension that I build with as seen [here](https://github.com/AshwinAmbal/xk6-prometheus) which is forked from this repo [here](https://github.com/szkiba/xk6-prometheus) but with minor changes. 

I ran a pprof Stack trace and I have narrowed down the growing memory to the internals of k6 (the below portion keeps increasing throughout the course of the test)
```
heap profile: 151: 5131480 [16686: 64783064] @ heap/1048576
1: 3448832 [1: 3448832] @ 0x89d816 0xe1f159 0xa4b8f4 0x471241
#	0x89d815	go.k6.io/k6/metrics.(*TrendSink).Add+0xb5			go.k6.io/k6@v0.49.0/metrics/sink.go:120
#	0xe1f158	go.k6.io/k6/metrics/engine.(*OutputIngester).flushMetrics+0x358	go.k6.io/k6@v0.49.0/metrics/engine/ingester.go:90
#	0xa4b8f3	go.k6.io/k6/output.(*PeriodicFlusher).run+0x73			go.k6.io/k6@v0.49.0/output/helpers.go:69
```
This is the part of code which is causing the memory growth due to accumulaton: https://github.com/grafana/k6/blob/b5328aa782832a80451ea430075af8845dffb7cd/metrics/sink.go#L120

Here is my k6 build command:
```
CGO_ENABLED=0 xk6 build latest \
    --with github.com/AshwinAmbal/xk6-prometheus@v1.0.1 \
    --with xk6-grpc-client=. \
    --replace repo=internal_golang_repo_with_dependencies
```

Here is my k6 run command:
```
k6 run --out 'prometheus=namespace=k6' "--summary-trend-stats=min,med,avg,max,p(50),p(95),p(99)" script.js
```

I have also tested the same with the `--no-summary` option [here](https://k6.io/docs/using-k6/k6-options/reference/#no-summary) but the growth still keeps occurring because we don't have a condition to accumulate the metrics. We accumulate them irrespective of whether end of test summary is required or not. 

### Expected behaviour

Memory to be pre-allocated before the start of the test based on expected QPS / numVU's and remain stable throughout the test to avoid giving the false pretense that it is a memory leak with the client code. It would also be beneficial to have a warning if the memory allocation goes beyond the estimate to say that this is expected behavior. 

I am not sure if this should be the expected behavior in the first place but I am open to brainstorming and debugging together. 

### Actual behaviour

Memory growing incrementally throughout the course of the test
![Screen Shot 2024-02-28 at 11 37 16 AM](https://github.com/grafana/k6/assets/29573024/d4cf24d7-3467-49e3-acf6-1b7539bd56d2)
P.S. you see multiple k6 clients with memory growing in the image above because I am running them in parallel in K8s as a job.

**Comment by codebien** [comment]
Hey @AshwinAmbal, it sounds you hit a known issues. You can check here the reasons and the work-around https://github.com/grafana/k6/issues/2367#issuecomment-1028866630, you're almost close :+1: .

Let me know if it works.

**Comment by AshwinAmbal** [comment]
Thanks. Using `--no-summary `and `--no-thresholds` together works for me.
