### ISSUE TITLE
Test run hangs if dashboard open

### ISSUE THREAD

**Issue by oliver-dungey** [grafana/k6#3619]
### Brief summary

The new dashboard is brilliant but it has a little gotcha - if you have http://localhost:5665 open whilst a test is running k6 will not exit/finish properly. It sits waiting for you to close the dashboard before it will exit.

This caught me out as I have script that runs a series of k6 load tests and it was hanging and not moving on from the first test. Took a while to workout that it was caused by having the dashboard open in a browser.

### k6 version

0.49

### OS

Ubuntu 22.04

### Steps to reproduce the problem

1. Launch a k6 test from the command line.
2. Launch a browser and goto http://localhost:5665

### Expected behaviour

k6 will exit when the test run completes

### Actual behaviour

k6 does not exit until you close the browser tab.

**Comment by codebien** [comment]
@szkiba Can you take a look into it, please?

**Comment by szkiba** [comment]
This is how it works by design. The page below describes what to do if you want to avoid k6 waiting for the browser to close.
(set K6_WEB_DASHBOARD_PORT to -1)

https://grafana.com/docs/k6/latest/results-output/web-dashboard/

> NOTE
>
> The k6 process waits to exit as long as there is at least one open browser window for the dashboard extension. In this way, the report can be downloaded, for example, even after the test has been completed.
>
> In certain environments, it is not allowed that the k6 process does not exit after the test run (e.g CI/CD pipeline). In this case, it is advisable to disable the HTTP port (with the -1 value of port parameter).

**Comment by oliver-dungey** [comment]
@szkiba thank you. My apologies, I appear to have read everything around that paragraph yet totally missed it.
