### ISSUE TITLE
K6_SYSTEM_TAGS environment variable not being read

### ISSUE THREAD

**Issue by Tom-Dann** [grafana/k6#3638]
### Brief summary

The [system tags option](https://k6.io/docs/using-k6/k6-options/reference/#system-tags) is not being picked up when specified by the environment variable.

When using the CLI flag `--system-tags` or code `options.systemTags`, the system tags are being parsed and processed correctly. When using the `K6_SYSTEM_TAGS` environment variable option it reverts back to the default setting.

### k6 version

v0.49.0

### OS

macOS 14

### Steps to reproduce the problem

Run the following test script
```
import exec from 'k6/execution'

export default function () {
  console.log(exec.test.options.systemTags)
}
```
with the following commands
```
export K6_SYSTEM_TAGS=proto
k6 run test.js
```

### Expected behaviour

Console log is
```
["check","error","error_code","expected_response","group","method","name","proto","scenario","service","status","subproto","tls_version","url"]
```

### Actual behaviour

Console log should be 
```
["proto"]
```

(Running `k6 run test.js --system-tags=proto` produces this correct output)

**Comment by olegbespalov** [comment]
Hi @Tom-Dann ! Thanks for reporting the issue. It seems like a bug. We'll try to prioritize and fix it.
