### ISSUE TITLE
Customised profiling in K6

### ISSUE THREAD

**Issue by ameetpal** [grafana/k6#3641]
### Feature Description

As of now, there is only one flag to enable profiling on k6 "--profiling-enabled". This spin up a server to get runtime profiling data but our requirement to generate a pprof file at a specified location so that we can analyse later if our test had failed due to reasons like OOM. 

### Suggested Solution (optional)

We can have separate flags for different type of profiling, depending on the requirements
- "--enable-http-profiling"
- "--enable-pprof-dump"
- "--pprof-file-location"

**Comment by oleiade** [comment]
Hi @ameetpal 👋🏻 

Likely, I don't fully grasp your specific needs here. Still, off the top of my head, I am under the impression the native Golang profiling support that we expose at `http://localhost:6565/debug/pprof` already somewhat addresses some of your needs but does involve some additional steps indeed. 

Considering that one can download the pprof binary content into a file at any time during the k6 run with the `--profiling-enabled` option enabled: `curl --output heap.pprof http://localhost:6565/debug/pprof/heap`, and `go tool pprof` let me grab, for instance, the profiling information regarding the heap allocations in pprof format anytime, save them into a dedicated file, and analyze them.

Are there specific needs on your end that this workflow wouldn't cover?

In the meantime, if you're not already a user, I invite you to checkout [Pyroscope](https://github.com/grafana/pyroscope), another Grafana open-source project that allows continuously profiting executables.

**Comment by ameetpal** [comment]
Hi @oleiade,

We are running k6 in distributed manner in different kubernetes pods. To download through endpoint we have to expose the port on pods. We want to store heap allocations when test is finished and we want a dump even in case of issues like OOM. So we want a dump rather than a endpoint.

Also, Is it possible to integrate Pyroscope with K6 ?

**Comment by oleiade** [comment]
Hi @ameetpal 

To make Pyroscope able to access k6 profiling information, I suggest to use the Grafana agent, in its "flow" flavour/mode, and set it up to scrape the profiling information k6 exposes on port `6565`.

Here's the Pyrsocope documentation in that regards that might help you get started: https://grafana.com/docs/pyroscope/latest/configure-client/grafana-agent/go_pull/

For reference, here's the grafana-flow-agent configuration I use locally to do just that:
```
 logging {
  level  = "info"
  format = "logfmt"
}

pyroscope.write "local" {
  endpoint {
    url = "http://localhost:4040"
  }
}

pyroscope.scrape "scrape_k6" {
  targets    = [{"__address__" = "localhost:6565", "service_name" = "k6"}]
  forward_to = [pyroscope.write.local.receiver]

  profiling_config {
    profile.process_cpu {
            enabled = true
    }

    profile.godeltaprof_memory {
            enabled = true
    }

    profile.memory { // disable memory, use godeltaprof_memory instead
            enabled = false
    }

    profile.godeltaprof_mutex {
            enabled = true
    }

    profile.mutex { // disable mutex, use godeltaprof_mutex instead
            enabled = false
    }

    profile.godeltaprof_block {
            enabled = true
    }

    profile.block { // disable block, use godeltaprof_block instead
            enabled = false
    }

    profile.goroutine {
            enabled = true
    }
  }
}
```
**P.S**: `http://localhost:4040` is the address at which your pyroscope server is accessible, and `localhost:6565` is the k6 profiling endpoint.

For reference I run k6 using the following command: `k6 run --profiling-enabled script.js`, creating flamegraphes under the `k6` application in pyroscope.

Hope this is helpful 🙇🏻

**Comment by oleiade** [comment]
I think we have established that as far as we know no further changes to k6 are necessary for the discussed usage. As a result, I will close this issue.

@ameetpal if you have further questions about integrating k6 with Pyroscope, I invite you to address them to our [Community forum](https://community.grafana.com/c/grafana-k6/70) instead 🙇🏻
