### ISSUE TITLE
Missing content-type: application/grpc when port set to 443 for grpc load test

### ISSUE THREAD

**Issue by NVJCameron** [grafana/k6#3644]
### Brief summary

When trying to do a grpc based load test, I am getting an error message of `{"modelName":"","modelVersion":"","id":"","parameters":{},"outputs":[],"rawOutputContents":[]}` from my GRPC client

### k6 version

0.49.0

### OS

Ubuntu 20.04

### Steps to reproduce the problem

Here is my script

```
import grpc from 'k6/net/grpc';
import { check, sleep } from 'k6';
import encoding from 'k6/encoding';

const client = new grpc.Client();
client.load(['definitions'], 'triton_grpc_service.proto');


// content-type application/grpc
export default () => {
    client.connect('grpc.nvcf.nvidia.com:443', {});

    const params = {
        metadata: {
            'function-id': '<id>',
            'function-version-id': '<id>',
            'authorization': 'Bearer ' + '<token>'
        },
    };

    const req = { model_name: "echo",
        inputs: [
             {
                name: "message",
                datatype: "BYTES",
                shape: [1],
                contents: {
                    bytes_contents: [encoding.b64encode("someString")]
                }
            },
            {
                name: "response_delay_in_seconds",
                datatype: "FP32",
                shape: [1],
                contents: {
                    fp32_contents: [0.001]
                }
            },
        ],
        outputs: [{name: "echo"}], };
    const response = client.invoke('inference.GRPCInferenceService/ModelInfer', req, params);

    check(response, {
        'status is OK': (r) => r && r.status === grpc.StatusOK,
    });

    console.log(JSON.stringify(response.message));
    console.log(JSON.stringify(response.error));

    client.close();
    sleep(0.01);
};
```

I run with `k6 run echo_grpc_load_test.js --http-debug=full`

### Expected behaviour

A successful call

### Actual behaviour

Getting the error message of `{"code":2,"message":"malformed header: missing HTTP content-type","details":[]}`

**Comment by mstoykov** [comment]
Hi @NVJCameron, thanks for reporting this :bow: 

A quick test on my side with the example grpc_server shows that just being on port 443 is not enough to reproduce your case.

Unfortunately without more info ... my guess is just your server isn't configured correctly or you are hitting the wrong server.

Can you provide some more info, maybe use ssl key logger as not really explained in this [k6-docs issue](https://github.com/grafana/k6-docs/issues/754) this might let you see what exactly is being sent. This might shine some light on what actually happens.

Using something like https://github.com/fullstorydev/grpcurl to make a single request and sharing what the arguments and result was will also be nice.

**Comment by NVJCameron** [comment]
I tried again with `docker run fullstorydev/grpcurl -v grpc.nvcf.nvidia.com:443 list` and got: `Failed to list services: rpc error: code = Unknown desc = malformed header: missing HTTP content-type`

This is a public endpoint if you want to test as well. But I will likely need to take this back to our team.

**Comment by mstoykov** [comment]
@NVJCameron I take it that it turned out to be grpc.nvcf.nvidia.com issue?

Can you please give us a sentece or two of the what was the problem in case someone else hits something similar.

Thank you a lot :bow:

**Comment by NVJCameron** [comment]
@mstoykov my bad - I thought I added the resolution but it didn't save!

Yes - the issue was on our end. The issue was the internal error was being sent via HTTP, so that error message cause quite some confusion!

k6 is awesome btw. Great work!
