### ISSUE TITLE
Enabling Profiling using environment variable 

### ISSUE THREAD

**Issue by ameetpal** [grafana/k6#3670]
### Feature Description

Currently we are using k6-operator to run tests and how will we able to enable profiling in that ? As of now we are only passing environment variables.

Will it be possible to have a environment variable for enabling profiling ?

**Comment by ameetpal** [comment]
Any update here ?

**Comment by codebien** [comment]
Hey @ameetpal,
yes, it is a good idea to support it as we do for all other options. Unfortunately, I can't guarantee when we will be able to work on it. Probably, the best path for you could be to contribute by opening a pull request.

It should be very similar to the other environment variables in this part of the code https://github.com/grafana/k6/blob/a5dcc9950bfe952865f433c7ca0a61ef3a03dc56/cmd/state/state.go#L157-L165.

**Comment by Bablzz** [comment]
hello everyone! in this case it's just add env variable and set to [ProfilingEnabled](https://github.com/grafana/k6/blob/a5dcc9950bfe952865f433c7ca0a61ef3a03dc56/cmd/state/state.go#L151)?

**Comment by codebien** [comment]
Hey @Bablzz,
yes, very similar to what we already have for https://github.com/grafana/k6/blob/a5dcc9950bfe952865f433c7ca0a61ef3a03dc56/cmd/state/state.go#L163-L174

Plus, if we are going to add multiple ways for setting it then we have to add a test for the consolidation. https://github.com/grafana/k6/blob/a5dcc9950bfe952865f433c7ca0a61ef3a03dc56/cmd/config_consolidation_test.go#L146
