### ISSUE TITLE
Issue with specifying host in K6 browser experimental feature, leading to virtual user limitation

### ISSUE THREAD

**Issue by dylandifilippo** [grafana/k6#3685]
### Brief summary

At work, I'm using the K6 browser experimental feature for testing a website we're going to lunch next week and I cannot specify a host to prevent being flagged as a DDoS attack by the Akamai layer in place, limiting me to 10 virtual users before it breaks. 

Using the standard K6 library for average load testing, specifying the host works fine. However, with the K6 browser feature on my Mac, despite setting the host in the K6 script options and using `sudo nano /etc/hosts` in the terminal, the issue remains.

### k6 version

0.50

### OS

macOS 14.4.1

### Steps to reproduce the problem

Try to specify an host in the code.

### Expected behaviour

Being able to add an host.

### Actual behaviour

Not being able to add an host and assuming I'm doing a DDoS attack.

**Comment by oleiade** [comment]
Hi @dylandifilippo 👋🏻 

Thanks for reaching out. Could you be more specific as to how the problem you experience manifests itself and provide us a test script we could use to reproduce the issue and assert whether it's related to a bug already? 🙇🏻 

cc @ankur22 @inancgumus

**Comment by inancgumus** [comment]
Hi @dylandifilippo, please ask questions on our community forum using the link: https://community.grafana.com/c/grafana-k6/k6-browser/79. Thank you.
