### ISSUE TITLE
K6 DASHBOARD summary not create while using loadimpact/k6:latest

### ISSUE THREAD

**Issue by fasatrix** [grafana/k6#3751]
### Brief summary

Hi,
this is more of a question as I am unsure it is an actual bug.
Using `loadimpact/k6:latest` within bitbucket pipeline I am unable to create the metric report neither using any of the following commands:
 1. `K6_WEB_DASHBOARD=true K6_WEB_DASHBOARD_EXPORT=metrics.html k6 run --env ENV=$ENV ./$folderName/$scriptName`
 2.` k6 run --env ENV=$ENV --env K6_WEB_DASHBOARD=true --env K6_WEB_DASHBOARD_EXPORT=metrics.html ./$folderName/$scriptName`
3. `k6 run -e ENV=$ENV -e K6_WEB_DASHBOARD=true -e K6_WEB_DASHBOARD_EXPORT=metrics.html ./$folderName/$scriptName`

### k6 version

latest

### OS

Docker image loadimpact/k6:latest

### Docker version and image (if applicable)

loadimpact/k6:latest

### Steps to reproduce the problem

Just run k6 commands above

### Expected behaviour

the `metrics.html` summary is created

### Actual behaviour

the `metrics.html` is not created

**Comment by joanlopez** [comment]
Hi @fasatrix,

After doing some quick checks, it looks like:
- Web dashboard support [was shipped into `v0.49.0`](https://github.com/grafana/k6/blob/master/release%20notes/v0.49.0.md#web-dashboard).
- The `latest` version published under the `loadimpact` organization [is `v0.48.0`](https://hub.docker.com/r/loadimpact/k6/tags).

Please, note the [deprecation announcement](https://hub.docker.com/r/loadimpact/k6) in the DockerHub overview page.

So, I'd say this is not a bug, just expected.
That said, is there any reason why not switching to [`grafana/k6`](https://hub.docker.com/r/grafana/k6)?

Thanks! 🙇🏻

**Comment by fasatrix** [comment]
> Hi @fasatrix,
> 
> After doing some quick checks, it looks like:
> 
> * Web dashboard support [was shipped into `v0.49.0`](https://github.com/grafana/k6/blob/master/release%20notes/v0.49.0.md#web-dashboard).
> * The `latest` version published under the `loadimpact` organization [is `v0.48.0`](https://hub.docker.com/r/loadimpact/k6/tags).
> 
> Please, note the [deprecation announcement](https://hub.docker.com/r/loadimpact/k6) in the DockerHub overview page.
> 
> So, I'd say this is not a bug, just expected.
> 
> That said, is there any reason why not switching to [`grafana/k6`](https://hub.docker.com/r/grafana/k6)?
> 
> Thanks! 🙇🏻

Hey @joanlopez thank you so much for your help. Didn't realized the deprecation.  I have now swapped image. Thx again
