### ISSUE TITLE
Invalid option value exits with code 255 instead of 104 Invalid Config

### ISSUE THREAD

**Issue by oleiade** [grafana/k6#3759]
### Brief summary

As a user, I would expect the following script to make k6 exit with code 104 (`InvalidConfig`):

```javascript
 export const options = {
    vus: 'this is an invalid type',
}

export default function () {}
```

However, when running it, I get the following error message: `ERRO[0000] could not initialize 'invalid-config.js': could not load JS test 'file:///Users/theocrevon/Dev/grafana/sandbox/k6-scripts/exitcodes/invalid-config.js': strconv.ParseInt: parsing "does not exist": invalid syntax`, which I expect.

But `echo $status` (pardon the fish shell syntax) returns 255, which is uint8 for -1, which in my understanding is the "catch all" exit code.

### k6 version

v0.51.0

### OS

MacOS

### Steps to reproduce the problem

`k6 run the-script-above.js`

### Expected behaviour

As a user, I would expect this to set the exit code to 104 `InvalidConfig`.

### Actual behaviour

Sets the exit code to 255 (uint8 equivalent of -1)

**Comment by ariasmn** [comment]
Hi! @oleiade 

Had some free time and decided to open a PR to solve this issue (https://github.com/grafana/k6/pull/3783)

PTAL and let me know what you think!
