### ISSUE TITLE
present setup() function breaks iteration_duration metric

### ISSUE THREAD

**Issue by dvob** [grafana/k6#3799]
### Brief summary

If a setup function is present the iteration_duration metrics are wrong.
It seems that the time used to run `setup()` is incorporated into the `iteration_duration` metric. 

Maybe related to #2718

### k6 version

v0.51.0

### OS

Linux

### Steps to reproduce the problem

* `script.js`
```
import { sleep } from 'k6';

export function setup() {
}

export default function() {
  sleep(1);
}
```

### Expected behaviour

iteration_duration metrics (avg, min, med, max, p(90), p(95)) are all 1s.

```
     data_received........: 0 B 0 B/s
     data_sent............: 0 B 0 B/s
     iteration_duration...: avg=1s min=1s med=1s max=1s p(90)=1s p(95)=1s
     iterations...........: 1   0.999474/s
     vus..................: 1   min=1      max=1
     vus_max..............: 1   min=1      max=1
```

### Actual behaviour

iteration_duration min shows a very low value:
```
     data_received........: 0 B 0 B/s
     data_sent............: 0 B 0 B/s
     iteration_duration...: avg=500.52ms min=1.67µs med=500.52ms max=1s p(90)=900.94ms p(95)=950.99ms
     iterations...........: 1   0.998617/s
     vus..................: 1   min=1      max=1
     vus_max..............: 1   min=1      max=1
```
The time used to run `setup()` is incorporated into the `iteration_duration` metric.
If put a `sleep(1)` into the setup function the metric appears correct.

**Comment by codebien** [comment]
Hey @dvob,
thanks for reporting it.

We are aware of it, you can check details in https://github.com/grafana/k6/issues/3377#issuecomment-1759485940 and https://github.com/grafana/k6/issues/1605.

I'm going to close as it is a duplicate.

**Comment by dvob** [comment]
@codebien thank you for pointing me to the right issue
