### ISSUE TITLE
Memory leak on load generator running large test

### ISSUE THREAD

**Issue by Nova1hhh** [grafana/k6#3822]
### Brief summary

I'm observing a memory leak on a virtual machine running a k6 test. The test is launched through a script file that imports one script and uses it in scenario with ramping-arrival-rate executor. There are two stages: 1 - from zero to 17,000 rps over 2 minutes, 2 - from 17,000 to 17,000 rps for 24 hours. The script is a simple GET request to a service that responds in about 5 ms, with a check for a 200 response code. 
I tried using constant-vus to achieve approximately 17k rps - the result was the same.

Using k6 0.51.0 + xk6-output-influxdb v0.4.3 + xk6-kafka v0.26.0. 
Sending messages to Kafka and metrics to InfluxDB are not used.

### k6 version

0.51.0

### OS

Astra Linux (16 cpu\64 ram)

### Steps to reproduce the problem

Run a k6 scenario that successfully generates 17k rps to the service.

### Expected behaviour

Get constant resource utilization of the generator under constant load.

### Actual behaviour

64 GB of memory is gradually utilized over approximately 6 hours of load at 17k rps. The response time of the targeted service, the number of requests, and resource utilization are normal.

**Comment by Nova1hhh** [comment]
additional: GET requests are sent to the same URL.

**Comment by mstoykov** [comment]
Hi @Nova1hhh, I see that you are using two different outputs, but are you also setting `--no-thresholds --no-summary` as recommended in the [Running large tests](https://grafana.com/docs/k6/latest/testing-guides/running-large-tests/#when-streaming-use---no-thresholds-and---no-summary). 

You can also see #2367 and the linked issues in the first comment (among others).

**Comment by mstoykov** [comment]
I am closing this issue - I expect that the above comment by me is the case and it has been a month since the last communicaiton by @Nova1hhh
