### ISSUE TITLE
File logger sometimes misses last log line sent from output extension

### ISSUE THREAD

**Issue by roobre** [grafana/k6#3843]
### Brief summary

In SM we use an output extension to output metrics in a particular format for our consumption. This output extension also outputs a log line for each `check` in the script:

https://github.com/grafana/synthetic-monitoring-agent/blob/d9a40a5294f7c94e15d15fdbbc8570ac8447b6c4/xk6/sm/output.go#L153

Which looks like this:

```
time="2024-07-12T21:11:22+02:00" level=info msg="check result" check="response code was 200" metric=checks_total scenario=default source=sm value=1
```

We have recently noticed, however, that in some executions this log line does not appear, for the same script.

I made a hacky script that runs k6 continuously and checks if the log line is missing, and this seems to happen once every ~100 iterations, meaning that in ~1% of the cases that log line is not printed.

With the reproduction script I was able to narrow down a bit what's going on:
- This does not seem to happen for log lines printed within the script via `console.log`, or at least not in 10k iterations
- This only happens when `--log-output` is a file
- This happens more often if `--verbose` is used.

Digging a bit I suspect the reason for this lies here:

https://github.com/grafana/k6/blob/04b53e43dcca312d2684713cea9185c0643304c3/log/file.go#L113-L128

I suspect it might be possible for the context to get cancelled while there are still log lines on the channel. I crudely patched k6 to yell if there are still stuff on the channel when the context is done:

```patch
diff --git a/log/file.go b/log/file.go
index 6da7e94b..ab34e9f6 100644
--- a/log/file.go
+++ b/log/file.go
@@ -116,6 +116,12 @@ func (h *fileHook) Listen(ctx context.Context) {
 				h.fallbackLogger.Errorf("failed to write a log message to a logfile: %w", err)
 			}
 		case <-ctx.Done():
+			select {
+			case <-h.loglines:
+				h.fallbackLogger.Errorf("Pending log lines found")
+			default:
+			}
+
 			if err := h.bw.Flush(); err != nil {
 				h.fallbackLogger.Errorf("failed to flush buffer: %w", err)
 			}
```

Running the reproduction script, I can see `Pending log lines found` in the same execution where the log line is missing.

From what I can see, k6 is doing everything right concurrency wise, but I _think_ this may be happening because logrus might be calling hooks on a separate goroutine, which is not synchronized with anything. If this were the case, it would explain this sometimes failing, as the output extension's `Stop()` method is invoked reasonably shortly before calling `stopLoggers()`, which triggers the cancellation of that context (by means of https://github.com/grafana/k6/blob/04b53e43dcca312d2684713cea9185c0643304c3/cmd/root.go#L277)

I'm not sure what a possible solution for this would look like.

### k6 version

k6 v0.52.0 (go1.22.5, linux/amd64)

### OS

Arch linux

### Steps to reproduce the problem

1. Build k6 with an output extension that logs something on `Stop()`
2. Run any k6 script with `--log-ouput=file=something` and `--verbose` (`--verbose` makes it more likely to happen)
3. Repeat 2 100 times or so
4. Observe that sometimes, the log line is missing

### Expected behaviour

Log lines should always be there.

### Actual behaviour

Log line is sometimes missing.

**Comment by roobre** [comment]
Kay, I have might found a flaw in the k6 logic for closing this logger. My understanding of how this works when `k6 run` is invoked

1. Root command's `PersistentRunE` runs. [`setupLoggers`](https://github.com/grafana/k6/blob/04b53e43dcca312d2684713cea9185c0643304c3/cmd/root.go#L78) is called, whic calls [`setLoggerHook`](https://github.com/grafana/k6/blob/04b53e43dcca312d2684713cea9185c0643304c3/cmd/root.go#L265). A separate goroutine [is spun up](https://github.com/grafana/k6/blob/04b53e43dcca312d2684713cea9185c0643304c3/cmd/root.go#L287) for `Listen`, which is the one consuming log entries.
2. The run function runs.
3. During run, the extension logs stuff. ⚠️ Logs are swallowed without waiting for them to be consumed by `Listen` because [the channel is buffered](https://github.com/grafana/k6/blob/04b53e43dcca312d2684713cea9185c0643304c3/log/file.go#L42). This is what I missed on my first analysis.
4. Run finishes, `stopLoggers` is called, and after some channel/context dance, the context [`Listen`](https://github.com/grafana/k6/blob/04b53e43dcca312d2684713cea9185c0643304c3/log/file.go#L111) has is cancelled. The select inside randomly decided whether to suck pending log lines, or terminate.
5. If we're unlucky, pending lines remain in the buffered channel.

**Comment by mstoykov** [comment]
Hi, I looked into this and did some testing, and went to have lunch while you were commenting :sweat_smile: .

We do have async log handling in the file hook as it is based on the loki one - where you need to buffer log lines either way, and it was fairly important when it was developed that this doesn't block on `console.log`. 

In retrospect both the loki, and the file implementation, likely doesn't need this that much. On the other hand we still need to flush/sync on exiting the process (especially on errors where we will use OsExit).

I tried to close the channel and it *works*, but looking over the code it seems like there could be raises on errosr where while we are closing, something still writes logs :(. So I don't think this is a good idea after all.

If the fix you proposed works well enough for your case I would prefer we do it like this and leave it as we would want to replace logrus ... one day. But that realistically won't be fast :(.

**Comment by roobre** [comment]
> there could be raises on errosr where while we are closing, something still writes logs :(. So I don't think this is a good idea after all.

If this happens, the patch I proposed will either ignore those logs, or keep consuming them until `stopLoggers` [times out](https://github.com/grafana/k6/blob/6116f7b97cc55d7c1ee9a73c28e721c64e1d8b32/cmd/root.go#L149), if I'm not mistaken.

I'm personally not sure whether that's better than panicking, so I'll leave it up to your best judgement 😄
