### ISSUE TITLE
No data on k6 inspect

### ISSUE THREAD

**Issue by ameetpal** [grafana/k6#3890]
### Brief summary

On running K6 inspect test.js, Most of the values are null especially duration
`{
  "paused": null,
  "vus": null,
  "duration": null,
  "iterations": null,
  "stages": [
    {
      "duration": "20s",
      "target": 1
    },
    {
      "duration": "20s",
      "target": 2
    },
    {
      "duration": "20s",
      "target": 1
    }
  ],
  "scenarios": null,
  "executionSegment": null,
  "executionSegmentSequence": null,
  "noSetup": null,
  "setupTimeout": null,
  "noTeardown": null,
  "teardownTimeout": null,
  "rps": null,
  "dns": {
    "ttl": null,
    "select": null,
    "policy": null
  },
  "maxRedirects": null,
  "userAgent": null,
  "batch": null,
  "batchPerHost": null,
  "httpDebug": null,
  "insecureSkipTLSVerify": null,
  "tlsCipherSuites": null,
  "tlsVersion": null,
  "tlsAuth": null,
  "throw": null,
  "thresholds": null,
  "blacklistIPs": null,
  "blockHostnames": null,
  "hosts": null,
  "noConnectionReuse": null,
  "noVUConnectionReuse": null,
  "minIterationDuration": null,
  "ext": null,
  "summaryTrendStats": null,
  "summaryTimeUnit": null,
  "systemTags": null,
  "tags": null,
  "metricSamplesBufferSize": null,
  "noCookiesReset": null,
  "discardResponseBodies": null
}`

I am using the following testscript
`import { check } from 'k6';
import http from 'k6/http';

export const options = {
    "stages": [
      { "target": 1, "duration": "20s" },
      { "target": 2, "duration": "20s" },
      { "target": 1, "duration": "20s" }
    ]
  }

export default function () {

  const result = http.get('https://test-api.k6.io/public/crocodiles/');

  check(result, {
    'http response status code is 200': result.status === 200,
  });
}
`

### k6 version

0.49

### OS

macOs 14.5

### Steps to reproduce the problem

k6 inspect test.js

### Expected behaviour

Returning duration of test

### Actual behaviour

duration is null

**Comment by mstoykov** [comment]
Hi @ameetpal, 

`k6 inspect` originally (and still) mostly just goes through the test and recalculates it's configuration. `duration` in this case is if you the user have  set the `duration` confuration. Not the total duration. 

Calculating the total duration is:
1. more involved
2. not actually accurate - as it is the maximum duration for some of the [scenario executors](https://grafana.com/docs/k6/latest/using-k6/scenarios/executors/)

You can get the estimate by providing `--execution-requirements` to `k6 inspect` and looking at the `totalDuration` field.

Hope this helps you!
