### ISSUE TITLE
Module discovery

### ISSUE THREAD

**Issue by ameetpal** [grafana/k6#3937]
There is `inspect` command to get duration of the test, is there any similar command for getting which extension is used by a particular script like xk6-kafka, xk6-stomp etc

**Comment by ameetpal** [comment]
Also there is an extension named xk6-temporal are you actively maintaining it ? As we are thinking of using it.

**Comment by olegbespalov** [comment]
Hey @ameetpal 

Currently, there is no such thing in stock version of k6. However, there is a separate project, https://github.com/grafana/k6deps, that aims to do that.

>The goal of k6deps is to extract dependencies from k6 test scripts. For this purpose, k6deps analyzes the k6 test scripts and the modules imported from it in a recursive manner.

**Comment by ameetpal** [comment]
@olegbespalov  Is there similar dependency used for calculating of test duration

**Comment by olegbespalov** [comment]
> Is there similar dependency used for calculating of test duration

@ameetpal I'm not quite sure if I follow, you can calculate test duration by using `k6 inspect` itself

**Comment by olegbespalov** [comment]
I'm closing this issue for now because it didn't need to be addressed. Please feel free to re-open if something new appears.
