### ISSUE TITLE
Test terminated with exit code 2

### ISSUE THREAD

**Issue by ameetpal** [grafana/k6#3962]
We are using K6-operator to run an 8 hour test, but it only ran for 5 hours and exited with exit code 2, there was no error log and resources were also sufficient, do anyone knows what exit code 2 signifies ?

On further investigating, i found that if there is panic in main thread or in output extension it may result in an exit code

Please provide some assistance around this

**Comment by ameetpal** [comment]
any update here ?

**Comment by mstoykov** [comment]
Hi @ameetpal , sorry for the slow reply 🙇 

exit code 2 is coming directly from golang and AFAIK it always means a panic of some kind. So the expectation is that you will have a message along with it explaining the panic.

For long tests I expect the most likely case will be OOM. 

I am not working with k6-operator, so maybe someone with more experience can help you find the logs.

cc @yorugac

**Comment by ameetpal** [comment]
Hi @mstoykov , OOM is not happening but i am suspecting, prometheus extension might be panicing but i am not able see error message. Every thing happen so quickly that pod crashed

**Comment by mstoykov** [comment]
I don't know how to help you @ameetpal if there is no additional data to go on.

If you think the prometheus extension is panicking, maybe try to get it to panic outside of k8s ? 

If you do not get error logs out of this, I would argue this might be a good first thing to fix as it is important to know what went wrong.
