### ISSUE TITLE
Uncaught (in promise) browser not found in registry. make sure to set browser type option in scenario definition in order to use the browser module

### ISSUE THREAD

**Issue by rgrygorovych** [grafana/k6#3973]
### Brief summary

The issue you're encountering appears to stem from the addition of the `--duration 60s` flag when running your k6 performance tests. Previously, the tests executed without any errors, but now you are seeing repeated error messages indicating that the "browser not found in registry." This suggests that when the duration flag is specified, the k6 CLI is not recognizing the browser type defined in your scenario.

When you remove the `--duration 60s` flag, the tests run correctly, utilizing the configuration set in your `smoke.json` file, which specifies the browser type (Chromium) in the scenarios section. 

Your execution details indicate you're using k6 v0.54.0, and the error messages suggest a potential conflict or oversight in how the browser module is being initialized with the duration flag. This unexpected behavior should be investigated further, as it is not aligning with the intended functionality.

### k6 version

0.54.0

### OS

Linux

### Steps to reproduce the problem

Hi Team, I recently started to get an errors where I was not expected to see, check the log output below.

While debugging the issue for test that worked fine before (not entirely sure about this), the issue seems to caused by adding duration flag to the k6 cli. And I do not think so it is aactually expected behaviour.

`npm run bundle && K6_BROWSER_HEADLESS=false k6 run -c config/smoke.json tests/xxxxxxxx.js -e APP_BASE_URL="https://xxxxxxx.xxx" -e APP_ENVIRONMENT="xxx" --include-system-env-vars --insecure-skip-tls-verify --duration 60s`

Removing the `--duration 60s` will work absolutely fine, the test will start with the options set in the `smokde.json` file.

```
...
"scenarios": {
    "browser": {
      "executor": "constant-vus",
      "exec": "default",
      "vus": 1,
      "duration": "30s",
      "options": {
        "browser": {
          "type": "chromium"
        }
      }
    }
  },
...
```

My execution details:
```
k6 v0.54.0 (go1.23.1, darwin/arm64)
"@types/k6": "^0.53.2"
```

### Expected behaviour

The tests executed successfully and i see the logs coming from my test implementation and browser extension.

### Actual behaviour

The tests fails producing thousands of log message like below:

```
...
ERRO[0002] Uncaught (in promise) browser not found in registry. make sure to set browser type option in scenario definition in order to use the browser module  executor=constant-vus scenario=default
ERRO[0002] Uncaught (in promise) browser not found in registry. make sure to set browser type option in scenario definition in order to use the browser module  executor=constant-vus scenario=default
ERRO[0002] Uncaught (in promise) browser not found in registry. make sure to set browser type option in scenario definition in order to use the browser module  executor=constant-vus scenario=default
ERRO[0002] Uncaught (in promise) browser not found in registry. make sure to set browser type option in scenario definition in order to use the browser module  executor=constant-vus scenario=default
ERRO[0002] Uncaught (in promise) browser not found in registry. make sure to set browser type option in scenario definition in order to use the browser module  executor=constant-vus scenario=default
...
```

**Comment by olegbespalov** [comment]
Hi @rgrygorovych!

Unfortunately, it's a known UX issue/bug, as it was described in:

* https://github.com/grafana/k6/issues/3742
* https://github.com/grafana/k6/issues/3741

The predominant problem here is that [a flag `--duration`](https://grafana.com/docs/k6/next/using-k6/k6-options/reference/#duration) is a shortcut to a single scenario with a constant VUs executor, so it does not overwrite the duration your scenario.

So I could suggest, in your case, switching to the environment variables, like:

```js
export const options = {
	vus: 1,
	duration: __ENV.TEST_RUN_DURATION || '30s',
};
```

and later on, pass the variable:

```bash
k6 run -e TEST_RUN_DURATION=33s script.js
```

I'm closing this task as a duplicate, but feel free to provide more details/feedback on the existing issues to give them a thumbs up, which is the signal for us that it's been reminded.
