### ISSUE TITLE
Contribution.md Style Guide Hyperlink points to incorrect resource

### ISSUE THREAD

**Issue by tarunsunny3** [grafana/k6#4012]
https://github.com/grafana/k6/blob/master/CONTRIBUTING.md

![Image](https://github.com/user-attachments/assets/e1e9c0f1-db56-49f1-a2de-0e581969fe26)

the style-guide now points to #style-guide, but a subsection with that name doesn't exist.

It should point to the below #code-style subsection? or some other one?

![Image](https://github.com/user-attachments/assets/8e97ac92-37c8-4ddf-b67a-c19610d5d335)

**Comment by tarunsunny3** [comment]
I want to work on this, excited to make my first OSS contribution

**Comment by oleiade** [comment]
Thanks for your interest in contributing to k6 @tarunsunny3 👏🏻 🚀 

I think your assumption about the broken link is correct indeed. Feel free to open a PR to suggest the change 🙇🏻
