### ISSUE TITLE
Report whether a test was run from a CI environment in usage report data

### ISSUE THREAD

**Issue by oleiade** [grafana/k6#4038]
### Feature Description

k6 collects anonymized usage data with users content. In order to help us continue improving k6, we would like to add the information whether a test was run in a CI environment to such report.

### Suggested Solution (optional)

The currently proposed solution is to look for the `CI` variable in the system's environment, and if set, update the usage report data accordingly (as proposed by @joanlopez).

**Comment by oleiade** [comment]
PS: The first naive solution sounds rather cheap to implement, and I'd really like to see this land in v0.56.0. What do you think @joanlopez @andrewslotin ?

**Comment by joanlopez** [comment]
> PS: The first naive solution sounds rather cheap to implement, and I'd really like to see this land in v0.56.0. What do you think [@joanlopez](https://github.com/joanlopez) [@andrewslotin](https://github.com/andrewslotin) ?

It's likely going to be straightforward to implement, and I don't see many risks and/or potential blockers, beyond deciding how to name that indicator, and filling with a boolean stating whether the `CI` environment variable is defined or not.

Any other concerns? cc/ @grafana/k6-core

**Comment by andrewslotin** [comment]
I like this proposal! Looks like a small change that would help us to understand how k6 is used in real life. Let do this!

**Comment by oleiade** [comment]
Cheers folks, adding it to v0.56.0 milestone 👍🏻
