### ISSUE TITLE
Test is aborted by system due to its own internal error

### ISSUE THREAD

**Issue by JadaVonRuth** [grafana/k6#4046]
### Brief summary

Hello there, 

I am experiencing severe problem with K6 tests, I am using bodies to spawn additional requests where I randomly select data for another request so I cannot really use discard bodies option. When all stages are finished test never completes and keeps running until it is aborted by system few minutes later despite no real activity on api happening.  What might be worth mentioning some of the endpoints are returning large jsons (~10MB) assuming that might be the issue. 

In k6 cloud dashboard it show error: TEST ERROR DETAIL: An internal system error has occurred, please contact support for more details.

![Image](https://github.com/user-attachments/assets/24ba78f0-2deb-4be5-889e-a56131004085)

Anyway if response sizes are the problem due to insufficient memory, current behavior is still not OK since we are paying money for this and god know how it affects the reports. There are no limits regarding to this mentioned anywhere. 

So I am contacting the support

### k6 version

v0.50.0 (commit/f18209a5e3, go1.21.8, windows/amd64)

### OS

Windows 10

### Steps to reproduce the problem

Our tests are kinda complex so there are no easy steps to describe but I will try

1. 300 VUs 
2. Every endpoint uses response to call another
3. Random sleeps between those
4. 2 of the endpoints returns large jsons
5. Test length 4:30 minutes in total

### Expected behaviour

Tests finishing normally

### Actual behaviour

Test fails

**Comment by mstoykov** [comment]
Hi @JadaVonRuth 

You clearly are a customer of Grafana Cloud k6. While the k6 cli project is used within the cloud, this is not the correct place to report issues with the service or ask for support directly connected with it. 

Please contact grafana cloud support, this way they can provide more data, and you will be able to find more info on your particular case.
