### ISSUE TITLE
Expose HTTP Request ID in Scripts

### ISSUE THREAD

**Issue by akefirad** [grafana/k6#4061]
### Feature Description

Hi there,

I searched quite a bit in the docs and other places, and couldn't find if this exists as a feature. So hopefully this is not a false report.
Can we have the request ID generated by k8 while running HTTP tests?

### Suggested Solution (optional)

I don't know enough about k8 to make any suggestion.

### Already existing or connected issues / PRs (optional)

There are clear ways to generate request ID in the script and use it (for example as `X-Request-Id` header), but what I'm looking for is to use the ID generated by k8s, because it shows up in the http-debug log and it's convenient to just use the same ID.

**Comment by kempsterc** [comment]
@akefirad 
I just added my own 🤷‍♀️
In the Params
