### ISSUE TITLE
To contribute on xk6-temporal extension

### ISSUE THREAD

**Issue by prmuthu** [grafana/k6#4079]
### Feature Description

Hi Team,

We have requirement to run loadtest on temporal workflows, for that we have cloned the xk6-temporal extension and customized it to run the test. Planning to contribute the same into public repository. 
@mstoykov  can i contribute in existing xk6-temporal extension if someone unarchive this repo, otherwise can someone delete it and i will create a new repo with same name.

**Comment by mstoykov** [comment]
Hi @prmuthu, as mentioned before the k6 team has no affiliation with the xk6-temporal extension. At no point were we maintainers or administrators of the [xk6-temporal repo](https://github.com/temporalio/xk6-temporal) and have never been.

We can 't unarchive it and the k6 team does *not* want to maintain this extension or the code it has.

You should be the one forking the repo and making the necessary changes to the fork to make it work. There is no need for the repo to be deleted either - you can have the same named repo under your organization.

I am closing this issue as there is nothing to be done.
