### ISSUE TITLE
Cannot install k6 rpm

### ISSUE THREAD

**Issue by JBWatenbergScality** [grafana/k6#4087]
### Brief summary

When running below command:

```
sudo dnf install https://dl.k6.io/rpm/repo.rpm
```

I'm getting the following error:

```
Errors during downloading metadata for repository '[dl.k6.io](http://dl.k6.io/)':
 - Status code: 403 for https://dl.k6.io/rpm/repodata/repomd.xml (IP: 3.164.240.81)
Error: Failed to download metadata for repo '[dl.k6.io](http://dl.k6.io/)': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried
```

### k6 version

any

### OS

rocky 8.9

### Steps to reproduce the problem

```
sudo dnf install https://dl.k6.io/rpm/repo.rpm
```

### Expected behaviour

No 403 when installing k6.

### Actual behaviour

Cannot install k6 (getting a 403).

**Comment by mstoykov** [comment]
Thanks for reporting this @JBWatenbergScality 🙇 

This seems strange:
1. it works for me with no problems
2. the actual file is https://dl.k6.io/rpm/x86_64/repodata/repomd.xml and my fedora 41 get this correctly

By the looks of it in `.repo` file your system doesn't expand $basearch or something else is happening. 

Can we confirm you have not done anything strange to the repo file and that some other repo with `$basearch` in its repo files is working? 

The repo files for me are under `/etc/yum.repos.d/`, no idea how that is for rocky linux.

**Comment by JBWatenbergScality** [comment]
Thanks this was indeed on my side, I got some issues in my repos files and sort this out ! Sorry for the noise !
