### ISSUE TITLE
Optimize test suite

### ISSUE THREAD

**Issue by na--** [grafana/k6#537]
Currently the test suite is somewhat slow, and would probably become even slower after we [start using the `-race` flag](https://github.com/loadimpact/k6/issues/536) and add more tests. Steps:

- [x] [Stop relying on httpbin.org](https://github.com/loadimpact/k6/issues/464) for a lot of our tests.
- [ ] Investigate if there are other external services that could be easily replaced as well. Remove them if there are, create issues for future releases if not.
- [x] Enable parallel execution of tests wherever possible with [`t.Parallel()`](https://golang.org/pkg/testing/#T.Parallel). This should happen after the [race conditions are fixed](https://github.com/loadimpact/k6/issues/536) if we want to avoid headaches. 
- [ ] Investigate the test suite for any outliers with slow test execution. If there are any quick wins we could get by optimizing specific tests with minimal effort, fix them directly. Otherwise - document in separate issues.

**Comment by na--** [comment]
Here are some of the external URLs I've noticed that we depend on in the unit tests while replacing httpbin:
- demos.kaazing.com (for websockets, should be easy to replace)
- http2.akamai.com (should be easy to replace)
- badssl.com (probably requires some time investment if there's no suitable Go library that mimics it)
- stackoverflow.com (for checking for good OCSP status, we probably can't avoid an external call here...)
Others, if there are, should pop up when the above are fixed and we run the tests locally without an internet connection.

**Comment by na--** [comment]
Something else that popped up, it seems like some of the tests can have huge memory leaks: https://github.com/loadimpact/k6/pull/814
Further investigation definitely needed...

**Comment by MStoykov** [comment]
I am closing this as all but 1 change was made, and I have moved it to a specific issue https://github.com/grafana/k6/issues/2302, please if any specific problems are noticed – open a specific issue for them instead of an “epic”.
