### ISSUE TITLE
got "incorrect header check" when invoke pako.inflate during websocket test

### ISSUE THREAD

**Issue by wallenZhao2046** [grafana/k6#594]
I am executing a websocket testing using K6. 
when handling ws response, I need to inflate the content. and I tried to use pako to do that.
The following is my script. I found pako can't deflate string and inflate either. 
I tried the same code in node.js, fount it worked well. Is there anything wrong?

``` javascript
import ws from "k6/ws";
import { check } from "k6";
import pako from './pako.js';

export default function() {
  var url = "ws://api.xxx.pro/ws";
  var params = { "tags": { "my_tag": "hello" } };
  var res = ws.connect(url, params, function(socket) {
    socket.on('open', function() {
      socket.send('WebSocket rocks');

     //begin--------
     // the following code is to test whether pako working in K6
     let data = { ping: "12345678"};
     console.log(JSON.stringify(data));
     let binStr = pako.deflate(JSON.stringify(data), {to:'string'});
     console.log(binStr);
     let text = pako.inflate(binStr, {
            to: 'string'
     });
     //end: ------------

    });

    socket.on('message', function(data) {
      // .....
    }); 
```

the error message is 
```
INFO[0004] !!!!!!!

ERRO[0004] incorrect header check
	at inflate (/Users/zh/workspace/test_files/k6_files/pako_out.js:803:45(24))
	at /Users/zh/workspace/test_files/k6_files/ws_base_test.js:24:50(76)
```

**Comment by wallenZhao2046** [comment]
@na-- It was fixed. Thanks a lot ! By the way, I got a reply message when I connected to a websocket server, and I printed it in console got a strang string code like "�V*��KW�245215�0145�0�����". How can I uncompress it? Do you have any idea?

**Comment by na--** [comment]
Sorry, I'm not sure what the reason is, maybe the server just uses the websockets to send some sort of binary data? In any case, that discussion is something that's more suited to the #support channel of the k6 slack, so I'm closing this issue for now.

**Comment by wallenZhao2046** [comment]
@na-- You are right. This issue is not a bug. Thanks for your reply.

**Comment by na--** [comment]
As seen [here](https://stackoverflow.com/questions/50128949/k6-k6-websocket-how-to-decode-compressed-text-in-k6/50129281#50129281), it seems like this could indeed be a bug in the goja runtime or somewhere in the JavaScript stack (babel, core.js/etc.), so I'm reopening this issue.

**Comment by MStoykov** [comment]
The error in StackOverflow would probably be as `data` is a string but after #1799 it should now be possible to get it as ByteArray and use that?

**Comment by mstoykov** [comment]
I am closing this as the error that was provided in the original report is no longer happening since k6 v0.26.2 but was present up to v0.25.1.

 This likely was fixed by a goja update at some point and we just didn't notice
