### ISSUE TITLE
Add functional tests to CI to validate load test feature functionality

### ISSUE THREAD

**Issue by StephenRadachy** [grafana/k6#625]
It's great to see that Unit testing + code coverage is ramping up and that the CLI is functionally being tested, however I would like to see functional load tests - so that we can validate that individual features (such as custom metrics) work as advertised and help prevent future bugs.

**Comment by na--** [comment]
I agree, this is something that I'd also like to have. 

I'd say that some of the current tests are at least partially functional, but we definitely should have more and better ones. For example, [those two tests](https://github.com/loadimpact/k6/blob/master/core/engine_test.go#L495-L751) (and others that parse and realistically execute a full test script with some options) are very useful for catching a lot of bugs, but we don't have enough of them and we can probably go more end-to-end.

**Comment by oleiade** [comment]
We believe this to have been addressed over time, and the team decided to close this issue.

In the event parts or the whole of this problem were judged to be still relevant, please feel free to open smaller, more specific issues detailing it further 🙇🏻
