### ISSUE TITLE
Iterations count in InfluxDB is lower than what k6 reports

### ISSUE THREAD

**Issue by RobinsonWM** [grafana/k6#636]
When using k6 with InfluxDB output, we noticed the iterations count in InfluxDB is ~1% lower than the iterations count in the k6 console output.  I'm trying to understand whether this is a bug in k6's InfluxDB reporting or if I'm misunderstanding how to read the metrics in InfluxDB.

While our real test saw a ~1% discrepancy, we were able to reproduce a much larger discrepancy with a script that ran very fast:
```javascript
export let options = {
    iterations: 10424
};

export default function() {}
```

We tested it this way, using a new database name (k67 in this case) each time:
```sh
k6 run noop.js --out influxdb=http://localhost:8086/k67
```

As expected, the k6 output showed 10424 iterations and no errors:
```noformat
          /\      |‾‾|  /‾‾/  /‾/
     /\  /  \     |  |_/  /  / /
    /  \/    \    |      |  /  ‾‾\
   /          \   |  |‾\  \ | (_) |
  / __________ \  |__|  \__\ \___/ .io

  execution: local-
     output: influxdb=http://localhost:8086/k67 (http://localhost:8086)
     script: noop.js

    duration: -,  iterations: 10424
         vus: 1, max: 1

    done [==========================================================] 10424 / 10424

    data_received........: 0 B   0 B/s
    data_sent............: 0 B   0 B/s
    iteration_duration...: avg=55.94µs min=0s med=0s max=10.74ms p(90)=0s p(95)=0s
    iterations...........: 10424 14825.217034/s
    vus..................: 1     min=1 max=1
    vus_max..............: 1     min=1 max=1
```

However InfluxDB unexpectedly reported a much lower iteration count:
```noformat
> use k67
Using database k67
> select count(*) from iterations
name: iterations
time count_value
---- -----------
0    494
> select sum(*) from iterations
name: iterations
time sum_value
---- ---------
0    494
```

I tried adding a short sleep to the script (`sleep(.001);`), and the problem went away.

Are the iterations in InfluxDB intended to match the number of iterations that actually ran?  I am curious if two iterations start at the same time, if k6 reports them to InfluxDB with the same timestamp, which means InfluxDB collapses them into a single data point:
https://docs.influxdata.com/influxdb/v0.13/troubleshooting/frequently_encountered_issues/#writing-duplicate-points

Should k6 track when multiple iterations have the same timestamp, and in that case report a `value` higher than 1 to InfluxDB?

**Comment by na--** [comment]
> Are the iterations in InfluxDB intended to match the number of iterations that actually ran? 

Yes

> I am curious if two iterations start at the same time, if k6 reports them to InfluxDB with the same timestamp, which means InfluxDB collapses them into a single data point:
> https://docs.influxdata.com/influxdb/v0.13/troubleshooting/frequently_encountered_issues/#writing-duplicate-points

This seems very likely. [Here](https://docs.influxdata.com/influxdb/v1.5/troubleshooting/frequently-asked-questions/#how-does-influxdb-handle-duplicate-points) is the latest influxdb documentation which says basically the same thing.

Can you try running the same test (without sleep) but with the `iter` [system tag](https://docs.k6.io/docs/tags-and-groups#section-system-tags) enabled. Basically something like this:
```
k6 run noop.js --system-tags "name,group,iter" --out influxdb=http://localhost:8086/k67
```
If that "fixes" it, then it's safe to assume that you've correctly diagnosed the issue.

> Should k6 track when multiple iterations have the same timestamp, and in that case report a value higher than 1 to InfluxDB?

I think that we should do that, so I'm tagging this a bug for now.

**Comment by RobinsonWM** [comment]
When I tried it with `--system-tags "name,group,iter"`, I saw the same results.  I think something else is wrong though, because I don't see any of those tags on the `iterations` measurement in InfluxDB.  In both cases, I see only the `value` field and no tags.  I'm using k6 0.2.0 and Influx 1.5.2-1.

**Comment by na--** [comment]
A recent report of the same issue in the community forum: https://community.k6.io/t/k6-to-influxdb-with-lesser-http-req-duration-data/1604

I think it's probable that we don't currently send the timestamps in nanoseconds, since if we did, I doubt we'd have so many collisions... But when switching to InfluxDB v2 (https://github.com/k6io/k6/issues/1730), we might want to have that option, since it should greatly ameliorate the issue: https://docs.influxdata.com/influxdb/v2.0/write-data/best-practices/duplicate-points/#increment-the-timestamp

**Comment by MStoykov** [comment]
But ... we already push them in nanoseconds precision, that is configurable

https://github.com/k6io/k6/blob/e5d4d82d16c0c86154f017971f4233b43702165d/stats/influxdb/config.go#L51

and by default it is nanoseconds or so they say in some parts of the client  code 

https://github.com/influxdata/influxdb1-client/blob/b269163b24ab8e62026d13a92aa988a7389c3b4e/v2/client.go#L65-L67

**Comment by na--** [comment]
Not sure why there are so many collisions then, it should be fairly difficult to generate the same metrics with the same nanosecond  timestamp from different VUs :confused: Maybe there is some configuration on the InfluxDB serves that truncates the precision to something less than a nanosecond, regardless of what we send?

**Comment by olegbespalov** [comment]
I've double-checked with a suggested scenario, and in my case, it works as expected. Closing the issue, and if more details appear, let's re-open it.
