### ISSUE TITLE
Support load test on SAML SSO Secured Websites

### ISSUE THREAD

**Issue by luizbafilho** [grafana/k6#646]
A user in Slack asked for being capable of testing SAML SSO Secured Websites. He linked an article on how to do it with Jmeter it might be helpful.

https://dzone.com/articles/how-to-load-test-saml-sso-secured-websites-with-jm

**Comment by olegbespalov** [comment]
It seems like the issue fits better: https://github.com/grafana/k6-docs/. Closing it here, and if it should be re-opened, it's better to do this in an appropriate repository.
