### ISSUE TITLE
regeneratorRuntime is not defined

### ISSUE THREAD

**Issue by chrisgodsey** [grafana/k6#706]
When attempting to utilize ES6 modules with async/await, I'm receiving the message:

"ReferenceError: regeneratorRuntime is not defined at [line where async is declared]"

Googling around points that this is a babel error, with led me to this issue:

https://stackoverflow.com/questions/33527653/babel-6-regeneratorruntime-is-not-defined

This would lead me to believe k6 needs babel-polyfill inside of it to be able to allow utilization of async/await methods

**Comment by cesarvarela** [comment]
Is there any workaround for this?(besides not using `await`)

**Comment by chrisgodsey** [comment]
I fiddled around with it for awhile but took the path of least resistance and stopped using async/await for now.

**Comment by RyderKishan** [comment]
Hope you should look at this guide and follow with the next part 

https://medium.com/@kishan020696/react-16-with-webpack-4-and-babel-7-7befed102817

**Comment by MStoykov** [comment]
I am closing this PR, as the babel plugins that were doing the transformation leading to the error haven't been enabled for quite sometime now.

As mentioned [here](https://github.com/grafana/k6/issues/779#issuecomment-964027280) I am kind of against enabling them again, but it also includes a workaround for the people who need to at least not get syntax errors with `async`/`await` keywords and are willing to compile their own k6 (for now) and also are willing to risk it that it probably doesn't work okay and might change in the future when it's actually implemented - In other words, you probably shouldn't use it ;)
