### ISSUE TITLE
Install instructions for Debian fail on Debian 9

### ISSUE THREAD

**Issue by neilstuartcraig** [grafana/k6#854]
When following the current install instructions for Debian under Debian 9 (stable), we get:
```
# sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 379CE192D401AB61
Executing: /tmp/apt-key-gpghome.a1OvMDPiZN/gpg.1.sh --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 379CE192D401AB61
gpg: failed to start the dirmngr '/usr/bin/dirmngr': No such file or directory
gpg: connecting dirmngr at '/tmp/apt-key-gpghome.a1OvMDPiZN/S.dirmngr' failed: No such file or directory
gpg: keyserver receive failed: No dirmngr
```

This can be fixed by first running:
```
apt-get update
apt-get install dirmngr
```

Not sure how best to add that to the doc as it might only be true for Debian 9 so I thought i'd raise the issue rather than making a PR.

EDIT:
Also, the next step fails too so you have to also run:
```
apt-get install apt-transport-https
```

Then the installation can proceed.

(this was all tested on a Google Cloud VM by the way)

**Comment by imiric** [comment]
Debian 9 was EOL'd on July 1 2022, so we don't need to mention installing `dirmngr` anymore. I tested [our current installation instructions](https://k6.io/docs/get-started/installation/#debian-ubuntu) on Debian 10, and they work fine.

We also mention installing `ca-certificates` on the [Troubleshooting page](https://k6.io/docs/get-started/installation/troubleshooting/#system-lacks-ca-certificates-or-gnupg2), which would fix `apt-get install` if it fails.

So I don't think we need to anything here. Sorry for the super-late response! :sweat_smile:
