### ISSUE TITLE
OpenMetrics support

### ISSUE THREAD

**Issue by marcuslindfeldt** [grafana/k6#858]
[OpenMetrics](https://github.com/OpenObservability/OpenMetrics) is aiming to be the standard for exposing metrics data and is already being adopted by many popular projects.

If k6 would expose metrics in this format we would not be limited to using influxDb to store loadtest metrics.

[OpenCensus](https://opencensus.io/) seems like a good library for instrumentation.

**Comment by liclac** [comment]
I would like to add that OpenMetrics is under the [CNCF umbrella](https://www.influxdata.com/blog/openmetrics-joins-cncf/) as it moves towards a stable spec.

The Prometheus metrics format, which this is based on, is already a de-facto standard.

**Comment by juwatanabe** [comment]
+1 this feature request

**Comment by olegbespalov** [comment]
Closing in favor of the https://github.com/grafana/k6/issues/2557
