### ISSUE TITLE
New metric to measure sleep times

### ISSUE THREAD

**Issue by na--** [grafana/k6#880]
In certain situations, it may be useful to have a measurement of how much time k6 spent in `sleep()` calls. This should probably be done after we have implemented https://github.com/loadimpact/k6/issues/570 and it likely should be disabled by default, to avoid excessive metric spam. Even then, it may be more useful as a per-iteration or per-group metric (like `iteration_duration` or `group_duration`) instead of being emitted by each `sleep()` call.

**Comment by olegbespalov** [comment]
The team decided to close this as not planned.
