### ISSUE TITLE
Ideas for improving the group() built-in function

### ISSUE THREAD

**Issue by na--** [grafana/k6#884]
It would currently be quite difficult to implement, but ideally, once https://github.com/loadimpact/k6/issues/883 is resolved, we may be able to partially override some of the global options in a `group()` call. That way we can set different tags for all metrics emitted in that group, or set local default HTTP options once https://github.com/loadimpact/k6/issues/761 is implemented (especially useful for stuff like authentication). 

In a way, something like that [already happens](https://github.com/loadimpact/k6/blob/d219b19a0353ddc73063ff3c45bc17444f0771c3/js/modules/k6/k6.go#L84-L86), since the `group` system tag's value is changed inside of the `group()` call, but it's not flexible or user-configurable at all.

**Comment by na--** [comment]
I've mentioned in in the linked issue (https://github.com/loadimpact/k6/issues/891#issuecomment-453919783), but a [users's question on Slack](https://k6io.slack.com/archives/C3E688J8Z/p1564585735007800) reminded me of that idea to extend this proposal, so it can help with some use cases where users don't want specific metrics measured. Specifically, we should be able to add an option/parameter to the `group()` call (or something else) that basically silences all metrics that would have been emitted during the execution of the callback function. I think this should be achievable by replacing the [metrics channel](https://github.com/loadimpact/k6/blob/c53607db0ef32be9535d1b516c90275fb37a54cf/lib/state.go#L62) in the `lib.State` object, like how `group()` [currently replaces the `Group`](https://github.com/loadimpact/k6/blob/c53607db0ef32be9535d1b516c90275fb37a54cf/js/modules/k6/k6.go#L85-L87). Though it's an open question about the issues this approach would have when we have event loops (https://github.com/loadimpact/k6/issues/882)...

**Comment by mstoykov** [comment]
Given how `group` does not work with `async` and we will likely have to figure out somethign for it's current usage and that this will likely have to do with https://github.com/tc39/proposal-async-context and/or [goja#AsyncContextTracker](https://pkg.go.dev/github.com/dop251/goja#AsyncContextTracker). 

I have opened https://github.com/grafana/k6/issues/3392 where we will explore making this async compatible and hopefully more generic.
