### ISSUE TITLE
K6 forces use of strict mode

### ISSUE THREAD

**Issue by ghost** [grafana/k6#914]
```javascript
import http from "k6/http";
import { sleep } from "k6";

function test() {
    arguments.callee;
}

export default function() {
  test();
  http.get("http://test.loadimpact.com");
  sleep(1);
};
```
Running the above script in K6 results in the following error:

`ERRO[0000] TypeError: 'caller', 'callee', and 'arguments' properties may not be accessed on strict mode functions or the arguments objects for calls to them`

Expected behavior: 

The above script should run fine. K6 should not force developers to opt-in to strict mode. This becomes a particular issue when trying to use (browserified) npm modules which violate strict mode.

Edit: I am using v0.23.1 of K6.

**Comment by MStoykov** [comment]
Hi, sorry for the slow response :(. This appears to be from babel, which we use to get the majority of ES6+ javascript functionality. 
We should probably properly update it - we are at version 6 and some `latest` preset which we are not exactly certain what exact version it is :( . Obviously when we do it we are going to remove the strict plugin but we should probably cherry pick what we want too in order to know what exactly we use and we don't ;). 
If you would like you can try to figure all this things out and make PR I will gladly look it over :)

**Comment by na--** [comment]
@MStoykov, this doesn't seem like a babel thing, more like a goja issue, see [this](https://github.com/dop251/goja/blob/084ecb42b053a72161c33ce1c36a69af5e9c9dd7/runtime.go#L754-L757). In k6, we explicitly call the goja methods with strict mode enabled, even with [`--compatibility-mode=base`](https://k6.io/docs/using-k6/javascript-compatibility-mode):
https://github.com/loadimpact/k6/blob/229c3c3ca0bbf8ffe2b1c1ec93c6a10404416d5d/js/compiler/compiler.go#L74-L75
https://github.com/loadimpact/k6/blob/229c3c3ca0bbf8ffe2b1c1ec93c6a10404416d5d/js/compiler/compiler.go#L89
https://github.com/loadimpact/k6/blob/229c3c3ca0bbf8ffe2b1c1ec93c6a10404416d5d/js/bundle.go#L83

And I tested it, this script fails with the same error with `--compatibility-mode=base`:
```js
var http = require('k6/http');
var sleep = require('k6').sleep;

function test() {
    arguments.callee;
}

exports.default = function () {
    test();
    http.get("http://test.k6.io");
    sleep(1);
};
```

All of that said, I am not sure this is something we should change. AFAIK, strict mode is a good thing, and we haven't had any complaints besides this one, I think, and `arguments.callee` seems to have [viable workarounds](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/arguments/callee). Given that we've silently used strict mode for the whole history of k6, it's probably fine if we continue to do so... :sweat_smile: So, adding `evaluation needed` here for now, but :+1: from me for closing the issue as a `wontfix`. @MStoykov, @imiric, @simskij, what do you think?

**Comment by MStoykov** [comment]
Well at the time I answered compatibility-mode wasn't a thing for [another 11 months](https://github.com/loadimpact/k6/releases/tag/v0.26.0). But regardless of that, babel does add `"use strict"` to the top of anything it transforms(because of a plugin that we have), we can probably configure it not to, but as you've mentioned there is probably no reason, and running in strict is the better option in my opinion as well.

**Comment by imiric** [comment]
I agree with you that strict mode is preferable, but OTOH I see how it would cause issues if some libraries do not conform to it, and agree with OP that k6 shouldn't enforce this and should leave it up to users to enable it.

So I'm slightly leaning towards labeling this as `low prio` and fixing it, if we can configure Babel to not add it automatically.

**Comment by na--** [comment]
> some libraries do not conform to it

Citation needed :sweat_smile: I am sure there are libraries like that, but I imagine that the majority are not... I guess we can add a new `--compatibility-mode` specifically for no strict mode, I just don't think it's worth it to do so...

**Comment by imiric** [comment]
Yeah, I'm not so sure about it either. The most intuitive UX would be to interpret `'use strict'` as usual, but disabling it by default after all this time doesn't sound safe. So if you feel strongly about it, I'm OK with closing this.

**Comment by MStoykov** [comment]
> The most intuitive UX would be to interpret 'use strict' as usual, 

We can't change that as that is done by goja as per the specification - if the line is there the following function/"file" is in strict mode,  but we can:
1. disable the plugin in babel that adds it to the top of the transformed file
2. not call goja with strict mode enforced so it is at least not strict if the line isn't present.

**Comment by na--** [comment]
hmm let's leave this open for a while, to see if anyone else complains or expresses desire for disabling strict mode, we can reevaluate again in the future
