### ISSUE TITLE
Return summary sending in datadog collector

### ISSUE THREAD

**Issue by mstoykov** [grafana/k6#916]
In the #915  we are adding datadog collector to which @ivoreis added the ability to send summary data to datadog. 
This has some problems - need to be configurable and the data has bash color sequences so I removed it in https://github.com/loadimpact/k6/pull/915/commits/cb3a3849d07686ebf9112408e5978fe51c66ad68 , but we would like it to have it in the future. It should also probably be done in a more centralized way :)

**Comment by olegbespalov** [comment]
We no longer have a datadog output, and the statsd also [is moving to an extension](https://github.com/LeonAdato/xk6-output-statsd), so we closing this issue as not planned.
