### ISSUE TITLE
Stabilize TestRealTimeAndSetupTeardownMetrics on windows/appveyor

### ISSUE THREAD

**Issue by mstoykov** [grafana/k6#919]
Currently this test is failing more than 50% of the time because of timings. This might be because some specifics on windows or just appveyor doesn't give us enough CPU time to finish the tests consistently. Either way the constant failing is annoying and is getting in the way of developing by making us constantly rerunning the tests.

**Comment by na--** [comment]
I can think of only one way to avoid using timings in this test - by using long-running HTTP requests. That way we can synchronize the JS and Go code of the tests - the HTTP server on the Go side can delay responding to the JS HTTP requests until it reads some required metrics from the metrics output channel. That way we can verify that they're actually sent in real time, and not at the end of the iteration.

**Comment by mstoykov** [comment]
This seems to have been fixed - probably due to appveyor swap of github actions ... maybe not. 

But it is no longer happening in my experience so closing
