### ISSUE TITLE
Introduction of a documentation convention

### ISSUE THREAD

**Issue by bgilner** [grafana/k6#942]
We would like to see an idiomatic way to set up command-line documentation. For example, something like a `--help` where I can set up something in the .js (like a k6-aware function) to spit out the purpose/usage of the test(s). 

Similar to most DOS console apps that display usage with `-h` or `/h`

One idea is to overload `--help` to return custom-defined help instead of general help. If so, maybe append the custom help with a message such as 'For general k6 help, use --help without specifying a test file: k6 --help'

**Comment by mstoykov** [comment]
This issue has never been picked up or discussed over the last 4 years.

Internally we looked at it very quickly, and we are not certain we will ever do it, but it will likely need to be as part of a lot more changes. 

As we are trying to clear unclear and unlikely to be picked up issues - I am going to close this.
